### ISSUE TITLE
`onEvent` is called multiple times

### ISSUE THREAD

**Issue by kamoljan** [greenrobot/EventBus#116]
```
@Override protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  setContentView(R.layout.activity_item_view);
  ButterKnife.inject(this);
  EventBus.getDefault().registerSticky(this);
}

@Override protected void onDestroy() {
  EventBus.getDefault().unregister(Events.AdChosenEven.class);
  super.onDestroy();
}

public void onEvent(Events.AdChosenEven adChosenEven) throws IOException {
  adId = adChosenEven.adId;
  getViewItem();
  EventBus.getDefault().removeStickyEvent(Events.AdChosenEven.class);
}
```

`onEvent` is called multiple times, 
however,  `EventBus.getDefault().postSticky(new Events.AdChosenEven(adId));` calles onces.

Why, it is bug or I am doing wrong?

**Comment by castrojr913** [comment]
Guys, I'm suffering the same issue with my enterprise application too. I think you should open the issue again and inquire the cause of the problem. I notice that several developers are complaining about the same bug.

**Comment by kamoljan** [comment]
@castrojr913 can you share your code?

**Comment by david-alejandro-reyes-milian** [comment]
Hello, guys, I'm experiencing similar issues here. My code is like:
`
@Override
    public void onResume() {
        super.onResume();
        if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        EventBus.getDefault().unregister(this);
    }
`
Any ideas?
