### ISSUE TITLE
RuntimeException when implementing proguard with EventBus AsyncExecutor

### ISSUE THREAD

**Issue by z0lope0z** [greenrobot/EventBus#131]
Hi! I'm not sure how to file reports and I'm not sure what's going on as well.
Basically, I'm currently implementing proguard in my project and this line of code fails:

```
...
 AsyncExecutor.builder().failureEventType(FailedEvent.class)
...
```

throwing the exception [(here)](https://github.com/GeekZooStudio/ECMobile_Android/blob/master/android/libs/EventBus/EventBus/src/de/greenrobot/event/util/AsyncExecutor.java#L90,L95):

```
...
java.lang.RuntimeException: Failure event class must have a constructor with one parameter of type Throwable
    at de.greenrobot.event.util.AsyncExecutor.<init>(AsyncExecutor.java:104)
    at de.greenrobot.event.util.AsyncExecutor.<init>(AsyncExecutor.java:32)
...
```

unless I add 

```
-keep class FailedEvent { *; }
```

to my proguard-rules.txt

If it's an expected behavior, should the best course of action be to include it in the [wiki](https://github.com/greenrobot/EventBus/blob/master/HOWTO.md#proguard-configuration)?

**Comment by sosite** [comment]
Unfortunately current [ProGuard config](https://github.com/greenrobot/EventBus/blob/master/HOWTO.md#proguard-configuration) doesn't work for me:

```
-keepclassmembers class * extends de.greenrobot.event.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
```

I still received below `runtime exception`:
```
java.lang.RuntimeException: Failure event class must have a constructor with one parameter of type Throwable
```
