### ISSUE TITLE
Suggested Proguard config in HOWTO.md obfuscates array onEvents

### ISSUE THREAD

**Issue by rcgroot** [greenrobot/EventBus#136]
Problem: 
Current HOWTO.md suggests a Proguard line as such:

    -keepclassmembers class ** {
        public void onEvent*(**);
    }

If an registered object has for example 2 methods like:

    public void onEvent(Client client){}
    public void onEvent(Client[] clients){}

the second method gets removed by proguard because the ** does not match primitive arrays.

A *** in the parameter match of the proguard config will match the Client[] type and keep the method around after proguard has run.

Ref: http://proguard.sourceforge.net/manual/usage.html

**Comment by sdeff** [comment]
I'm not sure if this is the right place to post it but adding:

```-keepclassmembers,includedescriptorclasses class ** { public void onEvent*(**); }```

To my ProGuard/DexGuard config did help me with [this issue](https://github.com/greenrobot/EventBus/issues/133).

**Comment by soochun-deali** [comment]
fix with below rule added

dexguard version : 8.6.06
eventbus version : 3.2.0


-keepnames class org.greenrobot.eventbus.**
-keep class org.greenrobot.eventbus.** { *; }
