### ISSUE TITLE
Toast not shown in onEvent()

### ISSUE THREAD

**Issue by globus243** [greenrobot/EventBus#162]
Hi,

Just needed a quick way to show a Toast in an Activity if something in an other non-activity class fails.
Found this librarie and used your How-To to quickly implement it.

This is virtually copy and pasted from your how to. but the Toast won't show up even though the Log triggers. This Snippet is in my MainActivity. Toasts from other places in the code are working.
```Java
    @Override
    public void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
    }

    @Override
    public void onStop() {
        EventBus.getDefault().unregister(this);
        super.onStop();
    }

    public void onEvent(errorEvent event){
        Looper.prepare();
        Log.v("Error! onEvent : ", event.message);
        Toast.makeText(MainActivity.this, event.message, Toast.LENGTH_LONG).show();
    }
```

**Comment by livotov** [comment]
try to use onEventMainThread instead onEvent

**Comment by globus243** [comment]
cool, thanks, that worked!
Working Code:

```Java
    @Override
    public void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
    }

    @Override
    public void onStop() {
        EventBus.getDefault().unregister(this);
        super.onStop();
    }

    public void onEvent(errorEvent event){
        Looper.prepare();
        Log.v("Error! onEvent : ", event.message);
        Toast.makeText(MainActivity.this, event.message, Toast.LENGTH_LONG).show();
    }
```

**Comment by livotov** [comment]
yep, this is because onEvent is called on the same thread as event producer and onEventMainThread is guaranteed to be called only  on UI thread regardless from where event was published

**Comment by globus243** [comment]
Ahh okay, no wonder it didn't worked out. Thank you for explanation!

Ticket can be closed

**Comment by dreamcatcha** [comment]
Even with "onEventMainThread" I still get the issue with the need to call looper.prepare(); any ideas?

**Comment by tilmanginzel** [comment]
Which EventBus version are you using? `onEventMainThread` was necessary in EventBus 2, but EventBus 3 uses annotations.

```java
@Subscribe(threadMode = ThreadMode.MAIN)
public void onEvent(AnyEventType event) {/* Do something */};
```
