### ISSUE TITLE
Subscribe annotation fails for event on main thread

### ISSUE THREAD

**Issue by fabrice999** [greenrobot/EventBus#191]
If you add @Subscribe annotation to your onEventMainThread method, it will publish the event on a thread different than the main thread.

I can see in the implementation that the threadMode default is PostThread.
{
public @interface Subscribe {
    ThreadMode threadMode() default ThreadMode.PostThread;
}

**Comment by rjbrock** [comment]
Yes this is the intended behavior now.

**Comment by fabrice999** [comment]
What is the purpose of onEventMainThread() if it is not publishing in the main thread?

**Comment by rjbrock** [comment]
I am not sure what you are referring to, was this in the docs? 

But just so you know, with annotations there is no longer a reason to name your methods onEvent or onEventMainThread.  You can name them anything and just annotate them.

So what used to be public void onEventMainThread(LoginEvent event) 

is now:

@Subscribe(threadMode = ThreadMode.MAIN)
public void onLoginEvent(LoginEvent event)

**Comment by rjbrock** [comment]
@greenrobot this can be closed

**Comment by fabrice999** [comment]
Ok will test as soon as I can, thanks

**Comment by rjbrock** [comment]
@fabrice999 Cool, let me know if you have any other questions
