### ISSUE TITLE
Integrate Volley with EventBus

### ISSUE THREAD

**Issue by ashwanikumar04** [greenrobot/EventBus#198]
Hello:

Thanks for this awesome library. 
I use [Volley](http://developer.android.com/intl/zh-cn/training/volley/index.html) in my applications for handling network calls. Currently I use Interface to receive responses from Volley. 
Interface has onSuccess and OnError methods.
I am trying to use EventBus to recouple this. 
What can be the approach differentiate two calls? Do I have to make separate Events (One from onSuccess and onError) for each call?
Thanks in advance

**Comment by rjbrock** [comment]
You can just create an event for each success or error (such as login). You can also create an event that takes an argument and subscribe for that.  ie: new LoginEvent(FAILURE) (where LoginEvent takes an enum)
