### ISSUE TITLE
ThreadMode enum doesn't use standard enum naming conventions

### ISSUE THREAD

**Issue by themichaelscott** [greenrobot/EventBus#203]
The enums in ThreadMode.java are:
PostThread, MainThread, BackgroundThread, Async

but Java conventions would have them be:
POST_THREAD, MAIN_THREAD, BACKGROUND_THREAD, ASYNC

http://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
"Because they are constants, the names of an enum type's fields are in uppercase letters."

**Comment by rjbrock** [comment]
@themichaelscott This is a good point! I kept the capitalization from the method names, but I should have made them uppercase.

You can submit a pull request to change this if you would like
