### ISSUE TITLE
How to stop onEventMainThread

### ISSUE THREAD

**Issue by tuanth89** [greenrobot/EventBus#220]
First of all, thank for project.
My question: How to stop onEventMainThread  after destroy fragment ??
Some events i don't want to excute after destroy because it maybe no found views and lead to crash app
Thanks

**Comment by livotov** [comment]
simply unsubscribe your fragment class instance from event bus in the appropriate fragment lifecycle method

**Comment by tuanth89** [comment]
@livotov thank for reply.
But the fragment received event. therefore, when destroy my code in that event still execute, lead to crash.
At fragment, i added the function:
<pre><code>
@Override
    public void onDestroy() {
        super.onDestroy();
        try {
            EventBus.getDefault().unregister(this);
        } catch (Throwable t) {
            //this may crash if registration did not go through. just be safe
        }
    }
</code></pre>

**Comment by livotov** [comment]
Your fragment instance will not receive any event after the call to EventBus.getDefault().unregister(this).

**Comment by livotov** [comment]
are you sure  you're talking about the onEventMainThread ?
onEventMainThread is called on the main (UI) thread. You cannot perform any long/background operations there. Also, even if you're doing smth long there, your UI will freeze and onDestroy method will not be called until you finish your event work. So no collision should happen there.

If you're receiving even on other thread (onEventBackgroundThread or similar), this is your event code responsibility to abort any activity when external conditions changes (e.g. fragment is not more alive)

**Comment by tuanth89** [comment]
@livotov, 
Fragment receive event and executing then i destroy while It not yet finish (still progressing) ---> crash app.

**Comment by livotov** [comment]
see my comment above

**Comment by ppamorim** [comment]
A palliative thing to do is:

Use isFinishing() for Activities or isAdded() for Fragments.

**Comment by tuanth89** [comment]
@livotov,  thank for reply.
In my case, I show data to listview, after call update function (check data change) in OnEventMainThread (set adapter again listview if data change). user click back when event still progressing lead to : no view found(adapter view) and crash.
Hope, everyone understand what i said :)

@ppamorim, i'll try.
Thank

**Comment by tuanth89** [comment]
which way to dismiss or ignore in case no view found above ???
Thanks

**Comment by livotov** [comment]
Could you please paste your code here, as I can't understand how you can end with a dead fragment state while executing your code on a main thread. 

Also, better call the eventbus.unregister(this) first, then super.onResume()

**Comment by oakkitten** [comment]
@tuanth89 onDestroy is not guaranteed to be called, and it's wrong to update ui when it's not being shown anyway. subscribe in onStart and unsubscribe in onStop and remove try/catch—you'll just mask a problem you will run into later

**Comment by tuanth89** [comment]
Thank everyone. i fixed problem by don't allow user back or destroy fragment while executing update.
BTW, I want to stop event while it's executing. Is possible ???

**Comment by eneim** [comment]
please show your fragment's code. it's easier too see what happened. or at least the crash log

**Comment by eneim** [comment]
Furthermore, IMO the best place to unregister a event  is inside the onPause or onStop method. where your UI is completely hidden. In fact, if you use your fragment with its backstack (use addToBackStack() on transaction, the fragment's onDestroy is not guarantee to be called --> crash)

**Comment by tuanth89** [comment]
@eneim thank for reply.
Exactly, i used it with backstack on transaction.
Could you suggest or give me advice about this problem ???
Thanks.

**Comment by eneim** [comment]
@tuanth89 The backstack works as follow: it add your fragment's state to its stacks (in reality, it saves the fragment transaction), call fragment's onDestroyView BUT NOT onDestroy. Note that in case you set your fragment to retain its instance (via ```Fragment#setRetainInstance(boolean)), the same thing happens (onDestroyed not called). For a better look of Fragment's life cycle, take a look at [this](https://github.com/xxv/android-lifecycle), it's not the latest update, but you can test it by yourself.

My hint in your case: move your ```EventBut.getDefault().register(MyFragment.this)``` into ```onStart()``` or ```onResume()``` and ```EventBut.getDefault().unregister(MyFragment.this)``` into ```onStop()``` or ```onPause()```. Those lifecycle methods are directly relate to your UI appearance.

**Comment by tuanth89** [comment]
@eneim thank for reply.
I realize this problem belong to me,i fixed and it seems not occurs.
One again, thank you so much.
