### ISSUE TITLE
Question: Sticky event thread

### ISSUE THREAD

**Issue by sosite** [greenrobot/EventBus#226]
In [HOWTO](https://github.com/greenrobot/EventBus/blob/master/HOWTO.md#delivery-threads-and-threadmodes) we can read that:

>**PostThread:** Subscriber will be called in the same thread, which is posting the event

```
// Called in the same thread (default)
public void onEvent(MessageEvent event) {
    log(event.message);
}
```

Ok, using classic `post()` we certainly have that behaviour. But what happens when we use `postSticky()`?

**Comment by livotov** [comment]
probably the same thread where .subscribe() was called ?

**Comment by sosite** [comment]
But when we recreate eg. an activity then we still hold the same thread?

**Comment by livotov** [comment]
yes, as activity lifecycle methods like onResume, etc are called on a main ui thread
