### ISSUE TITLE
in onEvent(Object object) method post event don't work.

### ISSUE THREAD

**Issue by artisan-android** [greenrobot/EventBus#227]
I send an event, and handling events.
   
     public void onEvent(final ASHandleSelectedProductEvent event) {
        
        AsFrameProject project = (AsFrameProject) ASModelLocator.onAttachProject();
        AsSpec spec = ASModelLocator.onAttachSpec();
        ASEventBusHelper.post(new ASSetProductEvent(event.product));

        String style = AsFrameDefaultValueHelper.getFrameDefaultStyle(spec, project);
        ASEventBusHelper.post(new ASSetFrameStyleEvent(style));

        String matte = AsFrameDefaultValueHelper.getFrameDefaultMatte(spec, project);
        ASEventBusHelper.post(new ASSetMatteEvent(matte));

        String color = AsFrameDefaultValueHelper.getFrameDefaultColor(spec, project);
        ASEventBusHelper.post(new ASSetFrameColorEvent(color));

        String paper = AsFrameDefaultValueHelper.getFrameDefaultPaper(spec, project);
        ASEventBusHelper.post(new ASSetPaperEvent(paper));

        String border = AsFrameDefaultValueHelper.getFrameDefaultBorderOption(spec, project);
        ASEventBusHelper.post(new ASSetCanvasBorderEvent(border));

        int borderColor = ASBorderBusiness.getDefaultBorderColor();
        ASEventBusHelper.post(new ASSetCanvasBorderColorEvent(borderColor));
    }

in onEvent() method post event don't work. I find in this API .
PostingThreadState postingState = currentPostingThreadState.get(); stop all event.

**Comment by AgentKnopf** [comment]
Did you mean that onEvent is not being called? Are you registering the class this method is located in before the event is being fired? The events you're firing inside onEvent would not be processed in the same method, but would require an onEvent method like this one for instance:

ASEventBusHelper.post(new ASSetProductEvent(event.product));

should require an onEvent method like this:

 public void onEvent(final ASSetProductEvent event)

If the above is not your issue, maybe elaborate on what the actual problem is.

**Comment by artisan-android** [comment]
Yes, I register the class this method. Actual problem is when I was sent  an event.
ASEventBusHelper.post(new ASHandleSelectedProductEvent (product));

public void onEvent(final ASHandleSelectedProductEvent event) {};
handle this event and doing something.

Simultaneous transmission events in the method
public void onEvent(final ASHandleSelectedProductEvent event) {
        ASEventBusHelper.post(new ASSetProductEvent(event.product));
        .........
}

I think (public void onEvent(final ASSetProductEvent event)) this method should be synchronized inside in
method of (public void onEvent(final ASHandleSelectedProductEvent event)). 
EventBus can only perform one event simultaneously?

**Comment by AgentKnopf** [comment]
I wrote a small class that attempts something similar to what you are doing and ran it through a unittest which prints out a string, then an int and then a boolean. The methods were all called correctly:

https://gist.github.com/AgentKnopf/ab95ed146297d0a7e620

Could you write up a unittest that covers your usecase and verify if it passes/fails? Or let me know, if I misunderstood your use-case (making multiple Eventbus.post calls from within an onEvent method.

**Comment by artisan-android** [comment]
Hi, I wrote a unit test and  it fails.

```
public class AsEventValue {

    public String value;

    public AsEventValue(String value) {
        this.value = value;
    }
}
```
```
public class AsPrintBoolean {

    private boolean value;

    public void register(){
        EventBus.getDefault().register(this);
    }

    public void unregister(){
        EventBus.getDefault().unregister(this);
    }

    public void onEvent(Boolean value){
        this.value = value;
        System.out.println("value--->"+ value);
    }

    public boolean isValue() {
        return value;
    }
}
```
```
public class AsPrintInteger {

    private int value;

    public void register(){
        EventBus.getDefault().register(this);
    }

    public void unregister(){
        EventBus.getDefault().unregister(this);
    }

    public void onEvent(Integer value){
        this.value = value;
        System.out.println("value--->"+ value);
    }

    public int getValue() {
        return value;
    }
}
```
```
public class AsPrintValue {

    private String value;

    public void register() {
        EventBus.getDefault().register(this);
    }

    public void unregister() {
        EventBus.getDefault().unregister(this);
    }

    public void onEvent(AsEventValue value) {
        this.value = value.value;
        System.out.println("value--->" + value.value);
    }

    public String getValue() {
        return value;
    }
}
```
```
public class AsEventBusTest {

    AsPrintBoolean mPrintBoolean = new AsPrintBoolean();
    AsPrintInteger mPrintInteger = new AsPrintInteger();
    AsPrintValue mPrintValue ;

    @Before
    public void setUp() {
        mPrintValue = new AsPrintValue();
        mPrintBoolean.register();
        mPrintInteger.register();
        mPrintValue.register();
    }

    @After
    public void tearDown() {
        mPrintBoolean.unregister();
        mPrintInteger.unregister();
        mPrintValue.unregister();
    }

    @Test
    public void testEventBus() {
        String text = "Carry";
        EventBus.getDefault().post(new AsEventValue(text));
        assertEquals(text, mPrintValue.getValue());

        int intValue = 10;
        EventBus.getDefault().post(intValue);
        assertEquals(intValue, mPrintInteger.getValue());

        EventBus.getDefault().post(true);
        assertTrue(mPrintBoolean.isValue());
    }

}
```
Thank you for your help~~^^

**Comment by AgentKnopf** [comment]
Hey there - thanks for the unittest - that's something we can work with :+1: . I'll add the test to my setup later and try it out in order to see where it fails.

**Comment by AgentKnopf** [comment]
Ok - I ran the tests and they pass, the only difference is that I had AsEventBusTest  extends TestCase. Could you let me know which import statement you are using for the assert statements? Also - it would help to know on which line the testcase fails for you.

**Comment by artisan-android** [comment]
Oh , I found that using an intermediate layer encapsulation Eventbus. Is my own problem with the code. thanks ~~~ Have good job.

**Comment by artisan-android** [comment]
When I  ran the tests I mock a EventBus instance to replace default instance. So test fails. 
```
EventBus.setDefaultInstance(mock(EventBus.class));
```
This is not good method~~
