### ISSUE TITLE
Register to generic type events

### ISSUE THREAD

**Issue by romainpiel** [greenrobot/EventBus#23]
Hi, I'm currently using EventBus in my app. I really like it it makes stuff much simpler.
I'm just facing a small issue which is an edge case I guess.

I would like to subscribe to generic classes, how do I do that:

``` java
public onEvent(MyEvent<A> event) {
// Issue: I receive all events of the class MyEvent, event stuff like MyEvent<B>
}
```

**Comment by ExtinctAmoeba** [comment]
Still in 2018?!
