### ISSUE TITLE
Android Studio Feature Request: Website Browser Tab

### ISSUE THREAD

**Issue by soapysoft** [greenrobot/EventBus#242]
Is it possible to have a tab similar to the code tabs, that will display a website.

I would find it useful to have the Android SDK docs, or stackoverflow website open in a tab inside the IDE, instead of switching back and forth between web browser and IDE.

**Comment by ppamorim** [comment]
This project is not the most correct location to ask something/request a support of Android Studio or another project. It don't have any relation.

**Comment by soapysoft** [comment]
x.x. My googlefu is poor tonight.

#request delete (lets never speak of this again)

**Comment by intrications** [comment]
@soapysoft You can close the issue yourself. Just click the "Close Issue" button below. That will remove it from the list of open issues, at least.

**Comment by hasnain-ahmad** [comment]
@ppamorim Kindly guide which forum or portal is used to suggest google to add/develop features/plugins/tools for Android Studio IDE.
