### ISSUE TITLE
Event post timeout problems

### ISSUE THREAD

**Issue by andymiao858** [greenrobot/EventBus#243]
I want to ask whether butterknife support event time out function. 
e.g. I have 2 fragments, when one of them finish init and post an event, however, the other fragment is initializing, and has not registered, so if i post an event this time, the other fragment can not receive. Can we set the event time out individualy or other way to solve the problem. when the subscriber finish registering, they can also received the event that posted by other before. 

Thanks a lot.

**Comment by livotov** [comment]
sticky events ?

**Comment by andymiao858** [comment]
Yes, sticky event can solve the problems. But i want a normal event, since sticky event alway keep in memory although i consume it. I wanna a event wait until i consume it, Of course, i can removestickyevent eveytime when i receive it, but it is more complex. Could i have a better way to solve this problem?

**Comment by druidamix** [comment]
I found my problem.
In every module I had replicated the event class.
So the post used one class and the receiver another.

Finally, I removed the duplicated. Then I used the same event class.
