### ISSUE TITLE
eventbus 3.0  fragment post(event)  

### ISSUE THREAD

**Issue by renwfy** [greenrobot/EventBus#267]
i sent post(event) in fragment,    at other activity can't receive msg

fragment :
`EventBus.getDefault().post(new QuestionEvent(1));`

activity:
`EventBus.getDefault().register(this);`

```
 @Subscribe(threadMode = ThreadMode.MAIN)
    public void onMessageEvent(QuestionEvent event) {
        //index = event.qIndex;
        //getData(event.qIndex);
    }
```

am i miss…… ？

**Comment by greenrobot-team** [comment]
Is the fragment part of the activity you want to receive the event in? If the activity is some other activity currently not visible then this might not work.

**Comment by greenrobot-team** [comment]
No response. Closing.
