### ISSUE TITLE
Multiple onEventAsync at the same time

### ISSUE THREAD

**Issue by elsennov** [greenrobot/EventBus#270]
Hi All,

I have an issue while doing some network tasks using onEventAsync. I design the tasks to be executed at the same time. But EventBus didn't execute all the tasks at the same time. It was like queued. I believed it is because of the thread pool. And I know that there is a statement

> Avoid triggering a large number of long running asynchronous handler methods at the same time to limit the number of concurrent threads.

Could somebody help me to solve this problem? I want to still use onEventAsync to deliver some network tasks at the same time. Is there any way to solve this? Thanks :)

**Comment by william-ferguson-au** [comment]
You can control how many threads are available in the thread pool used to deliver async events. Do so by configure the `ExecutorService` to use. See `EventBusBuilder.executorService()`
