### ISSUE TITLE
Activity can not receive Event when app in the background.

### ISSUE THREAD

**Issue by dinhthaidaica** [greenrobot/EventBus#275]
When I push my App to background, My Activity does not receive Event while Fragment does well.
I post my detail question in [here](http://stackoverflow.com/questions/36032422/eventbus-activity-does-not-receive-event-when-app-is-in-the-background?noredirect=1#comment59714678_36032422). Any guy can help me? 
Thanks in advance.

**Comment by xyhuangjinfu** [comment]
do you call EventBus.unregister() method in the lifecycle method of your Activity?

**Comment by greenrobot-team** [comment]
This is discussed at length at the mentioned [Stackoverflow post](http://stackoverflow.com/questions/36032422/eventbus-activity-does-not-receive-event-when-app-is-in-the-background?noredirect=1#comment59714678_36032422). Closing.
