### ISSUE TITLE
Is there a way to turn off the log 'No subscribers registered for event class xxx.xxx'?

### ISSUE THREAD

**Issue by nezen** [greenrobot/EventBus#280]
Is there a way to turn off the log 'No subscribers registered for event class xxx.xxx'?

**Comment by tilmanginzel** [comment]
The [documentation](http://greenrobot.org/eventbus/documentation/configuration/) describes two different options.

1) Create your own EventBus instance and configure it
```java
EventBus eventBus = EventBus.builder().logNoSubscriberMessages(false)
    .sendNoSubscriberEvent(false).build();
```

2) Configure the default instance prior first usage
```java
EventBus.builder().logNoSubscriberMessages(false).installDefaultEventBus();
```

**Comment by nezen** [comment]
problem solved, Thanks a lot !
