### ISSUE TITLE
Support for @Subscribe in kotlin

### ISSUE THREAD

**Issue by dave08** [greenrobot/EventBus#286]
I made a few subsciber classes in Kotlin, but my index class does not get generated. I get this error at build time:

warning: The following options were not recognized by any processor: '[eventBusIndex]'

Is there some solution? I configured my build.gradle exactly like on your site...

Thanks!

**Comment by dave08** [comment]
It could be that kapt has to be used for kotlin, but how do I configure it? Is this right?

These are the dependencies:

    compile 'org.greenrobot:eventbus:3.0.0'
    kapt 'org.greenrobot:eventbus-annotation-processor:3.0.1'
    provided 'org.glassfish:javax.annotation:10.0-b28'

This is how I got the args:

kapt {
    generateStubs = true
    arguments {
        arg('eventBusIndex', 'com.lomdaat.coreservices.sync.MyEventBusIndex')
    }
}

I've tried but it still doesn't work.. only the previous error disappears. But there are a lot of:

Error:Subscriber method must have exactly 1 parameter
Error:@Subscribe is only valid for methods

**Comment by romansl** [comment]
More information: `kapt` adds his own annotations to `annotations` array [here](https://github.com/JetBrains/kotlin/blob/cb4702c4064b1edfb8ac3d53d421df34de9b140a/libraries/tools/kotlin-annotation-processing/src/main/kotlin/org/jetbrains/kotlin/annotation/AnnotationProcessorWrapper.kt#L132).

**Comment by romansl** [comment]
Reported to jetbrains: https://youtrack.jetbrains.com/issue/KT-12201

**Comment by dave08** [comment]
Thank you for the response, I'm sorry I didn't write back then, I was busy with other task. Now I'm back to this and I'm wondering if there is a workaround? Our app is using eventbus for very important functionality, and it would be nice to have this optimization. Otherwise, should I switch back to version 2.4?

Thanks again! And also for the wonderful library!

**Comment by MrThreepwood** [comment]
Is there no current workaround for this? I am using kapt for the annotation processor and have it generating for the java files, but it's still not working on kotlin.

**Comment by romansl** [comment]
Tri this:
```
apply plugin: "kotlin-kapt"
```

**Comment by greenrobot-team** [comment]
No response, so I guess this works now. Closing. -ut

**Comment by deviant-studio** [comment]
no. it still broken

**Comment by greenrobot-team** [comment]
@deviant-studio Any further details? [Looking at the issue report](https://youtrack.jetbrains.com/issue/KT-12201) this was fixed in Kotlin 1.0.6.

**Comment by deviant-studio** [comment]
@greenrobot-team sorry, never mind. it works now
