### ISSUE TITLE
does eventbus support List of javabean?

### ISSUE THREAD

**Issue by ourgit** [greenrobot/EventBus#290]
when I post List<PlainJavaBean> with eventbus, gradle tell me GeneratedSubscriberIndex need identifier, so fail to compile. What need I do to post a List of javabean? thanks

**Comment by ourgit** [comment]
Well, when  I use Object as my subscribe parameter, it works, however I don't feel comfortable this way. When dig the generated code, I see "List<com.example.javabean>.class" rather than "List<com.example.javabean.class>" ,that is the point. Any way to improve?

**Comment by greenrobot-team** [comment]
EventBus currently [only works with simple Java objects](http://greenrobot.org/eventbus/documentation/how-to-get-started/). As you said you might just create a wrapper-event that includes your list, for example:

```java
public class MessageEvent {
    public final List<SomeItem> items;

    public MessageEvent(List<SomeItem> items) {
        this.items= items;
    }
}
```
