### ISSUE TITLE
Send data from Activity to Fragment and perform FragmentTransaction

### ISSUE THREAD

**Issue by pmk2429** [greenrobot/EventBus#297]
Hello

I have been trying to work on a simple feature where I am trying to pass my custom event object from `FragmentB` to `Fragment A`. 

> What are the best possible ways to do that?

 
I have tried the following options:

### 1)
In `FragmentB`, I post an event 
`EventBus.getDefault().post(new Sources(24, "my data"));`

and then I get the event in the parent/container` Activity`    

```
    @Subscribe
    public void getSources(Sources sources) {
        Log.i("~!@#$", "Activity: " + sources.type + " : " + sources.name);
        getSupportFragmentManager().beginTransaction().add(R.id.container_main, new PlaceholderFragment()).commit();
    }

```
Immediately, after getting the event object, I try to perform the FragmentTransaction and replace the `FragmentB `with `FragmentA `since I need the event object in `FragmentA`. But I cant get it working.

**What am I missing here?**

Any help is appreciated.

**Comment by william-ferguson-au** [comment]
Q: Is `getSources` called when you post your event?

If no, then have you registered your Activity as a subscriber?
If yes, then this is not an EVentBus question, it is a general Android Fragment question.

**Comment by greenrobot-team** [comment]
You can only pass data through an event between fragments if both are registered at the same time. In your case it might be possible to work with a [sticky event](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/) that the new fragment can query for once it is created.

Closing as there was no response. @william-ferguson-au Thanks for helping out!
-ut
