### ISSUE TITLE
No subscribers for events posted from background service

### ISSUE THREAD

**Issue by frakc** [greenrobot/EventBus#298]
I post         `EventBus.getDefault().post(new SendPlayer(player));` from a services, which is running in non main thread
```java
<service
        android:name=".player.PlayerService"
        android:process=":player"
        android:enabled="true"
        android:exported="true">
    </service>
```
I expect to recieve even in my fragment
```java
  @Subscribe(threadMode = ThreadMode.MAIN) public void onEvent(SendPlayer event) {
    Log.w("mcheck", "onEvent");
  }
```
However, i get message `D/EventBus: No subscribers registered for event class yarh.com.tryexo.player.SendPlayer`. Events are delivered only if i remove `android:process=":player"`. 
Is it a bug or I misunderstud flow of posting events between bachground thread and main thread?

**Comment by ajgarn** [comment]
The EventBus is not shared between processes, which means that you unfortunately can't send an event from your service running in the ":player" process unless your listener class also is running in that process. However, of course you could still have multiple threads running in the same process, all sharing the same EventBus.

I would like the ability to send events between processes as well, so I might develop that functionality shortly as an extension. I'll let you know.

**Comment by frakc** [comment]
@ajgarn thanks for replay. For now ill mark as closed, as eventbus works properly

**Comment by greenrobot-team** [comment]
Thanks @ajgarn for jumping in! Closing. -ut

**Comment by xDragonZ** [comment]
Any workaround to share eventbus between processes `(android:process=":bg") `?

**Comment by ajgarn** [comment]
Take a look at the code in this repository https://github.com/ajgarn/mpeventbus
I use Intents to send events between processes. My intention was to make it a simple library, so feel free to extend it if you want.

**Comment by greenrobot-team** [comment]
Just referencing [this comment](https://github.com/greenrobot/EventBus/issues/140#issuecomment-232346805) with an alternative implementation as well (uses Inter Process Communication, IPC). Have not tried it either, though. -ut
