### ISSUE TITLE
Could we remove methodClassOld.isAssignableFrom(methodClass) in checkAddWithMethodSignature(), in SubscriberMethodFinder.java?

### ISSUE THREAD

**Issue by tiany** [greenrobot/EventBus#299]
in checkAddWithMethodSignature() from SubscriberMethodFinder.java, we got these code:

``` java
        private boolean checkAddWithMethodSignature(Method method, Class<?> eventType) {
            methodKeyBuilder.setLength(0);
            methodKeyBuilder.append(method.getName());
            methodKeyBuilder.append('>').append(eventType.getName());

            String methodKey = methodKeyBuilder.toString();
            Class<?> methodClass = method.getDeclaringClass();
            Class<?> methodClassOld = subscriberClassByMethodKey.put(methodKey, methodClass);
            if (methodClassOld == null || methodClassOld.isAssignableFrom(methodClass)) {
                // Only add if not already found in a sub class
                return true;
            } else {
                // Revert the put, old class is further down the class hierarchy
                subscriberClassByMethodKey.put(methodKey, methodClassOld);
                return false;
            }
        }
```

After reading the code about finding subscribe methods, we knew that when finding subscribe method from the object which called register, we always start from that object's class, then its superclasss, then super... util to java._, javax._, etc. 
Also, the findState which used to find the subscribe methods, will be cleared everytime we have finished a find work on one class.

So, when we call `Class<?> methodClassOld = subscriberClassByMethodKey.put(methodKey, methodClass);` and the return value is not null, we should be sure that the `methodClass`  is the superclass of `methodClassOld`, `methodClassOld.isAssignableFrom(methodClass)` always return false here. it will be senseless in the || expression, and can be **removed** from the code. Did I miss anything here?  If so, please let me know.

Or writing like this, just want the method to be more generic, for example when we traverse the class from top to bottom, we can also use this method.

It would be very appreciated if you could explain this to me.

Thanks in advance.

**Comment by haiyang1994** [comment]
im looking the answer for this

**Comment by haiyang1994** [comment]
we can not.
When in method -> findUsingReflectionInSingleClass:

try {
        // This is faster than getMethods, especially when subscribers are fat classes like Activities
        methods = findState.clazz.getDeclaredMethods();
    } catch (Throwable th) {
        // Workaround for java.lang.NoClassDefFoundError, see https://github.com/greenrobot/EventBus/issues/149
        methods = findState.clazz.getMethods();
        findState.skipSuperClasses = true;
    }


if it call getMethods,it will include method in base class. so isAssignableFrom will return true

**Comment by greenrobot-team** [comment]
Closing this then (is just a question for code explanation). -ut
