### ISSUE TITLE
Could not dispatch event

### ISSUE THREAD

**Issue by croemmich** [greenrobot/EventBus#30]
I'm likely doing something wrong.. but I have been trying to debug this for almost 10 hours now... about ready to give up.

I have a setup like this:

Activity:
  onCreate:
    - mView = findViewById(R.id.view)
    - register subscriber
    - start event poster

  onEventMainThread
    -mView.setVisibility(View.GONE)

Event Poster:
Events are posted inside a runnable that is executed by a cached thread pool.

I get this exception:
Could not dispatch event: class com.example.MyEvent to subscribing class class com.example.MyActivity
        java.lang.NullPointerException
at mView.setVisibility

Somehow mView is null. It's not, as I can call "mView.setVisibility(View.GONE)" in onCreate. Is this somehow a bug with EventBus?

**Comment by StayInLove** [comment]
I hava this question ,in myProject I use butterknife,how can i fix it
