### ISSUE TITLE
Augment background delivery mode with a custom background thread.

### ISSUE THREAD

**Issue by antoine-dbr** [greenrobot/EventBus#300]
Hi @greenrobot,

First, kudos for this awesome library, we use it across our Android SDK and apps and it really served use well.

Not sure if this has been discussed before but, it would be nice to be able to add APIs to give a bit more control over background threads for certain clients that have a specific threading model. For example, at bus creation:

```java
EventBusBuilder.addBackgroundThread(String backgroundThreadName); // Create an additional background looper.
```

Sample code:
```java
EventBusBuilder.addBackgroundThread("motion_tracking_thread")...;

@Subscribe(threadMode = ThreadMode.BACKGROUND threadName = "motion_tracking_thread")
public void onMessage(MessageEvent event){
    // This call will be executed on "motion_tracking_thread"
}
```

I started a branch in my fork (see https://github.com/antoine-dbr/EventBus/tree/feature-custom_background_threads). Happy to chat more if you are interested into supporting this use-case.

**Comment by rjbrock** [comment]
Hey quick question, what is the purpose of naming the background thread? Is this so that you can decide which thread certain subscribers receive their events on?

I think a better approach might be to provide the builder with an instance of an ExecutorService that you create, what do you think?

**Comment by antoine-dbr** [comment]
@rjbrock 
"what is the purpose of naming the background thread? Is this so that you can decide which thread certain subscribers receive their events on?"
- Correct.

Good point on the ExecutorService, I'll look into that. Should I close the issue?

**Comment by greenrobot-team** [comment]
If using an ExecutorService works for you, guess yes. Closing.
