### ISSUE TITLE
如果在跳转的页面写点击事件会接收不到消息

### ISSUE THREAD

**Issue by zhangzzqq** [greenrobot/EventBus#306]
如果在跳转的页面写点击事件会接收不到消息

not 
//    @Override
//    public void onStop() {
//        EventBus.getDefault().unregister(this);
//        super.onStop();
//    }

like this 
    @Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
    }

**Comment by haonanerjt** [comment]
注销eventbus写在ondestroy方法里面

**Comment by danceWithKeyboard** [comment]
太坑啦，注销方法写在onStop里面，消息监听的位置无法收到回调的消息，但  是  author的 how to get started 里面就写在了 onstop里面

**Comment by danceWithKeyboard** [comment]
onStop中取消了当前的界面的回调监听，切换到其他界面想要通知时 自然就收不到了

**Comment by greenrobot-team** [comment]
Are you talking about the [getting started page example](http://greenrobot.org/eventbus/documentation/how-to-get-started/)?

On Android the new activity is already past `onResume()` if `onStop()` of the current activity gets called (assuming they are within the same process). So there should be no issue unregistering EventBus in `onStop()` already.

Sorry if that is not your issue, Google Translate is not that good. Please try to write in English.
