### ISSUE TITLE
How to unregistered a specific eventtype of EventBus

### ISSUE THREAD

**Issue by BUPT-LXP** [greenrobot/EventBus#310]
I made an Activity as a subscriber for several eventtypes. Now I want to unregister a specific eventtype, but I don't know how. 
I found this Unregister from a specific event, but there is no more

`public synchronized void unregister(Object subscriber, Class<?>... eventTypes)`
in the latest version. Also I found

`private void unubscribeByEventType(Object subscriber, Class<?> eventType)`
, but it is private.

Could someone give me a hand? Thanks a lot! Sorry for my poor English, I'm not a English speaker.

**Comment by greenrobot-team** [comment]
(Un)Registering for specific events was [deprecated with 2.2 and removed in 2.4](http://greenrobot.org/eventbus/changelog/) to simplify the API.

I suppose you can simply add logic to your `@Subscribe` annotated method to ignore the event if some condition is met.
