### ISSUE TITLE
Subscriber not found when using BroadcastReceiver for Intent.ACTION_BOOT_COMPLETED

### ISSUE THREAD

**Issue by tlindener** [greenrobot/EventBus#313]
Hi,

I'm implementing a Background Service which should be able to communicate with a Frontend activity or other Background Services.

The problem I'm facing is, that the Activity can't send anything successfully to the service when the service is started via BroadcastReceiver.

I use this to start the service on boot.

Do you have any ideas to work around or how to solve this?

**Comment by william-ferguson-au** [comment]
1. Make sure you haven't defined your service to execute is a different process to the rest of your app. EventBus does not transmit events across process boundaries.

2. Make sure you service is actually alive at the time that the event is sent. What type of service is it? Could it already have finished, stopped itself or been stopped by something else?

**Comment by zhangsl** [comment]
Does your Background Service run in a separate process?

**Comment by tlindener** [comment]
In general the service is started Sticky and is usually started in the context of the activity. When started in the context of the BroadcastReceiver, this seems to run in a different context...

**Comment by greenrobot-team** [comment]
If you properly register your service when it is created I do not see where this might fail without any code or an example app. The process of any service started by a receiver in your manifest should by default run within the application process. So it should share the EventBus instance.

May it be possible that the service is stopped (by the system for memory reasons) and is then not registered with EventBus once your activity launches?
