### ISSUE TITLE
Operation strategy

### ISSUE THREAD

**Issue by zouzhenglu** [greenrobot/EventBus#314]
I want to know , when it run? I found Subscriber Index is used to  speed up initial subscriber registration,so ,if I don't add the class to the index ,  it will run by reflection at runtime ???
In my opinion, it spend too much to add index than implementation.

**Comment by zouzhenglu** [comment]
I my opinion, if  u  can use the  package name instead of  the class path,that would be nice.

**Comment by greenrobot-team** [comment]
When not using a subscriber index the subscriptions are looked up at runtime, using reflection, yes.

Have a look at the [subscriber index documentation](http://greenrobot.org/eventbus/documentation/subscriber-index/) for more info.
