### ISSUE TITLE
Events blocking discriminator

### ISSUE THREAD

**Issue by Goutte** [greenrobot/EventBus#315]
Hello !

I wanted to make an event aggregator that would post an `OnEverythingReady` event when a collection of minor events such as `OnViewsReady`, `OnConnectionReady`, and say `OnThatOtherAsyncTaskIsDone` were *all* posted.

The `OnEverythingReady` event should only be posted once, when the last of the subscribed minor events is posted. The order of the minor events does not matter.

I made a test case, and then started hacking around, but I'm confused : is there no other way than the `@Subscribe` annotation to listen to an event ?

The test-case is as follows :

``` java

package org.give2peer.karma.test;

import org.give2peer.karma.EventAggregator;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;
import org.junit.Test;

import android.support.test.runner.AndroidJUnit4;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;


//
// /!\
// Configure this test to use, as instrumentation runner, the following class :
// android.support.test.runner.AndroidJUnitRunner
//

// These three events are posted in any order, and we want to react only when they are all posted.
class SubEventA {}
class SubEventB {}
class SubEventC {}

// We want that event to be posted when all three events above were posted, and not before.
class RealEvent {}

// A mock class to listen to events posted by the aggregator -- in practice this would be an Activity
class ListenerOfRealEvents {
    public int thaum = 0;

    public boolean wasTriggered() { return thaum > 0; }

    @Subscribe
    public void makeMagic(RealEvent re) { thaum += 1; }
}

@RunWith(AndroidJUnit4.class)
public class EventAggregatorTest
{
    public EventAggregatorTest() {}

    @Test
    public void eventAggregation() {

        List<Class<?>> subEvents = new ArrayList<Class<?>>();
        subEvents.add(SubEventA.class);
        subEvents.add(SubEventB.class);
        subEvents.add(SubEventC.class);

        EventBus bus = EventBus.getDefault();

        EventAggregator ea = new EventAggregator(bus, subEvents, new RealEvent());
        bus.register(ea);

        ListenerOfRealEvents lore = new ListenerOfRealEvents();
        bus.register(lore);

        assertFalse("Sanity check : the listener of real events should not have already " +
                    "triggered upon instantiation.", lore.wasTriggered());

        // Let's post the first event !
        bus.post(new SubEventA());

        assertFalse("The aggregated event should not have been posted after only one " +
                    "event.", lore.wasTriggered());

        // Let's post the second event, but let's try event C and not B, as order should not matter.
        bus.post(new SubEventC());

        assertFalse("The aggregated event should not have been posted after only two " +
                    "events.", lore.wasTriggered());

        // Okay, let's post the third and last event, and now Realevent should have been fired too.
        bus.post(new SubEventB());

        assertTrue("The aggregated event should have been posted after the third event.",
                   lore.wasTriggered());

        // Cleanup
        bus.unregister(lore);
        bus.unregister(ea);
    }

}

```

There probably is a way to do that with sticky events and as many subscriptions as I have minor events, but this is something I expect to use quite often (in most of my activities, actually), and I've been spoiled by the awesome handling of such events in [Dart](https://www.dartlang.org/).

I got stuck at the very beginning of the implementation (my mistake for assuming there would be a simple way of subscribing dynamically) :

``` java
package org.give2peer.karma;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;

import java.util.List;

/**
 * Posts (but only once !) an event to the event bus when all subscribed events have been posted.
 *
 * Well... this was a failure... It seems it can't be done... :(
 *
 * Other possible names :
 * - MetaEvent ; but this is not an event per se, as it needs to be registered like a subscriber.
 * - this.posted => this.aggregate ?
 */
public class EventAggregator
{
    EventBus       bus;
    List<Class<?>> subscribed;
    Object         posted;

    public EventAggregator(EventBus bus, List<Class<?>> subscribed, Object posted)
    {
        this.bus = bus;
        this.subscribed = subscribed;
        this.posted = posted;

    }

    // AAAAAH
    // Maybe if we use some reflection to procedurally create the methods of this class with
    // an @Subscribe annotation... Can it be even done ?
    // And I don't like Reflection for things that are used in production...

}
```

What do you think ? Is it a bad idea to try and do things like this ?

---

### Another way

I'm looking at the code behind [`@Subscribe`](https://github.com/greenrobot/EventBus/blob/513f466fee9eec849d4c6a900b7fc1bf6bdc8fba/EventBus/src/org/greenrobot/eventbus/Subscribe.java) but I'm a java noob and I don't understand most of it.
I've never seen an annotation definition before and I'm very much confused.

I also thought of making a custom annotation like `@SubscribeAll` (and maybe also `@SubscribeAny` for good measure) which would take multiple event classes as parameters, but... Noob, remember ? I haven't the faintest yet on how to do that, nor how much work it might take... Especially without touching the `EventBus` codebase.

There probably is an obvious and easy way of doing this, but the web has been pretty scarce on that subject, or I'm not looking for the right keywords.

**Comment by william-ferguson-au** [comment]
The use case you have described matches a discriminator s described the Workflow Pattern papers.
See http://www.workflowpatterns.com/patterns/control/new/wcp28.php

It's not as simple as you seem to think if you plan on covering off all inputs. Consider messageA, messageB, messageA, messageC. Is the 2nd messageA discarded or is it used to start a separate listener.

You can subscribe dynamically, in fact you have to, by using `EventBus#register`.
But I suspect what you meant to ask was can a listener explicitly unregister for a certain message. I imagine you were planning on having your listener unregister for messages as they were received until it received the last message. There is no way that I am aware of to do this in EventBus.

But you can do this yourself in your listener. Maintain a Set of expected messages, remove them as they arrive. Fire when last is received and reset you set of expected messages for next iteration (or unsubscribe or whatever works for your use case)..

**Comment by greenrobot-team** [comment]
I just tried using a plain `Object` as the subscriber method parameter and it receives any posted events.

```
@Subscribe
public void handleEvent(Object event) {
    Log.d("Test", "handleEvent: called for " + event.getClass().getSimpleName());
}
```

You could then do `instanceOf` checks against your list of `subscribed` events and once all are received post your `OnEverythingReady`.

**Comment by Goutte** [comment]
Ha !

That's great, @greenrobot-team ! I can work with this.

Thanks for the tip ! I can close this now ;)

---

Also, thanks @william-ferguson-au for the _blocking discriminator_ keyword, that's exactly right !

:tada:
