### ISSUE TITLE
@Subscribe not working

### ISSUE THREAD

**Issue by wingoku** [greenrobot/EventBus#317]
I have the following methods in my MainActivity.java class. However when the events are fired, these methods don't get called instead I get exception from EventBus.

    ```
@Subscribe
    public void onEvent(MainActivityCallbacks s) {
        Log.e("MAIN", "MAIN ACTIVITY CALLBACK");
    }

    @Subscribe
    public void onEventError(NoSubscriberEvent s) {
        Log.e("MAIN", "NoSubscriberEvent "+s.toString());
    }
```

```
D/EventBus: No subscribers registered for event class com.wingoku.models.eventBus.MainActivityCallbacks

D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
```

**Comment by william-ferguson-au** [comment]
It sounds like you haven't added MainActivity as an event listener.

**Comment by wingoku** [comment]
I have registered the MainActivity as well as the Fragment with EventBus.getDefault()

**Comment by william-ferguson-au** [comment]
Show the code, because the symptoms suggest you haven't.

**Comment by wingoku** [comment]
Resolved it. If the issue surfaces again, I'll reopen the issue and post the code here. Thanks for your help @william-ferguson-au 

Best,

**Comment by william-ferguson-au** [comment]
It would be good for you to post the solution here, so that someone else with the same problem can learn from yours.

**Comment by cuiyuming** [comment]
@wingoku Are you using Subscribe from another library, could you check the Subscribe import path?

**Comment by billrancho** [comment]
you must have unregister your activity /fragment from EventBus. Put your unregister code in correct place it should work then.

**Comment by dimpybadra** [comment]
I am facing the same problem.Can you please tell what u did to resolve this?

**Comment by daerimin** [comment]
I was accidentally doing this:

`EventBus.post(event)`

instead of

`EventBus.getDefault().post(event)`   **<-- Correct**
