### ISSUE TITLE
The main module cannot receive event posted from android lib module ???

### ISSUE THREAD

**Issue by weimianlong** [greenrobot/EventBus#322]
In android studio，my code structure refer to “MVP" . so I use EventBus to post event from domain layer to presenter layer.But the logcat print the msg like "No subscribers registered for event class com.sds.smarthome.business.event.SmartHomeStatus" ! 
If I move the code " EventBus.getDefault().post(statusEvent);" to presenter layer,that is OK.
why????....

**Comment by weimianlong** [comment]
EventBus.getDefault() is the same object...I tested for many times...

**Comment by jemshit** [comment]
same issue for version 2.4
