### ISSUE TITLE
Thorws ClassCastException

### ISSUE THREAD

**Issue by momersaleem-sdsol** [greenrobot/EventBus#325]
I have two fragments (Categories and Allstories). When a I first load the categories fragment, it call an api which in return receives list of categories in the following method. 

 @Subscribe
    public void onEvent(List<Category> pCategoriesList) {
    }

Categories list api response is not received yet and I instantly move to AllStories fragment which also calls an api which in return receives list of stories in the following method.

@Subscribe
    public void onEvent(List<Story> pStoriesList) {
    }

**Problem arises here.**
I have unregistered event for first fragment in onPause and instantly moved to second fragment which registers event in onResume and wait for list of stories. We also know api for getting list of categories (on categoires fragment) is also called but when response receives, it posts an event with list of categories which receives in the onEvent method of AllStories fragment. Which in returns throws the following error.

java.lang.ClassCastException: com.example.pojos.Category cannot be cast to com.example.pojos.Story

According to my understanding of event bus this should be called for categories list because I have unregistered on first fragment and it different from stories list. Then why it's being called. I need a solution to this problem. Please help.

**Comment by greenrobot-team** [comment]
You should not use type `List` for your event as EventBus can not distinguish between them. Design a unique custom event class for your categories and one for your stories instead.

For example:
```java
public static class CategoryEvent {
    public final List<Category> categories;

    public CategoryEvent(List<Category> categories) {
        this.categories = categories;
    }
}

public static class StoriesEvent {
    public final List<Story> stories;

    public StoriesEvent(List<Story> stories) {
        this.stories = stories;
    }
}
```

See the [getting started documentation](http://greenrobot.org/eventbus/documentation/how-to-get-started/).

**Comment by kwameopareasiedu** [comment]
Another thing to note here is nested classes don't work well when obfuscated, so its best to avoid that...
