### ISSUE TITLE
get EventBus event on fragment not working

### ISSUE THREAD

**Issue by tux-world** [greenrobot/EventBus#326]
after define event class and post event on Activity onBackPressed() i cant get event on fragment, some my activities opening above this fragment which that is child of MainActivity. i want to get some events that post from other opening activitis, but my code doesnt get this event on Fragment, but i can post event from Activity onBackPressed()

**SignalActivityMarketDetailStateEvents class:**

```
public class SignalActivityMarketDetailStateEvents {
    private boolean activityMarketDetailState;

    public SignalActivityMarketDetailStateEvents(boolean activityMarketDetailState) {
        this.activityMarketDetailState = activityMarketDetailState;
    }

    public boolean isActivityMarketDetailState() {
        return activityMarketDetailState;
    }
}
```

ActivitySecond :

```
@Override
public void onBackPressed() {
    EventBus.getDefault().post(new SignalActivityMarketDetailStateEvents(true)); 
}
```

**Fragment to get event:**

```
@Subscribe(threadMode = ThreadMode.MAIN)
public void onEventMainThread(SignalActivityMarketDetailStateEvents event) {
    Log.e("EventBus ","Received");
}

@Override
public void onStart() {
    EventBus.getDefault().register(this);
    super.onStart();
}

@Override
public void onStop() {
    EventBus.getDefault().unregister(this);
    super.onStop();
}

@Override
public void onResume() {
    EventBus.getDefault().unregister(this);
    super.onResume();
}
```

**in my Fragment this line doesnt work after post event:**

```
Log.e("EventBus ","Received");
```

**Comment by greenrobot-team** [comment]
You probably should not call `unregister` in `onResume` already.

Also to get an event across activity boundaries (I assume the subscribing fragment is inside of the first activity that started `ActivitySecond` for a result) you might have to use [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). Or use [`startActivityForResult()`](https://developer.android.com/guide/components/activities.html#StartingAnActivityForResult).

You probably should have a look at the [Activity lifecycle](https://developer.android.com/guide/components/activities.html#Lifecycle) and [Fragment lifecycle](https://developer.android.com/guide/components/fragments.html#Lifecycle). Or [all in one picture](https://github.com/xxv/android-lifecycle).

-ut
