### ISSUE TITLE
Event not fired inside onActivityResult

### ISSUE THREAD

**Issue by demo-Ashif** [greenrobot/EventBus#331]
I have two activities A & B. in B activities onActivityResult event is not posting - 

```java
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == Constants.REQUEST_CODE_PHOTO && resultCode == RESULT_OK && data != null) {
            setResult(RESULT_OK, data);
            EventBus.getDefault().post(new CameraClick(true));
            finish();
        }
    }
```

so in A activity i get nothing on thread

```java
@Subscribe
    public void onEventMainThread(CameraClick event) {
        Utilities.showToast(this,"On Even Main Thread");
    }
```

**Comment by greenrobot-team** [comment]
Where do you unregister EventBus in activity A? However, there is no guarantee that while activity B is resumed your activity A still exists, it might already have been destroyed (you can test using the Android Developer Options > Don't keep activities).

To pass something between activities you might have to use [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). Or use [`startActivityForResult()`](https://developer.android.com/guide/components/activities.html#StartingAnActivityForResult) to launch activity B from A.

You probably should have a look at the [Activity lifecycle docs](https://developer.android.com/guide/components/activities.html#Lifecycle).

-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by TomGarden** [comment]
Thanks @greenrobot-team Solution way:
1. unregister on destroy
```kotlin
    public override fun onStart() {
        super.onStart()
        if(!EventBus.getDefault().isRegistered(this)) EventBus.getDefault().register(this)
    }

    override fun onDestroy() {
        super.onDestroy()
        EventBus.getDefault().unregister(this)
    }
```

2. on activity restult
```kotlin
view.postDelay({/*do something*/} , 100)
```
