### ISSUE TITLE
Error position in adapter listview

### ISSUE THREAD

**Issue by bkitduy** [greenrobot/EventBus#335]
http://stackoverflow.com/questions/38548591/eventbus-not-working-with-position-in-list-adapter-correctly
That is my problem, please help me

**Comment by greenrobot-team** [comment]
You should not hold onto a specific `ViewHolder`. If your `onEvent` method is called you have no guarantee that this is the view holder of the item position you need.

Instead update your dataset, then notify the adapter: change `item.isMarkedAsFavorite` of the item you want to change, then call `notifyItemChanged`.

-ut
