### ISSUE TITLE
event was handled twice

### ISSUE THREAD

**Issue by lewisgit** [greenrobot/EventBus#336]
When I quit my app, it seemed that my last registered objec "presenter" was still in my memory. And the next time when I lauch my app, a new "presenter" was registered. when dispatch an event, the old "presenter" and the new "presenter" both handled the event. Therefore, the onEvent function was executed twice, which cause my app crashing.

My question is, is there any method i can call to unregister all objects??

**Comment by greenrobot-team** [comment]
No. You have to make sure to call `unregister()` for all your subscribers at appropriate times. Not sure how your code is set up, but you might try unregistering your presenter in your activity or fragment `onPause()` or `onStop()` methods. -ut
