### ISSUE TITLE
Confusion must be standardized method name

### ISSUE THREAD

**Issue by tao0111225** [greenrobot/EventBus#337]
Sorry, English is not good
Eventbus 3 Use annotations can customize the name of the method:
The former is possible, but in the confusion after the name must be standardized
E.g:
```java
  @Subscribe
    public void onEventMainThread(Object url) {
           
    }
```

**Comment by greenrobot-team** [comment]
You can call your method whatever you want as long as you add the `@Subscribe` annotation. See [the documentation](http://greenrobot.org/eventbus/documentation/how-to-get-started/).

I assume you want your method to be called on the main thread, so you would do something like:
```java
    @Subscribe(threadMode = ThreadMode.MAIN)
    public void handleEvent(Object url) {

    }
```
