### ISSUE TITLE
Eventbus and AlertDialog

### ISSUE THREAD

**Issue by amin1985** [greenrobot/EventBus#344]
there is an issue 
in my app a message is send from recyclerview adapter to main thread
in the main thread after receiving the message calls another function  to delete item from recyclerview
everything works fine but if i press back key and resume my app after it calls Delete_image(Event.parameter);

give this error

> E/EventBus: Could not dispatch event: class something.MessageFunction to subscribing class class something.MainActivity
> android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@1e867b71 is not valid; is your activity running?

my activity is showing(not in background) the whole process is still fine and working good and alertdialog is showing but just the "error" i know that i can't run dialog in none ui thread and the error is because of that

i have this code in mainactivity

```
    @Subscribe
   public void onMessageFunction(MessageFunction Event)
    {
        if(Event.myFunction.equals("F_I_Delete"))
        {
            Delete_image(Event.parameter);
          //  Log.d("F_I_Delete",Event.parameter);
            recycler_pos=Event.value;

        }
}
```

```
public void Delete_image(String FileToDelete)
    {

        final String FileToDelete_lo=FileToDelete;
        DialogInterface.OnClickListener dialogClickListener = new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                switch (which) {
                    case DialogInterface.BUTTON_POSITIVE:
                        //Yes button clicked
                        boolean deleted = false;
                        File del_file = new File(FileToDelete_lo);
                        if (FileToDelete_lo.contains("xyz")) {
                            deleted = false;
                        } else {
                            deleted = del_file.delete();
                            }
                        }

                        if (deleted) {
                          adapter_images.Remove_item(recycler_pos);
                        } else {
                            Toast.makeText(MainActivity.this, R.string.CantDeleteFile, Toast.LENGTH_SHORT).show();
                        }
                        break;
                    case DialogInterface.BUTTON_NEGATIVE:
                        //No button clicked
                        break;
                }
            }
        };
        AlertDialog.Builder builder = new AlertDialog.Builder(MainActivity.this);//or Builder(this) same result
        builder.setMessage(R.string.DeleteVideoFromPhone).setPositiveButton(R.string.YES, dialogClickListener)
                .setNegativeButton(R.string.NO, dialogClickListener).show();
    }
```

if i don't show the alertDialog ===no Error
if i call Delete_image from another view ===no Error
if i call Delete_image from onMessageFunction===Error

i have also tried this
```
@Subscribe(threadMode = ThreadMode.MAIN)
   public void onMessageFunction(MessageFunction Event)
```
but no luck    

everything works fine except the error that is showing
anyway can i ignore it?
thank you for your great job

**Comment by greenrobot-team** [comment]
Where do you call `register()` and `unregister()` in your `Activity`, usually you should use `onStart()` and `onStop()`? `is your activity running?` sounds like EventBus is still holding on to a dead activity.

And yes, you should include `@Subscribe(threadMode = ThreadMode.MAIN)` to ensure your code runs on the main thread.

I guess you should take a look at the [Android lifecycle documentation](https://developer.android.com/training/basics/activity-lifecycle/index.html). -ut

**Comment by amin1985** [comment]
i have used oncreate and ondestroy
there was an if statement for unregistering and it was the issue

thank you very much
