### ISSUE TITLE
Proguard rules in document is incorrect

### ISSUE THREAD

**Issue by markzhai** [greenrobot/EventBus#345]
Using the proguard rules from official site: 

```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
```

cannot work. the subscriber method does not get called, I have to add

```
-dontskipnonpubliclibraryclassmembers
```

to make it work

**Comment by greenrobot-team** [comment]
`-dontskipnonpubliclibraryclassmembers` is part of the default Android ProGuard configuration. Have a look at the [Android + ProGuard docs](https://developer.android.com/studio/build/shrink-code.html#shrink-code). -ut

**Comment by markzhai** [comment]
@greenrobot-team No, it's not, you can check the `proguard-android.txt`, the default is
`-dontskipnonpubliclibraryclasses`, but not `-dontskipnonpubliclibraryclassmembers`

**Comment by greenrobot-team** [comment]
Oh, sorry, my mistake. Did you make sure that your [subscriber methods are `public` then](http://greenrobot.org/eventbus/documentation/how-to-get-started/)?

**Comment by markzhai** [comment]
yes, in detail, I am writing
```java
    @Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
    public void onPostFadeFeed(FadeFeedEvent feedEvent) {
        ...
    }
```

And I am using `proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`

If I do not write `-dontskipnonpubliclibraryclassmembers` in my own proguard file, the subscriber will not get called.

**Comment by greenrobot-team** [comment]
ProGuard should not strip any of the required `EventBus` methods/fields, this is odd. Is `EventBus` used only in a library that your project depends on?

Are you using the [subscriber index](http://greenrobot.org/eventbus/documentation/subscriber-index/), if yes correctly?

-ut

**Comment by markzhai** [comment]
@greenrobot-team no, it is using in the application module, and I did not use the subscriber index

**Comment by greenrobot-team** [comment]
Well, as you found a working ProGuard config for your project and so far no one else is seeing this issue, I guess there is nothing we have to do here... -ut
