### ISSUE TITLE
Hope new feature:postDelay(event,delayTimeMilli)

### ISSUE THREAD

**Issue by edwardZj** [greenrobot/EventBus#349]
Hope new feature:postDelay(event,delayTimeMilli)
new method like this:EventBus.getDefault().postDelay(event,delayTimeMilli);
the event can be received after delayTimeMilli millisecond,
and this method can be useful

**Comment by keluokeda** [comment]
so i am,like  handle postDelay

**Comment by greenrobot-team** [comment]
Duplicate of #70. -ut
