### ISSUE TITLE
eventBus 3.0 EventBus: No subscribers registered for event

### ISSUE THREAD

**Issue by jeromekai** [greenrobot/EventBus#353]

**Comment by greenrobot-team** [comment]
Please see the [Getting Started docs](http://greenrobot.org/eventbus/documentation/how-to-get-started/). Make sure you have a subscriber registered for your event with for example `EventBus.getDefault().register(this);`. -ut

**Comment by SpiritOfDarkDragon** [comment]
I have same problem.

```
EventBus.getDefault().hasSubscriberForEvent(SomeEventClass.class); 
```
return true, but when I post event, I see in logcat: 

```
D/EventBus: No subscribers registered for event class *SomeEventClass*
D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
```
but in another activity this event was recieved fine

**Comment by RoboFlax** [comment]
for me the same! (non-adnroid environment)

**Comment by JerryDu0306** [comment]
I have  same problem. then I restart my app, It can work. so why?
