### ISSUE TITLE
How to unsubscribe from single event?

### ISSUE THREAD

**Issue by sneps85** [greenrobot/EventBus#354]
Hello,

how can i unsubscribe from a single event?

I need to subscribe sticky to FetchDataEvent and immediately unsubscribe from the FetchDataEvent so that i will get data updates only on load.

Thank you

**Comment by greenrobot-team** [comment]
You can not. You can only call `EventBus.getDefault().unregister()`. Otherwise adapt your event handling method to only handle the event once or whenever you choose. -ut
