### ISSUE TITLE
GreenRobot: EventBus's isRegistered() method not working as expected

### ISSUE THREAD

**Issue by lalit3686** [greenrobot/EventBus#355]
I am using [EventBus][1] for receiving the events. I want to check if my Activity is already registered or not as I need to register only once through the whole lifetime of the application, but the issue is that wheneven I come to that Activity which is registered EventBus registers it again and due to that multiple events are getting fired.

Below is my code sample!

        public void registerEventBus(){
            if(EventBus.getDefault().isRegistered(this)){
                Log.e(TAG, "already registered event bus for "+TAG);
            }
            else{
                EventBus.getDefault().register(this);
                Log.e(TAG, "registering event bus for "+TAG);
            }
        }

Also, find the screenshot of logs, in which you can see that initially it gives me proper response but once I move to that Activity again it registers the subscriber again!

**NOTE:** Please don't suggest me to unregister as I want it to be registered always!

[![enter image description here][2]][2]

  [1]: http://greenrobot.org/eventbus/
  [2]: http://i.stack.imgur.com/OYv9b.png

**Comment by william-ferguson-au** [comment]
Are you sure that `this` is the same each time?
Try changing your log to 
` Log.e(TAG, "already registered event bus for " + this);`

If your MainActivity is being destroyed and recreated (eg due to rotation) then it will be a different instance each time.

Also, when/where are you registering?
When/where are you unregistering?

**Comment by lalit3686** [comment]
Instance is different everytime as I am destroying the Activity and creating it everytime and registering it but why I am getting mutliple logs though instance is different?

If Activity 1 is destroyed and and I open it again say Activity 2 then why it is sending me the event registered with Activity 1?

**Comment by william-ferguson-au** [comment]
Because if you never unregistered Activity1 then EVentBus still has a reference to it, so will still send it messages.

You should ALWAYS unregister your subscriber at the equivalent exit point.

**Comment by lalit3686** [comment]
ok, got it thanks for the brief explaination!
