### ISSUE TITLE
Need a new feature of getting subscriber list for a particular event

### ISSUE THREAD

**Issue by GaurangShaha** [greenrobot/EventBus#356]
In one of the I am requiring subscribers object in order to call some methods written inside the subscriber. Can you please create a function that can return me list of subscribers for particular event.

**Comment by william-ferguson-au** [comment]
You are going to have to explain your use case much better.

It sounds like what you are after violates the core principle of loose coupling that an EventBus provides.

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
