### ISSUE TITLE
UncaughtException occured only on Tablet

### ISSUE THREAD

**Issue by shashi2459** [greenrobot/EventBus#360]
Crashing app on Tablet(4.4 kitkat) with the following exception.
`E/UncaughtException: java.lang.NoClassDefFoundError: org.greenrobot.eventbus.EventBusBuilder
                                                     at org.greenrobot.eventbus.EventBus.<clinit>(EventBus.java:48)`
It crashes on line:
`EventBus.getDefault().register(this);`

But the same code runs on other devices.

**Comment by greenrobot-team** [comment]
Are you using multidex? It might not work correctly with EventBus, see [the multidex docs](https://developer.android.com/studio/build/multidex.html#limitations).

Also have a look at your [ProGuard rules](http://greenrobot.org/eventbus/documentation/proguard/). -ut

**Comment by greenrobot-team** [comment]
Oh, and you also might want to [check the FAQ](http://greenrobot.org/eventbus/documentation/faq/) about `NoClassDefFoundError`. -ut

**Comment by shashi2459** [comment]
@greenrobot-team, yes, i`m using multidex.

**Comment by greenrobot-team** [comment]
Let me know if the issue persists after disabling multidex. Closing this then. -ut

**Comment by jemshit** [comment]
So no solution for Multidex ??

**Comment by greenrobot-team** [comment]
As I wrote in [my previous comment](https://github.com/greenrobot/EventBus/issues/360#issuecomment-252543758) this is an issue with multidex, not EventBus. Not sure there is anything we can do here. -ut

**Comment by jemshit** [comment]
My problem is IDE can't find class `EventBus.getDefault()`. If this is multidex related, why Otto was working on my previous project (which had multidex too)

**Comment by greenrobot-team** [comment]
If your IDE can not find a method, there is likely a problem with your build setup (check your dependencies). Multidex is only applied when packaging into an APK. There is nothing we can do in EventBus for you. -ut
