### ISSUE TITLE
I want to fire post to butterknife click

### ISSUE THREAD

**Issue by josejaguirre** [greenrobot/EventBus#363]
Im using ButteKnife and i want to fire "EventBus.getDefault().post(new MyObject())" for send data to another Activity but always appear " No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent".

In onCreated method eventbus does it.

Please help !! 

PD: Sorry for my english and thanks !

**Comment by greenrobot-team** [comment]
You might not be able to do what you want. Read the Android docs about [Coordinating activities](https://developer.android.com/guide/components/activities.html#CoordinatingActivities).

You may be able to pass data between activities by using [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut

**Comment by josejaguirre** [comment]
Thanks !! i resolve the problem
