### ISSUE TITLE
Use annotationProcessor instead of apt to generate subscriber index?

### ISSUE THREAD

**Issue by hamberluo** [greenrobot/EventBus#366]

**Comment by greenrobot-team** [comment]
This only works if you use [the experimental Jack compiler](https://developer.android.com/guide/platform/j8-jack.html) with Android (not recommended). [There are some instructions](http://tools.android.com/tech-docs/jackandjill#TOC-Repackaging-support), but as the top of the file notes they are no longer up to date for Android N.
-ut
