### ISSUE TITLE
True way to attach event to activity lifecycle.

### ISSUE THREAD

**Issue by coulCod** [greenrobot/EventBus#367]
This is more support question or proposition to develop new future than issue. If I make api request and use EventBus as callback manager I want to receive result in any case. Firstly I make this as described here http://greenrobot.org/eventbus/documentation/how-to-get-started/
But problem that if method `EventBus.getDefault().post` will be called when activity is in background state - event will be not catched. That could be if user open activity and turn screen off or tap on home button.
I can fix this behavior by using `postSticky` method, but I think that this is not best way to do this. This is not perfect because I must to remove sticky event from EventBus in `onEvent` method. And if I have two or more depended `onEvent` methods from one event - I must calculate count of times methods was performed and then remove event from EventBus. This is manner difficult to use, because I lot of code. I want just send event and receive it in any case.
 My proposition is to and method like `postSticky` with additional params, this is params is count of times this event must be delivered to `onEvent` methods and then removed from memory. This is will be easy to use for developers.

**Comment by greenrobot-team** [comment]
You may be able to make this work [using priorities](http://greenrobot.org/eventbus/documentation/priorities-and-event-cancellation/). The lowest priority subscriber method may then remove the sticky event. Let us know! -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
