### ISSUE TITLE
how does the  field maxMillisInsideHandleMessage in HandlerPoster work?

### ISSUE THREAD

**Issue by microDD** [greenrobot/EventBus#369]
the field maxMillisInsideHandleMessage is set 10 in EventBus:
  `mainThreadPoster = new HandlerPoster(this, Looper.getMainLooper(), 10);`

And in the class HandlerPoster has the folloing code:
`if (timeInMethod >= maxMillisInsideHandleMessage) {`
    `if (!sendMessage(obtainMessage())) {`
   `throw new EventBusException("Could not send handler message");`
  `}`
 `rescheduled = true;`
`return;`
`}`

Why when a method's  time  costed great than maxMillisInsideHandleMessage will send a message?What's the maxMillisInsideHandleMessage mean?

**Comment by greenrobot-team** [comment]
Due to the lack of documentation, I can only guess: I assume this should force you to not do long-running operations in subscriber methods receiving on the main thread.

@greenrobot should know more.
-ut
