### ISSUE TITLE
post() and unregister() are not synchronized (bug)

### ISSUE THREAD

**Issue by artemik** [greenrobot/EventBus#370]
Going from this issue https://github.com/greenrobot/EventBus/issues/318 there is a bug possible.

Suppose **unregister()** is called from the main thread from **onStop()** method, and the subscriber is also on main thread (MAIN thread mode), but **post()** is invoked from a background thread.

Due to that there is **no synchronization and no double checks**, it's possible that:

1. during **post()** from background thread, EventBus makes subscriptions look up, and gets the subscription;
2. **unregister()** is called from main thread, and activity is destroyed. Subscription is deleted from the EventBus internal list, but EventBus already did look up and is going to send the event;
4. event is recevied on the main thread.

So even calling **unregister()** from the main thread, after it's possible to receive an event on the main thread. It doesn't seem to be expected. 

I wan't to be sure if I call **unregister()** from **onStop()**, no event will be received then, so I don't need to make verbose checks like isDestoryed(), etc.

Real life example: background task received network data and posts it to display via post() from its own thread. Activity receives this on main thread but in the destroyed state, due to the case described above.

**Comment by greenrobot-team** [comment]
Have a look at [my comment](https://github.com/greenrobot/EventBus/issues/318#issuecomment-228694316) in #318 and the linked source code. You can also inspect the source yourself by digging into the code starting from you calling `.post()`. -ut

**Comment by greenrobot-team** [comment]
Just a friendly pointer: the [relevant code is here](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBus.java#L468-L481). -ut

**Comment by artemik** [comment]
Thanks! I see, for different threads there IS a check. Can close the issue.
