### ISSUE TITLE
unregister can not cancel Subscribe background task

### ISSUE THREAD

**Issue by keluokeda** [greenrobot/EventBus#371]
i start a long time task in Subscribe  method in activity,like
![image](https://cloud.githubusercontent.com/assets/16809185/19811310/5d2fe1a8-9d63-11e6-84bd-079a5dc49887.png)
but before task over,i finish activity ,unregister in onDestroy,but background task not cancel
![image](https://cloud.githubusercontent.com/assets/16809185/19811360/9a4f5c94-9d63-11e6-9bd3-7b3644485e24.png)
this is logger info
![image](https://cloud.githubusercontent.com/assets/16809185/19811381/b1a82876-9d63-11e6-8fcf-97c126e1a36a.png)
and it take Main2Activity leak
![image](https://cloud.githubusercontent.com/assets/16809185/19811398/cfeb04a2-9d63-11e6-883b-350df84442dc.png)

i want cancel long time background task when i unregister for no leak,how can i do?

**Comment by william-ferguson-au** [comment]
1.  You should NEVER do long running tasks on someone else's Thread. Your example effectively consumes one of the background Threads of the EventBus for 20 seconds. Your handler should create its own Thread and perform the task in it.
2.  The EventBus's responsibility is to deliver events. It is not to manage the app's tasks. It is the app's responsibility to track and terminate long running tasks that are no longer required.

I would suggest that in your handler you create a new Thread in which you execute your long running Task. Add the Task to a LIst managed by your Activty. When your Activity is destroyed, end all the tasks.

**Comment by keluokeda** [comment]
@william-ferguson-au  thanks your suggestion,this is a demo.
in my project ,i can not make sure when i finish activity the background task is done(stick event),i need do some long running task for not block UIThread,now i can not mamager this task.

**Comment by william-ferguson-au** [comment]
I don't understand. 

Do you want your long running task to terminate if and when the Activity terminates? If so follow my advice.

Do you want your long running task to terminate only when it completes? In that case, do nothing and ignore the temporary memory leak, or create a Service in which to execute the long running task (this is the normal approach).

**Comment by keluokeda** [comment]
i am  so sorry,not long running task,

for example,if i post stick event in this activity,i start this activity ,the background task begin work,and now i finish this activity,

long running task just  example,maybe just 10ms,i finsih activity before task done,the activity will leak

**Comment by william-ferguson-au** [comment]
Activity will be released once your task completes.
Temporary leak.

**Comment by greenrobot-team** [comment]
As this is not a problem with EventBus, but rather about understadning threading (on Android), will close. -ut
