### ISSUE TITLE
Otto deprecated is EventBus also ?

### ISSUE THREAD

**Issue by j2emanue** [greenrobot/EventBus#372]
Since Otto https://github.com/square/otto is deprecated now i was wondering if EventBus would be deprecated for the same reasons  ? Square says RxJava is better at handling threads. Could you comment ?

**Comment by Zhuinden** [comment]
@j2emanue that's like asking if regular saws are deprecated if you can also use a programmable chainsaw which can also boil coffee.

**Comment by greenrobot-team** [comment]
Use whatever fits your needs. For a simple app EventBus might be easier and smaller to get started with. As of now EventBus is not officially deprecated. -ut
