### ISSUE TITLE
About when to register and unregister the EventBus?

### ISSUE THREAD

**Issue by DysaniazzZ** [greenrobot/EventBus#373]
Although you recommend registering the `EventBus` in the `onStart` method and unregistering it in the `onStop` method. I don't know the reason. And I have a requirement when the refresh_token is expired, I need to close all the activities and start the login activity. So I write an empty class `CloseAllEvent`, and subscribe it in the `BaseActivity`. Codes like below:

    public class BaseActivity extends AppCompatActivity {

        @Subscribe(threadMode = ThreadMode.MAIN)
        public void onCloseAll(CloseAllEvent event) {
            finish();
        }

        @Override
        protected void onStart() {
            super.onStart();
            EventBus.getDefault().register(this);
        }

        @Override
        protected void onStop() {
            super.onStop();
            EventBus.getDefault().unregister(this);
        }
    }
I make all the activities extend the `BaseActivity` so that they all subscribe the common `CloseAllEvent`, and when I detect the refresh_token is expired, I post the `CloseAllEvent` to finish all activities, but the result is that only the current activity is finished. I think the reason is when I start `ActivityB` from `ActivityA`, the `onStop` method of `ActivityA` is executed, so the `ActivityA` unregister the `EventBus` and can't receive the `CloseAllEvent` any more. So I think the best way is to register in `onCreate` method and unregister in `onDestroy` method in this case. And the final codes are below:

    public class BaseActivity extends AppCompatActivity {

        private static final String TAG = "BaseActivity";

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            EventBus.getDefault().register(this);
        }

        @Subscribe(threadMode = ThreadMode.MAIN)
        public void onCloseAll(CloseAllEvent event) {
            Log.d(TAG, "CloseAllEvent: " + getClass().getSimpleName());
            finish();
        }

        @Override
        protected void onDestroy() {
            super.onDestroy();
            EventBus.getDefault().unregister(this);
        }
    }

 So what's the best time to `register` and `unregister`?

**Comment by CoXier** [comment]
In my opinion,the best time for `Activity` to register is in `onCreate` and unregister is in `onDestroy`

**Comment by greenrobot-team** [comment]
You can try to use [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). But in your case I would rather properly use an Intent to [clear your task stack and start the login activity](https://developer.android.com/guide/components/tasks-and-back-stack.html#ManagingTasks). -ut
