### ISSUE TITLE
Sticky Event Delivery

### ISSUE THREAD

**Issue by ylfzq** [greenrobot/EventBus#374]
I've checked all of the official documents, but found no conclusion. 

The scenario is:

I had a subscriber method defined:
```java
@Subscribe(sticky = false)  // yes, keep false here
public void onEvent(SomeEvent someEvent) {
    // do something
}
```

I posted a sticky event of `SomeEvent` before the registeration of above class:
```java
EventBus.getDefault().postSticky(new SomeEvent());
```

Will I receive the sticky event after registeration of the class?  If yes, what's the difference between `@Subscribe(sticky = false) ` and @Subscribe(sticky = true)?

**Comment by greenrobot-team** [comment]
According to [the documentation of `.postSticky()`](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBus.java#L283-L287) you will only receive sticky events that were posted before registering your subscriber, if the method is annotated with `@Subscribe(sticky = true)`. So no.

`sticky = false` is the default.

See the docs about [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). -ut

**Comment by ylfzq** [comment]
Thank you for your answer, I think the key sentence in the doc is: 
> During registration all sticky subscriber methods will immediately get the previously posted sticky event.

It's clear but not enough. There are many other scenarios, let's talk in detail:
1. I am registering a sticky/non-sticky subscriber method;
2. But there is a sticky/non-sticky event posted before registration, will I receive the previously posted event?
3. I want to post a sticky/non-sticky event after registration, what will happen?
The scenario that I described in issue is: (1) I am registering a non-sticky subscriber method, (2) But there is a sticky event posted before registration, I WILL NOT get the event as you and the doc said. What's more here, (3) I want to post a sticky/non-sticky event after registration, what will happen?
The combination result is 8 and we have 8 scenarios to discuss. Maybe not every scenario is meaningful, but I think it's worth to think about this.

**Comment by greenrobot-team** [comment]
If you read the EventBus docs and method documentation I pointed out you should be able to deduce the other options, no? You might also just test your scenario, which is always the better option.

The core concept of EventBus is: every registered subscriber will receive every event of the type it registered for. With sticky events and methods you can expand that for certain events/methods so that they receive an existing sticky event right when registering. -ut
