### ISSUE TITLE
Remove a listener from the list of subscriptions

### ISSUE THREAD

**Issue by hearbeathorror** [greenrobot/EventBus#375]
Hi,

Is there a way to remove a certain subscriber from the list of subscriptions available? Since that method and also the variable (list) is private, there is no way for me to do so. I would like to remove a certain subscriber that would have been registered twice by mistake.

Please assist

Thanks

**Comment by greenrobot-team** [comment]
The only API available is `EventBus.register()` and `.unregister()` which will register/unregister all the subscriber methods in a class. See [the docs](http://greenrobot.org/eventbus/documentation/how-to-get-started/). -ut
