### ISSUE TITLE
Add tag for the same posting to seperate?

### ISSUE THREAD

**Issue by jp1017** [greenrobot/EventBus#377]

**Comment by jp1017** [comment]
Just like this: 

https://github.com/hehonghui/AndroidEventBus

**Comment by greenrobot-team** [comment]
I am not sure what exactly you are looking for. Do you have an example?

In any case, have a look at [the thread mode documentation](http://greenrobot.org/eventbus/documentation/delivery-threads-threadmode/). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
