### ISSUE TITLE
A and B and C total three activities

### ISSUE THREAD

**Issue by naguchennai** [greenrobot/EventBus#378]
A Activity

    @Subscribe(threadMode = ThreadMode.MAIN)
     public void doThis(Pvt_Eventbus intentServiceResult) {
        **//snackbar with start new C activity button. A activty not finish. just onclick call C activity**
     }

    @Override
    protected void onPause() {
        super.onPause();
        gooffline();
        EventBus.getDefault().unregister(this);
    }
    @Override
    protected void onResume() {
        super.onResume();
        EventBus.getDefault().register(this);
    }

B Acticity

     EventBus.getDefault().post(new Pvt_Eventbus(Activity.RESULT_OK, "done!!"));

I have three activity .. when fire from B , A activity will show snack bar with button. if i click button C activity will start. but A activity not finished . its working fine

But, When i close C Activity A activity snack bar fire stopped?????????

i also try with sticky its not work why?
i fired Using B avtivity in Separate emulator*

i used Firebase Realtime Database

A activity = Groupchat_activity
C activity  = Privatechat_activity
B Activty = Privatechat_activity ( From separate Emulator)

**Comment by greenrobot-team** [comment]
Not sure what exactly you are trying to do, but have a look at [how activities are coordinated](https://developer.android.com/guide/components/activities.html#CoordinatingActivities). This should clear things up. -ut
