### ISSUE TITLE
EventBusIndex when using annotationProcessor

### ISSUE THREAD

**Issue by andrewlord1990** [greenrobot/EventBus#380]
The Android Gradle plugin 2.2 has introduced an annotationProcessor, meaning apt doesn't need to be used anymore.

How would you go about configuring the EventBusIndex with this annotationProcessor? As the documentation currently relies on using apt and using the apt { arguments { } } closure, to specify the event bus index.

**Comment by iismagilov** [comment]
Hi @andrewlord1990!

I used this to make it works.
```
defaultConfig {
...
   javaCompileOptions {
    annotationProcessorOptions {
      arguments = [eventBusIndex: "com.example.EventBusIndex"]
    }
  }
...
}
```

**Comment by andrewlord1990** [comment]
Excellent, thanks very much!

**Comment by greenrobot-team** [comment]
[Updated the docs](http://greenrobot.org/eventbus/documentation/subscriber-index/). -ut
