### ISSUE TITLE
warning: The following options were not recognized by any processor: '[eventBusIndex]'

### ISSUE THREAD

**Issue by draskosaric** [greenrobot/EventBus#382]
I have following code in `build.gradle`:

    defaultConfig {
        applicationId "com.code.xyz"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 6
        versionName '1.0.6'
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true 
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ eventBusIndex : 'com.code.xyz.TestEventBusIndex' ]
            }
        }
    }
    ...
    dependencies {
       //...
        compile 'org.greenrobot:eventbus:3.0.0'
        annotationProcessor 'org.greenrobot:eventbus-annotation-processor:3.0.1'
    }

FAQ states, I quote: 

> This happens when you set up the build script, and you did not add any annotations to your code yet. Without any @Subscribe annotations, annotation processor for indexing will not be triggered to consume the ‘eventBusIndex’ option. So, just add some @Subscribe annotations and you should be fine.

This is what I did:

- I put @Subscribe annotations for all `onEventMainThread(...)` methods in my project (I migrated from EventBus 2 to 3), but keep getting this message after every project rebuild. 

- Annotation processing is enabled

- I am using Android Studio 2.2.2

- Gradle plugin's version is 2.14.1

**Note:** I am using different flavors and, just to make sure, I copied that code from `defaultConfig` to my flavor's config, but I still get the message: warning: _**The following options were not recognized by any processor: '[eventBusIndex]'**_

 
What am I doing wrong?

Thanks!

**Comment by aviadmini** [comment]
Do you have any method looking like this: 

 ```
    @Subscribe
    public void onStubEvent(@NonNull final StubEvent pEvent) {
        // whatever
    }
```

Any annotation parameters and any class instead of StubEvent should work as far as I know

**Comment by greenrobot-team** [comment]
From my experience, you can safely ignore that warning. This is because EventBus has no official support for the new `annotationProcessor` API. It should work anyhow.

Let me know if that is not the case. Also, if somebody has insights on how to avoid this warning (it appears the Android Gradle plugin does not realize the EventBus processor is running) that would be helpful.
-ut

**Comment by draskosaric** [comment]
@aviadmini No, I don't have any method like that.

**Comment by snkashis** [comment]
Yeah, I'm seeing this warning too. But the index file appears to be generated properly.

**Comment by draskosaric** [comment]
@snkashis, where can I find or should expect to find index file, since the line below:

`EventBus.builder().addIndex(new com.code.xyz.TestEventBusIndex()).installDefaultEventBus();`

produces error: 

> Error:(94, 64) error: cannot find symbol class TestEventBusIndex

**Comment by greenrobot-team** [comment]
The file should get generated when you make/build the project into a subfolder of `build\generated\source\apt\<flavor>\debug\...`. -ut

**Comment by draskosaric** [comment]
It doesn't get generated.

**Comment by snkashis** [comment]
@draskosaric yeah, as @greenrobot said, my generated files ends up in build/generated/source/apt/debug/my/app/name and build/generated/source/apt/release

**Comment by draskosaric** [comment]
@greenrobot-team, @snkashis, how can I get generated that class?

**Comment by greenrobot-team** [comment]
I do no longer see this warning. Closing then. -ut
