### ISSUE TITLE
Why EventBus cannot pass data to a newly created activity? 

### ISSUE THREAD

**Issue by jamin918** [greenrobot/EventBus#385]
ActitvityA: EventBus.getDefault().post(data),  then startActivity to ActivityB, 
ActivityB:  onStart(): EventBus.getDefault().register(ActivityB.this); 
                   onStop(): EventBus.getDefault().unregister(ActivityB.this);  activityB cannot receive the data.
why not provide such functionality?

**Comment by william-ferguson-au** [comment]
I think you are looking for a sticky event.
In which case EventBus does have that functionality.

**Comment by jamin918** [comment]
The problem was solved, tks.  [http://greenrobot.org/eventbus/documentation/configuration/sticky-events/](url)
