### ISSUE TITLE
Subscriber class com.sample.package.service.BackgroundSyncService and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by spurdow** [greenrobot/EventBus#388]
`Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.sample.package.service.BackgroundSyncService and its super classes have no public methods with the @Subscribe annotation`
Im currently using 3.0
When i was using 2.4 It was ok, but now its so frustrating.
I dont understand, the 3.0 version, Im currently using a base-service i created, registerd it `onCreate` and unregisterd it `onDestroy`. 

What should I do to make my base classes work so that I wont register it over and over again?

**Comment by AllanWang** [comment]
You are free to register and unregister in a superclass and not have to rewrite it for other subclasses, but the subclasses must have at least one subscription for it to work. I don't think @Subscribe annotations are inherited so that may be the issue.

**Comment by spurdow** [comment]
@AllanWang thanks for the info, I'll soon try what u said, but as of now I'm currently using 2.4. Anyway I  don't see any link for change log?

**Comment by AllanWang** [comment]
@spurdow Check [this](http://greenrobot.org/eventbus/changelog/) for the changelog
