### ISSUE TITLE
Can't receive Event message when invoke Button click action

### ISSUE THREAD

**Issue by maojunjun** [greenrobot/EventBus#389]
when I posting a message in  method block of button click action from another Activity ,the Subscriber can't receive it !! Just a demo for using Eventbus 3.0

follow is MessageEvent sender Activity:
`public class EventSenderActivity extends AppCompatActivity {

    @BindView(R.id.btn_post_msg)
    Button btnPostMsg;
    private  String Tag = EventSenderActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_eventsender);
        ButterKnife.bind(this);

        EventBus.getDefault().post(new MessageEvent("First Message from EventBus"));

        EventBus.getDefault().post(new MessageEvent("Second Message from EventBus"));

        btnPostMsg.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Log.e(Tag,"isInMainThread : "+ (Looper.myLooper() == Looper.getMainLooper()));
                EventBus.getDefault().post(new MessageEvent("Third Message from EventBus"));
                Toast.makeText(EventSenderActivity.this, "发送Event消息成功", Toast.LENGTH_SHORT).show();
            }
        });
    }
}`

Subscribe Activity:
`public class SubscriberActivity extends AppCompatActivity {

    @BindView(R.id.tv_content)
    TextView tvContent;
    @BindView(R.id.start_next)
    Button startNext;

    private String Tag = SubscriberActivity.class.getSimpleName() ;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_subscriber);
        ButterKnife.bind(this);

        startNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(SubscriberActivity.this,EventSenderActivity.class));
            }
        });

    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onMessagePosted(MessageEvent event) {

        Toast.makeText(this, event.msg, Toast.LENGTH_SHORT).show();
        Log.e(Tag,"===================EventMessage received!!!!===============================");
        tvContent.setText(event.msg);
    }

    @Override
    protected void onStart() {
        super.onStart();
        EventBus.getDefault().register(SubscriberActivity.this);
    }

    @Override
    protected void onStop() {
        EventBus.getDefault().unregister(SubscriberActivity.this);
        super.onStop();
    }
}`

MessageEvent:
`public class MessageEvent {

    public final String msg;

    public MessageEvent(String msg) {
        this.msg = msg;
    }
}`

SubscriberActivity can receive First and Second Message but Third which posted in Button Click Action method block, why?

**Comment by william-ferguson-au** [comment]
This is never going to work.

You need to understand the Android Activity lifecycle better.
See https://developer.android.com/guide/components/activities/activity-lifecycle.html

Only one of your Activities will be active at any time. The reason you are receiving the first 2 messages is because the #onCreate method of your EventSenderActivity has fired before the #onStop of your EventSubscriber.

When your EventSender is fully instantiated (as it will need to be before you can press the postMsg button, your EventSubscriberActoovty will have bee long stopped, probably destroyed and possibly garbage collected.

**Comment by maojunjun** [comment]
really thank you!
