### ISSUE TITLE
How do I send an event to the specified subscriber ?

### ISSUE THREAD

**Issue by CoderBCat** [greenrobot/EventBus#390]
How do I send an event to the specified subscriber?
I don't want to define too many event classes.

**Comment by william-ferguson-au** [comment]
You don't send an event to a specified subscriber.
You post an event and the subscribers that have been configured for that event will receive it.

**Comment by greenrobot-team** [comment]
Also see the graphic in [the documentation](http://greenrobot.org/eventbus/). -ut

**Comment by CoderBCat** [comment]
All network requests are returned to the JSON data format, different business to do different distribution, I have to define a lot of similar event class.
