### ISSUE TITLE
Background thread vs Async thread pool

### ISSUE THREAD

**Issue by adil-hussain-84** [greenrobot/EventBus#391]
(This is not an issue with the library but a question...)

I see from the documentation that with thread mode `BACKGROUND` a single background thread is used and with thread mode `ASYNC` a thread pool is used.

_Is the background thread used by the `BACKGROUND` thread mode separate and distinct from the threads used by the `ASYNC` thread mode?_

I ask because I want to use `BACKGROUND` thread mode for quick events (like local file access) and I want to use `ASYNC` thread mode for slow(er) events (like network calls)... and naturally I'd like it if `BACKGROUND` events were never waiting on `ASYNC` events to complete.

**Comment by greenrobot-team** [comment]
Each has its own queue ([`AsyncPoster`](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/AsyncPoster.java), [`BackgroundPoster`](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/BackgroundPoster.java)) and both use the same cached thread pool [`ExecutorService`](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBusBuilder.java#L30). So yes, they should not block each other.

However, if you always use `ASYNC` those will also not block each other as each will use its own thread (the docs even warn about [too many concurrent threads](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/ThreadMode.java#L53)).

Also note that `BACKGROUND` may use the main thread if the event was posted from it.
-ut

**Comment by adil-hussain-84** [comment]
Thank you for the response @greenrobot-team. That makes sense.

I think you meant `POSTING` in your last comment above rather than `BACKGROUND`, i.e. in `POSTING` mode the main thread is using if the event was posted from the main thread. From the [docs](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/ThreadMode.java), a non-main thread is always used in `BACKGROUND` mode. Is my understanding correct?

**Comment by greenrobot-team** [comment]
Yes, sorry, the docs are right. -ut
