### ISSUE TITLE
Subscriber Index documentation needs a small change

### ISSUE THREAD

**Issue by adil-hussain-84** [greenrobot/EventBus#392]
The Subscriber Index documentation [here](http://greenrobot.org/eventbus/documentation/subscriber-index) says to add this block to the `build.gradle` file:

    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ eventBusIndex : 'com.example.myapp.MyEventBusIndex' ]
            }
        }
    }

For correctness this should be:

    android {
        defaultConfig {
            javaCompileOptions {
                annotationProcessorOptions {
                    arguments = [ eventBusIndex : 'com.example.myapp.MyEventBusIndex' ]
                }
            }
        }
    }

**Comment by greenrobot-team** [comment]
Good point, thanks. Updated the documentation. -ut
