### ISSUE TITLE
Can't unit test classes that use EventBus

### ISSUE THREAD

**Issue by gsteigert** [greenrobot/EventBus#398]
I want to write some unit tests for classes that have their own EventBus instances, but it won't work because EventBus uses Android's Handler in its constructor. Using Otto I'm able to do it, but I want to use EventBus instead. Any ideas?

```
java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.os.Looper.getMainLooper(Looper.java)
	at org.greenrobot.eventbus.EventBus.<init>(EventBus.java:111)
	at org.greenrobot.eventbus.EventBus.<init>(EventBus.java:104)
	(...)

Process finished with exit code 255
```

**Comment by okamayana** [comment]
Have you considered looking into using Robolectric?

**Comment by greenrobot-team** [comment]
You are probably trying to use [a local unit test](https://developer.android.com/training/testing/unit-testing/local-unit-tests.html). But as you found out, EventBus depends on some Android features. So you have to [use an instrumented unit test](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html) that runs on an Android device instead.
-ut

**Comment by gsteigert** [comment]
Ok, thanks!

**Comment by jmholtan** [comment]
My team and I ran into this exact problem while integrating GreenRobot Eventbus. We wanted to verify that the eventbus was posting a specific event but not the execution of the posted event.

You can achieve this via reflection and mockito mocks. 

Java:
```java
Field field = EventBus.class.getDeclaredField("defaultInstance");
if (!field.isAccessible()) field.setAccessible(true);
field.set(null, Mockito.mock(EventBus.class));
```

Kotlin:
```kotlin
val field = EventBus::class.java.getDeclaredField("defaultInstance")
if (!field.isAccessible) field.isAccessible = true
field.set(null, mock<EventBus>())
```

**Comment by postace** [comment]
thank @jmholtan  for your answer

**Comment by greenrobot-team** [comment]
Note that as of version `3.1.1` EventBus also works for plain-Java projects, so also for Android local unit tests. Though note that some thread modes may behave differently. -ut
