### ISSUE TITLE
subscribe event set priority useless ?

### ISSUE THREAD

**Issue by TheSnowFish** [greenrobot/EventBus#399]
in MainActivity  post 

EventBus.getDefault().postSticky(1);
EventBus.getDefault().postSticky("1");

in other Activity Subscribe 

    @Subscribe(priority = 100,threadMode = ThreadMode.MAIN,sticky = true)
    public void onTest1(String satring){
        Log.e(TAG, "onTest1: "+satring );
    }
   @Subscribe(priority =500,threadMode = ThreadMode.MAIN,sticky = true)
    public void onTest2(Integer a){
        Log.e(TAG, "onTest2: "+a );
    }
But the log shows ：
 TAG : onTest1: 1
 TAG : onTest2: 1

Why priority big to receive late ?

**Comment by TheSnowFish** [comment]
@greenrobot  @PerfectCarl  @friederbluemle @stefanhoth @talklittle 
 Who can tell me about it? God will care for you，thanks

**Comment by greenrobot-team** [comment]
First of all, you should define an event class that you post. See [how to get started](http://greenrobot.org/eventbus/documentation/how-to-get-started/).

Second, check the [documentation for how priorities work](http://greenrobot.org/eventbus/documentation/priorities-and-event-cancellation/).
