### ISSUE TITLE
SubscriberInfoIndex does not support sub-modules

### ISSUE THREAD

**Issue by balizhuang2012** [greenrobot/EventBus#401]
I' have done an experiment, the result is that,  generated SubscriberInfoIndex does not include Subscriber in sub-modules.
Do u have any ideas?

**Comment by greenrobot-team** [comment]
You probably have to [add the EventBus annotation processor](http://greenrobot.org/eventbus/documentation/subscriber-index/#How_to_generate_the_index) to each submodule, then just [add the index class for each one](http://greenrobot.org/eventbus/documentation/subscriber-index/#Indexing_your_Libraries) in your main project. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
