### ISSUE TITLE
onEventMainThread() shoud be public on mi note 3

### ISSUE THREAD

**Issue by Rishi19** [greenrobot/EventBus#403]
Shows onEventMainThread() should be public on MI Mobile device and some Motorola Devices

**Comment by Rishi19** [comment]
Check you methods is't private? Just change it be public.

**Comment by greenrobot-team** [comment]
I am not sure what you are referring to? You declare `onEvent` methods yourself. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
