### ISSUE TITLE
Sticky events get posted only once

### ISSUE THREAD

**Issue by aliakhgar** [greenrobot/EventBus#405]
Hi, I use greenrobot as eventbus to post some sticky events.Well every thing works fine and when I open application the ex content is showed which shows sticky post works fine. But when I close app and open it for second,third,... time there is no ex content showed which means sticky event hasn't been posted.Sticky event get posted only once! why? can anyone help me?
I use the code below in onPostExecute of asyncTask.
`EventBus.getDefault().postSticky(new SliderBusModel(SlideID,SlideImage,SlideType,SlideTitle));`

**Comment by greenrobot-team** [comment]
Did you add `sticky = true` to your `@Subscribe` annotation? Are you sure the `.postSticky` method is called again? Also: sticky events are not preserved when your app is killed.

In any case, have a look at [how sticky events work](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut

**Comment by loveRose** [comment]
I also met the scene, my solution is removed before sending time, but don't know what “sticky = true ”can achieve this effect

**Comment by greenrobot-team** [comment]
No response. Closing.

@loveRose See the [documentation about sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
 -ut
