### ISSUE TITLE
[Question] Order delivery of events 

### ISSUE THREAD

**Issue by melicamp** [greenrobot/EventBus#412]
Hi, I've got a question regarding event bus. Does event bus guarantee delivery order of events? Let's say that I post event1 from thread1  and then post event2 from thread2, can I be certain that event1 will be delivered first, if I listen for both of the events on thread3?

**Comment by greenrobot-team** [comment]
Only if the events are posted from the same thread and are received on the same thread. You can follow [the call stack here](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBus.java#L238). When posting from different threads order is (obviously) not guaranteed, you have to ensure yourself who gets to post first. Also see the [Delivery Threads](http://greenrobot.org/eventbus/documentation/delivery-threads-threadmode/) documentation.
-ut

**Comment by melicamp** [comment]
Thanks a lot for quick and detailed answer. :)
