### ISSUE TITLE
App crashes on lower Android api devices in Unity Plugin

### ISSUE THREAD

**Issue by samrajsingh** [greenrobot/EventBus#413]
I am using the Unity version of  Tune 
But the app crashes on Android Api (4.4.2) while it works properly on Upper Android apis.

```
android.java.exception java.lang.NoClassDefFoundError:de.greenrobot.event.EventBus 
com.tune.ma.eventbus.TuneEventBus.<clinit>(TuneEventBus.Java:18)
com.tune.Tune.init(Tune.java:175).
```

An clue about this??

**Comment by greenrobot-team** [comment]
Have a [look at the FAQ](http://greenrobot.org/eventbus/documentation/faq/) about this. -ut

**Comment by samrajsingh** [comment]
Hi

 I am using the Unity Version.

Does that FAQ applies to Unity version as well.

If it applies, then how to modify the jars file as it comes with the Unity Package?

According to the FAQ's  to fix scenarios.

1) I have not  overwritten  a life cycle method with PersistableBundle just by accident since I am directly                      using the jars file.

2) How to use EventBus 3 with the Unity Version?

Solution 3 and 4 also not possible coz I am again using the packaged product?

Any help would be greatly appreciated.

**Comment by greenrobot-team** [comment]
Oh, @samrajsingh are you sure that the EventBus your are referring to is `org.greenrobot.eventbus.EventBus`? I am not aware that we have an official version packaged for Unity. -ut

**Comment by samrajsingh** [comment]
@greenrobot-team I am using the Tune Sdk which uses GreenRobot , the link for the Tune sdk is 
[https://developers.tune.com/sdk/unity-quick-start/ ](url) .  And you can check the jar file at this location [https://github.com/TuneOSS/unity-plugin/blob/master/sample/Assets/Plugins/Android/eventbus-2.4.0.jar](url). eventbus-2.4.0.jar uses Green Robot. But now  I think you guys have nothing to do with the Tune SDK right?? Do let me know your thoughts.

**Comment by greenrobot-team** [comment]
Yes, we have nothing to do with the Tune SDK. As the error originates in `com.tune.ma.eventbus.TuneEventBus.<clinit>(TuneEventBus.Java:18)` I would go ask those developers about any dependency issues. -ut
