### ISSUE TITLE
App crashes when using WebChromeClient.FileChooserParams with EventBus on Pre-Lollipop devices

### ISSUE THREAD

**Issue by lalit3686** [greenrobot/EventBus#414]
App keeps crashing while registering EventBus on Pre-Lollipop devices while using **WebChromeClient.FileChooserParams**

Below is the stack-trace

Stacktrace: android / webkit / WebChromeClient$FileChooserParams
```
java.lang.Class.getDeclaredMethods(Native Method)
java.lang.Class.getPublicMethodsRecursive(Class.java: 955)
java.lang.Class.getMethods(Class.java: 938)
org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java: 157)
org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java: 88)
org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java: 64)
org.greenrobot.eventbus.EventBus.register(EventBus.java: 136)
com.semaphore.common.CommonActivity.onResume(CommonActivity.java: 138)
com.semaphore.login.WebViewerActivity.onResume(WebViewerActivity.java: 629)
android.app.Instrumentation.callActivityOnResume(Instrumentation.java: 1184)
android.app.Activity.performResume(Activity.java: 5082)
android.app.ActivityThread.performResumeActivity(ActivityThread.java: 2565)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java: 2603)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java: 2089)
android.app.ActivityThread.access$600(ActivityThread.java: 130)
android.app.ActivityThread$H.handleMessage(ActivityThread.java: 1195)
android.os.Handler.dispatchMessage(Handler.java: 99)
android.os.Looper.loop(Looper.java: 137)
android.app.ActivityThread.main(ActivityThread.java: 4745)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java: 511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 786)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 553)
dalvik.system.NativeStart.main(Native Method)::Cause: java.lang.ClassNotFoundException: android.webkit.WebChromeClient$FileChooserParams
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java: 61)
java.lang.ClassLoader.loadClass(ClassLoader.java: 501)
java.lang.ClassLoader.loadClass(ClassLoader.java: 461)
java.lang.Class.getDeclaredMethods(Native Method)
java.lang.Class.getPublicMethodsRecursive(Class.java: 955)

```
If anyone faced similar previously can provide a solution

**Comment by greenrobot-team** [comment]
There is your issue: `dalvik.system.NativeStart.main(Native Method)::Cause: java.lang.ClassNotFoundException: android.webkit.WebChromeClient$FileChooserParams`

[Looking at the docs, WebChromeClient.FileChooserParams](https://developer.android.com/reference/android/webkit/WebChromeClient.FileChooserParams.html) was added in API level 21. It is not available on "pre-Lollipop" devices.
-ut

**Comment by lalit3686** [comment]
Yes, but still is there anyway that it should not crash on pre-lollipop devices?

**Comment by william-ferguson-au** [comment]
@lalit3686 *your* app is referencing `android.webkit.WebChromeClient$FileChooseParams`. You need to remove this reference from your app if you expect it to run on pre-lollipop devices.

This has *nothing* to do with EventBus.

**Comment by lalit3686** [comment]
This has to do with EventBus for sure, because I tried removing EventBus and then there was no problem at all!

**Comment by william-ferguson-au** [comment]
@lalit3686 that just means that the code that is loading `WebChromeClient$FileChoosrParams` isn't being invoked when you removed EventBus. So you are no longer exercising all of your app.

EventBus has **zero** dependencies on `WebChromeClient`. 
Buty don't take my word for it. Look yourself.

**Comment by lalit3686** [comment]
@william-ferguson-au  as you can see in the crash report the crash is being generated by register method of EventBus. So, if I just remove that part of registering EventBus then it works fine, how?

**Comment by william-ferguson-au** [comment]
@lalit3686 EventBus uses reflection to find the Subscriber annotations on whatever you are registering. As part of loading that class (or one of its dependencies) the classloader attempts to load `WebChromeClient$FileChooserParams`.

**Comment by lalit3686** [comment]
Is there anyway I can handle this scenario of classes available for higher version can be ignored by EventBus while registering & performing reflection?

**Comment by greenrobot-team** [comment]
Thanks @william-ferguson-au for the explanations!

@lalit3686 what @william-ferguson-au said. Also you might want to look at how to [make your Android app compatible with versions of Android](https://developer.android.com/guide/practices/compatibility.html).

Closing this then. -ut
