### ISSUE TITLE
Subscribe specific object inside List

### ISSUE THREAD

**Issue by caiquebertan** [greenrobot/EventBus#416]
Hi there!

Is there a way to post an event with the object List, but having more than one kind of list?

Like, if I post an event with the List<Car> and then post another one with the List<Boat> both of my methods are going to receive both of the events.

So the method "public void onEvent(List<Car>)" will get the List<Boat> as parameter and vice versa.

That can be achieve somehow? Because if can't, I know that I will need to controle the type of the list when it gets on the subscribed method..

Thanks in advance!

**Comment by greenrobot-team** [comment]
It is probably best if you define multiple events like:
```java
public static class ListEventA {
    public List<TypeA> list;
    [...]
}

public static class ListEventB {
    public List<TypeB> list;
    [...]
}
```
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
