### ISSUE TITLE
could add a option that not regiest repeat?

### ISSUE THREAD

**Issue by tanghongbin** [greenrobot/EventBus#417]
many fragment work with same data structure and same reuqest's module,i would receive once request's result for each fragment ,but i receipt many repeat data....it's terrible!!!!

**Comment by greenrobot-team** [comment]
Check where and how often you post events. Beyond that, [have a look at the docs](http://greenrobot.org/eventbus/documentation/) to get a better understanding how to use EventBus.

If you do not have a specific code example project, I can not reproduce any possible EventBus issues. -ut
