### ISSUE TITLE
Could not dispatch event

### ISSUE THREAD

**Issue by whiteboy** [greenrobot/EventBus#418]
I've received that log:
E/EventBus: Could not dispatch event: class xxx to subscribing class class yyy
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

```
class yyy
@Subscribe(threadMode = ThreadMode.MAIN)
    public void onMainThread(xxx event) {
        tvTitle.setText(event.value)
    }
```

So I wonder that the problem is I do not check null for TextView before setText or evenbus problem?

**Comment by Davids89** [comment]
Are you sure you're setting a value in the event?

**Comment by whiteboy** [comment]
Yes, the value is set. I think when main thread call, the textview is not init view yet, that's why it's null

**Comment by Davids89** [comment]
Is totally necessary for you use the main thread? I mean, I don't use sticky events and I have no problems like that

**Comment by whiteboy** [comment]
I think I have some problem to do with my code. Thank you so much.

**Comment by greenrobot-team** [comment]
Yes, the error log indicates that `tvTitle` is `null`. Closing then as this is not an EventBus issue. -ut
