### ISSUE TITLE
upgrade to 3.0.0.

### ISSUE THREAD

**Issue by imyyq-star** [greenrobot/EventBus#419]
Hello, my project uses version 2.4.0, and I want to improve performance, so upgrade to 3.0.0.
However, I refer to a library using 2.4.0, (I can not let the development of this library guy also upgraded to 3.0.0). So I have to add in my build.gradle:
Compile 'de.greenrobot: eventbus: 2.4.0'
Compile 'org.greenrobot: eventbus: 3.0.0'

My question is: does this do not reduce performance? Should i be upgraded to 3.0.0?

thx！forgive my English is not good

**Comment by greenrobot-team** [comment]
Looking at [the release notes for v3.0.0](http://greenrobot.org/eventbus/changelog/) it is fine to run both EventBus 3 and EventBus 2 side-by-side:

> This is a breaking change release: there is no inter-op between EventBus versions 2 and 3; they can run in parallel though.

There should be no issues with performance.
-ut

**Comment by imyyq-star** [comment]
Thank you, my boss eventually chose not to upgrade, even though I did a full investigation and preparation, but he still worried that the upgrade will bring unpredictable new mistakes.
