### ISSUE TITLE
golang API using gomobile bind

### ISSUE THREAD

**Issue by joeblew99** [greenrobot/EventBus#420]
From golang you can call Java.
https://www.reddit.com/r/golang/comments/5fno6i/gomobile_now_comes_with_reverse_bindings_for_java/

here is an example:
https://github.com/golang/mobile/tree/master/example/reverse
you run the command and it inspects the java and creates a binding to be called from golang.

**Comment by greenrobot-team** [comment]
I had a quick look, is experimental. So what are you expecting from EventBus here? -ut

**Comment by joeblew99** [comment]
Its does work and well.
Google just dont want to make it look liek they support it.
But when you hit a problem they fix it in a day.

What woudl really help is a github repo with good basic examples.
This would allow me to quickly try out interfacing with it from gomobile.
then i can write a golang example that matches it using gomobile.

How does that sound ?

**Comment by greenrobot-team** [comment]
@joeblew99 I still do not get what you expect us to do here? This has nothing to do with EventBus. Feel free to fork this repository and experiment with gomobile. -ut

**Comment by joeblew99** [comment]
am just asking if you know of a github repo that uses eventbus. like a sample.
then i can copy the logic in the sample with golang.

Makes sense ?

**Comment by greenrobot-team** [comment]
Nothing from the top of my head. But you can [try looking for open source software in this list](http://www.appbrain.com/stats/libraries/details/eventbus/greenrobot-eventbus).

Closing as this is not an EventBus issue. -ut
