### ISSUE TITLE
EventbusException

### ISSUE THREAD

**Issue by viviandbritto** [greenrobot/EventBus#421]
Hello,

I am using greenbot eventbus library 3.0.0 i am getting following error.

org.greenrobot.eventbus.EventBusException: Subscriber class com.xtempo.q2t.request_portal.RequestPortalFragment and its super classes have no public methods with the @Subscribe annotation

Thanks,
Vivian

**Comment by greenrobot-team** [comment]
You need to add event handling methods annotated with `@Subscribe` to one of your classes. See step 2 of [the getting started guide](http://greenrobot.org/eventbus/documentation/how-to-get-started/). -ut

**Comment by viviandbritto** [comment]
Thank a lot
