### ISSUE TITLE
Event is triggered multiple times

### ISSUE THREAD

**Issue by Hemant0408** [greenrobot/EventBus#422]
Hello,

I am using greenbot for network calls issue i am facing is, same event is triggered multiple times.
I have registered and unregisered an event in onStart() and onStop() method.

Thanks,
Hemant

**Comment by greenrobot-team** [comment]
Check when and where the event is posted (add a log statement). Or are you possibly using [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/)? -ut
