### ISSUE TITLE
Differentiate multiple @Subcribe methods with same argument signature in a class

### ISSUE THREAD

**Issue by wingoku** [greenrobot/EventBus#424]
I'm using Greenbot EventBus in my app. I have an onEvent() in 2 fragments, Fragment A & B. The signature of the @Subscriber method is

    public void onEvent(String myString) {}

in both fragments.

Fragment B is ADDED on top of the Fragment A so both fragments are alive at the same time. The issue is when a Utility class posts an event like this `EventBus.getDefault().post("hello world")`, the `onEvent(String myString)` *in both fragments is called*. This is cumbersome & least elegent way IMO.

I can create Multiple model classes that contain the String value to cope with this problem but it's not practical for example if I have 100 methods with same argument types, I'll have to create 100 classes whose only purpose will be to contain a String value to deliver to method matching the signature.

How can I create qualifiers to differentiate the 2 `onEvent(String myString)` methods just like Dagger2 uses **qualifers/@Named()** to differetiation?

**Comment by MatFl** [comment]
Have you considered to unregister the fragment in it's onPause and register in in onResume? That way only the active fragment would receive events.

**Comment by greenrobot-team** [comment]
What @MatFl said, try to unregister if you do not want to receive events. Otherwise creating an event class for each different event is how EventBus works. If this does not suit you, you have to look for another solution. -ut
