### ISSUE TITLE
Is there a design patter or suggestion about centralization of management for consuming event

### ISSUE THREAD

**Issue by stoneLee81** [greenrobot/EventBus#427]
When I was using this tool in android, i found a problem, when event is more, it's mess and hard to manage those message, wanna to consult a question about centralization of management for consuming event in android?
Thanks a lot

**Comment by william-ferguson-au** [comment]
You will have to explain yourself more clearly.

Centralisation of event management (beyond the event bus itself) is the antithesis of event streams.
