### ISSUE TITLE
 Problems with upgrading gradle to 2.4.0-alpha7

### ISSUE THREAD

**Issue by VipMinF** [greenrobot/EventBus#433]
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
  - eventbus-annotation-processor-3.0.1.jar
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

**Comment by greenrobot-team** [comment]
I am not sure how this is different from [the current recommended setup](http://greenrobot.org/eventbus/documentation/subscriber-index/#How_to_generate_the_index) if you want to use the subscriber index (which requires using the EventBus annotation processor)? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
