### ISSUE TITLE
how to restore eventbus when activity suddenness destroy?

### ISSUE THREAD

**Issue by liangjingkanji** [greenrobot/EventBus#434]

**Comment by greenrobot-team** [comment]
If you are using `EventBus.getDefault()` it is a singleton and is not destroyed when your activity is destroyed.

But I think you are asking about registering to EventBus, please see [How to get started](http://greenrobot.org/eventbus/documentation/how-to-get-started/) about that. In short: register/unregister during the activities lifecycle methods.
-ut

**Comment by liangjingkanji** [comment]
You got me wrong.What I mean is the memory shortage caused the application destroyed. example: onRestoreInstanceState

**Comment by greenrobot-team** [comment]
@liangjingkanji You should always get a call to `onStart()` in that case. (So register EventBus there and unregister in `onStop()`). Here is [a nice diagram of the activity lifecycle](https://github.com/xxv/android-lifecycle#complete-android-fragment--activity-lifecycle). -ut

**Comment by liangjingkanji** [comment]
![image](https://cloud.githubusercontent.com/assets/21078112/26052740/0b3e6040-3999-11e7-9a80-14ec26c35d54.png)

i am crash,  My English is not good.

**Comment by liangjingkanji** [comment]
sorry

**Comment by greenrobot-team** [comment]
@liangjingkanji Oh, you are talking about [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). Yes, they are only stored **in memory**. If you want to [persist data across app restarts you have to use another method](https://developer.android.com/guide/topics/data/data-storage.html). -ut
