### ISSUE TITLE
EventBus not work

### ISSUE THREAD

**Issue by moter** [greenrobot/EventBus#435]
After my application executed onTrimMemory (), app was started again, and eventbus did not execute @Subscribe

@subscribe works in service, and service has not been destroyed

**Comment by greenrobot-team** [comment]
Check that you correctly [register and unregister EventBus](http://greenrobot.org/eventbus/documentation/how-to-get-started/) in your [activity/fragment lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle.html) methods. -ut

**Comment by moter** [comment]
Thank you。
I've solved it. This problem exists below the Android 4.4.2 version. Register eventbus in service, and when memory is reclaimed, service is still running. When I opened the app again, I decided that service was running and would not restart it. My solution is to restart service in Application onCreate (), and then register eventbus again in service
