### ISSUE TITLE
How to run test

### ISSUE THREAD

**Issue by Songsayit** [greenrobot/EventBus#439]
I try to run EventBusTest, then I got failed log following:
$ adb shell am instrument -w -r   -e debug false -e class org.greenrobot.eventbus.EventBusBasicTest de.greenrobot.event.test/android.test.InstrumentationTestRunner
Client not ready yet..
Started running tests
Test running failed: Unable to find instrumentation info for: ComponentInfo{de.greenrobot.event.test/android.test.InstrumentationTestRunner}
Empty test suite.

What did I missed?

**Comment by greenrobot-team** [comment]
Thanks, this was a broken configuration. Have a look at the [the code and instructions to fix this](https://github.com/greenrobot/EventBus/pull/440) I suggested. -ut

**Comment by Songsayit** [comment]
It works. Thank you very much for your reply to deal with my fool issue.
