### ISSUE TITLE
@Tag annotations

### ISSUE THREAD

**Issue by KobeBryant824** [greenrobot/EventBus#444]
If there are multiple same events
Is it possible to add @Tag annotations for distinguishing?

**Comment by greenrobot-team** [comment]
Not sure what you mean exactly, do you have an example? However, I suspect it makes sense to just define a different event class. -ut

**Comment by KobeBryant824** [comment]
Create only one object, but you can define a tag to notify the recipient

@Subscriber
Private void update User (User user) {.
/ /not receive.
}

@Subscriber (tag = "my _ tag").
Private void update User With Mode (User user) {.
/ /dosomething.
}

**Comment by greenrobot-team** [comment]
I do not see a need for this. Just create two different event classes (both can have `User` as a field). -ut

**Comment by KobeBryant824** [comment]
Okay, I admit I'm lazy, I do not want to define too many classes, there https://github.com/hehonghui/AndroidEventBus
