### ISSUE TITLE
EventBus.post() does not call subscribers immediatelly

### ISSUE THREAD

**Issue by Villason** [greenrobot/EventBus#445]
(I edit the issue completely as I identified the original problem)

When you post a new message inside a subscriber, the call to subsequent subscribers are delayed until the first call is finished. Is there a way to make the bus call the subscribers in each post call?

**Comment by greenrobot-team** [comment]
No, this is not possible and would break the bus principle of events being delivered in the order they were posted. I suppose you already had a look at how the [`EventBus.post` method](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBus.java#L238-L258) works using a queue. -ut
