### ISSUE TITLE
All Sticky event trigger in Activity

### ISSUE THREAD

**Issue by onlymnsh** [greenrobot/EventBus#446]
I have 3 activity A,B,C.
    In Activity B i have register 2 Sticky Events
    
     @Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
        public void getReqIDandNumber(MessageEventDTO eventDTO) {
    }
    
    @Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
        public void getSelectedExpenseList(List<ExpenseDTO> expenseList) {
    }
    
    When come from activity A to B i post MessageEvent and when come from activity C i post List of Object.    Whenever Activity B open both sticky event trigger always.
    How to trigger only one method at a time.

**Comment by greenrobot-team** [comment]
You might want to remove the sticky event after you have handled it. See [Getting and Removing sticky Events manually in the Sticky Events documentation](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). -ut

**Comment by onlymnsh** [comment]
Thank your for your help . Its working now .
