### ISSUE TITLE
Subscriber methods are invoked even after the object is unregistered

### ISSUE THREAD

**Issue by karthiks** [greenrobot/EventBus#447]
**The Context**
I've an Android app built using MVP design. The Presenter unregisters itself from the EventBus, onDestroy of its associated activity.

I've a MediaPlayer service that posts events, some of whose consumers are in one Presenter (say PresenterA of ActivityA) and the others in another Presenter (PresenterB of ActivityB).

Now when I move from one ActivityA to ActivityB (via MainActivity that has options to navigate to any of these two activities), I see that the subscribed methods of supposedly lost Presenter gets invoked inspite of it being unregistered successfully.

I tested this unregisteration state by doing it twice, to get the below warning in my log:
`W/EventBus: Subscriber to unregister was not registered before: ...`

**The Issue (as I see it)**
Now because the EventBus holds stale reference to this Presenter, this method gets invoked and throws NPE like below:
```
E/EventBus: Could not dispatch event: class com.demo.MediaPlayerPreparedEvent to subscribing class class com.demo.presenters.PresenterA
java.lang.NullPointerException: Attempt to invoke interface method ...
```

I'd appreciate your advice on this.

**Comment by greenrobot-team** [comment]
I assume you are calling `resgister(this)` in `onCreate()` and `unregister(this)` in `onDestroy()`.

Are you aware that the new activity will go up to `onResume()` while the old activity remains in `onPause()`? Only after that the old activity will be stopped and destroyed. See [Coordinating activities](https://developer.android.com/guide/components/activities/activity-lifecycle.html#soafa) in the Android Activity Lifecycle documentation.

However, the error message sounds like something in your subscriber method can be `null` before `unregister()` in `onDestroy()` is called.

-ut

**Comment by karthiks** [comment]
Your assumption is right on when I (un)register Eventbus.

"However, the error message sounds like something in your subscriber method can be null before unregister() in onDestroy() is called." has more likelyhood in my case. The MediaPlayer service updates its media play progress (say in the interval of every 500 milli-seconds) by way of EventBus event that the Presenter subscribes to.

I typically set the view to null in my presenter's onDestroy() after Eventbus.unregister(..). The question is after the unregister(..) of Eventbus is called the possibility of NPE shouldn't exist.

I see the unregister method definition like below:
```
List<Class<?>> subscribedTypes = typesBySubscriber.get(subscriber);
        if (subscribedTypes != null) {
            for (Class<?> eventType : subscribedTypes) {
                unsubscribeByEventType(subscriber, eventType);
            }
            typesBySubscriber.remove(subscriber);
        }
        ...
```
Would executing `typesBySubscriber.remove(subscriber);` before the for loop help resolve this issue?

And FYI, I resolved this issue by wrapping the view in presenter with WeakReference<>. Even as this issue is resolved this way, I'm just wondering that this issue could be resolved at EventBus.

Let me know your thoughts.

**Comment by greenrobot-team** [comment]
Your suggested change should not make a difference. When posting only `subscriptionsByEventType` is used to determine the subscribers that should receive the event.

Great to hear the issue is resolved.
-ut
