### ISSUE TITLE
Post to only 2 of the 3 subscribers listening for the same event

### ISSUE THREAD

**Issue by KLC27** [greenrobot/EventBus#448]
Note: This is more of a suggestion if does not already exists

It would come quite handy if it is possible to have the ability to limit/restrict/allow which of the registered subscribers of the same event that the event is delivered to at the time of posting an event.

**Comment by william-ferguson-au** [comment]
This should be handled by the listeners buy either subscribing to different sets of event or filtering an event based upon some information. There is no need (and lots of reasons not to) complicate the delivery mechanism.

**Comment by KLC27** [comment]
@william-ferguson-au Thanks for the prompt reply. 

What is being suggested is trying to avoid adding fields in the event to determine the logic, because if a particular event has a lot of subscribers (over 10), then all subscriber methods will need to add logic to determine if it should handle the event posted, it would be much either to pass an array of classes that define the scope of the event being posted.

Please could you follow up on this issue(suggestion) if in the near future, a feature is implemented that meets the above mentioned requirements. 

Much appreciated!

**Comment by william-ferguson-au** [comment]
In that case you should be posting different events.
There is absolutely no good reason to add this functionality to the infrastructure of an EventBus.

**Comment by greenrobot-team** [comment]
Kind of agree with @william-ferguson-au on keeping EventBus as simple as possible. Adding a simple check (super class method, static helper method, or a method inside the event class?) or using different events should is the way to go. -ut

**Comment by KLC27** [comment]
@william-ferguson-au @greenrobot-team Thanks for the response, much appreciated.
