### ISSUE TITLE
[Android Studio 3.0 alpha7]OnClick doesn't get response

### ISSUE THREAD

**Issue by 1130381752** [greenrobot/EventBus#449]
My Android Studio has been updated to 3.0 alpha7, when I use eventbus 3.0.0 on a OnClick Event, I find it can't work well(but it doesn't crash), the received Activity can't make any response! 
But if I post message once the Activity onCreated, it can receive and make any response.
I think maybe the message hasn't been sent out !!!

**Comment by jp1017** [comment]
Code or demo please. 

we must keep in mind: Code has nothing to do with tools(android studio or eclipse).

**Comment by 1130381752** [comment]
I don't think so, maybe the gradle version don't match the code, because when I use Android Studio 2.3.3, it can be fine.

**Comment by greenrobot-team** [comment]
As @jp1017 said, we can not help without an example project so we can reproduce the issue. -ut

**Comment by 1130381752** [comment]
I made a project with AS 3.0.0 alpha7(and gradle version is 3.0.0-alpha7) ,you can run it to find the issue.
[https://github.com/1130381752/MyApplication.git](url)

**Comment by william-ferguson-au** [comment]
You need to read up and understand the Android Activity lifecycle.
MainActivity will already have stopped (and unregistered it's EventListener) by the time Activity1 posts its event.

**Comment by 1130381752** [comment]
But if I post the Event once the MainActivity1 onCreate, MainActivity can make response(Toast) right now.

**Comment by greenrobot-team** [comment]
Are you aware that the new activity will go up to `onResume()` while the old activity remains in `onPause()`? Only after that the old activity will be stopped and destroyed. See [Coordinating activities](https://developer.android.com/guide/components/activities/activity-lifecycle.html#soafa) in the Android Activity Lifecycle documentation.

To pass data across activities you should [save the data](https://developer.android.com/training/basics/data-storage/index.html) or you might try [using sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut
