### ISSUE TITLE
一个注册的回调会被调用两次···

### ISSUE THREAD

**Issue by liaohuyu** [greenrobot/EventBus#450]
如题，求解···谢谢。

**Comment by GHYOWEE** [comment]
===用中文他又看不懂 哈哈

**Comment by jp1017** [comment]
哈哈哈,sticky事件吗,destroy里要添加removeStickyEvent.... @liaohuyu

**Comment by CoXier** [comment]
**Maybe this group don't speak or use Chinese.So you should translate your question in English.**

**Comment by greenrobot-team** [comment]
If I understand correctly: make sure that you unregister your subscribers properly. When used within Activity or Fragment use the equivalent lifecycle method (register in onCreate -> unregister in onDestroy, register in onStart -> unregister in onStop, ...). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
