### ISSUE TITLE
Does subscriber index support KAPT?

### ISSUE THREAD

**Issue by Zhuinden** [greenrobot/EventBus#452]

**Comment by greenrobot-team** [comment]
Yes. Make sure to update to the latest version of Kotlin (I believe at least 1.1.3) as it includes fixes for kapt.

I added a section about using kapt to the [Subscriber Index documentation](http://greenrobot.org/eventbus/documentation/subscriber-index/#Using_kapt).
-ut

**Comment by Zhuinden** [comment]
Thank you!
