### ISSUE TITLE
can't receive event

### ISSUE THREAD

**Issue by PineappleM** [greenrobot/EventBus#453]
don't receive event on activity by send in class of Application

**Comment by greenrobot-team** [comment]
Make sure that the activity is subscribed at the time the event is posted. See [How to get started](http://greenrobot.org/eventbus/documentation/how-to-get-started/).

If the event is posted before, you may be able to solve this [using sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut

**Comment by PineappleM** [comment]
i thhink that i do Follow the requirements
the following code:
1,in application:
UmengNotificationClickHandler notificationClickHandler = new UmengNotificationClickHandler() {
            @Override
            public void dealWithCustomAction(Context context, UMessage msg) {
                Toast.makeText(context, msg.custom, Toast.LENGTH_SHORT).show();
                LogUtils.d("自定义通知打开动作:UmengNotificationClickHandler:dealWithCustomAction:m" + msg.custom);

                //打开应用操作
//                try {
//                    Intent intent = context.getPackageManager().getLaunchIntentForPackage("com.tydic.compstaff");
//                    startActivity(intent);
//                    LogUtils.d("应用启动");
//                } catch (Exception e) {
//                    Toast.makeText(context, "没有安装", Toast.LENGTH_SHORT).show();
//                }

                //启动应用
                launchApp(getApplicationContext(),msg);


                //发送打开通知页事件，接受通知的消息是在homeactivity2中，所以相当于已经完成了登录有了token（但是serviceId应该还没更新），时机是对的
                LogUtils.d("eventbus发送:" + LOAD_NOTIFICATION_PAGE+":"+EventBus.getDefault().hashCode());
//                EventBus.getDefault().postSticky(new OperateEvent(LOAD_NOTIFICATION_PAGE));
                EventBus.getDefault().postSticky(new OperateEvent(UPDATE_NOTIFICATION).setNotificationNum(3));

            }

        };
2,in activity:
@Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
    public void onEvent(final BaseEvent event) {
        LogUtils.d("Eventbus接收:onEvent");
        if (event instanceof OperateEvent) {
            final OperateEvent operateEvent = (OperateEvent) event;
            switch (((OperateEvent) event).getEvent()) {
                case LOAD_NOTIFICATION_PAGE:
                    LogUtils.d("Eventbus接收:LOAD_NOTIFICATION_PAGE");
                    goMeg();
                    break;
......
}
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home2);
        ButterKnife.bind(this);

        initPtr();
        initView();

        if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
            LogUtils.d(this.getClass().getSimpleName() + ":onCreate:register");
        }
    }
@Override
    protected void onDestroy() {
        super.onDestroy();

        if (EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().unregister(this);
            LogUtils.d(this.getClass().getSimpleName() + ":onDestroy:unregister");
        }

        XLoadingDialog.with(getContext()).dismiss();
        timer.cancel();

    }

GreenRobot Team,Please help me to solve,thanks.

**Comment by PineappleM** [comment]
in the application, that is Umeng push sdk.

the problem can appear when the app is closed then auto reboot the app by receive the push message

**Comment by greenrobot-team** [comment]
You can not listen for the base class of your events `BaseClass`. You have to specify the exact class you post: `OperateEvent`.

Your onEvent method signature should look like this:
```
@Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
public void onEvent(final OperateEvent event) {
...
```
-ut

**Comment by greenrobot-team** [comment]
Are you sure that the `dealWithCustomAction()` is executed inside the same process as your app? It is possible that `EventBus.getDefault()´ is not returning the same instance. -ut

**Comment by PineappleM** [comment]
this method maybe is the callback by UmengPush service process. if ti is ,should i do to solve? sigh!!!

**Comment by PineappleM** [comment]
i see the object's hashCode is the same

**Comment by PineappleM** [comment]
the problem can appear when the app is closed then auto reboot the app by receive the push message,
if the app is in running ,it's ok, no problem.
why ? please

**Comment by greenrobot-team** [comment]
There is a possibility that the app process is terminated after receiving the push message and before the app is started. 

You should probably pass the data you require through the launch intent as extras. -ut

**Comment by PineappleM** [comment]
This is feasible scheme.
If the activity of Subscribed class is not active by my judged,i set launch intent args,then postStick in the SplashActivity(Frist activity of launch App).
thank you GreenRobot Team.

**Comment by PineappleM** [comment]
my english is not good. ha ha

**Comment by PineappleM** [comment]
oh,you say that can not listen for the base class of my events BaseClass, is it?

**Comment by moter** [comment]
你Receive用的是BaseEvent,可是Post的时候用的是子类。你这样节约了代码貌似不行。Receive换成子类试试

**Comment by PineappleM** [comment]
这个我用子类接收的时候，已经试过了，一样不行的。前面GreenRobot Team也说过了，用父类接收默认是可以的，你看上面的回复，问题出在发送和接收不在同一个应用进程的问题。

**Comment by evansherry** [comment]
默认EventBus.getDefault()这个会返回自己和基类的回调，友盟应该是开启了一个新的进程，比如推送之类都这样做的，这时候你在新的进程里post一个message，在你的app进程里是接收不到的，不过他给出的方案应该可行，用aidl应该也可以，我也没什么好的想法！

**Comment by greenrobot-team** [comment]
Closing this then. -ut
