### ISSUE TITLE
About the instruction, I have a suggestion

### ISSUE THREAD

**Issue by 1130381752** [greenrobot/EventBus#454]
Several days ago, I post a issue called "[Android Studio 3.0 alpha7]OnClick doesn't get response", the develop team told me that when enter the another activity from the previous one, the previous activity will be stopped, it donesn't make response because I put unregister function on the old activity's onStop function.
So when I put the register function on the old activity's onCreate function and the unregister function on onDestory function, it can work normally.But the README.md told me put the register function on onStart function and the unregister function on onStop function, just like the picture, I think can you change it to "@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        EventBus.getDefault().register(this);
    }
@Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
    }"

![a](https://user-images.githubusercontent.com/26515937/28600373-2528456a-71e4-11e7-9382-1455cc5e1fb4.png)

**Comment by greenrobot-team** [comment]
No. You should NOT use EventBus to pass data between activities. The only exception is if you [use sticky events](http://greenrobot.org/eventbus/documentation/sticky-events).

Please read up on [the Android activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle.html). -ut
