### ISSUE TITLE
Subscribing to Integer type

### ISSUE THREAD

**Issue by dapengyinyue** [greenrobot/EventBus#459]
If subscribe just action, I think to create entity is not a better idea, can launch Integer type such as :
```
int SHARE_SUCCESS = 0x101;
EventBus.getDefault().post(SHARE_SUCCESS);
```

**Comment by greenrobot-team** [comment]
Yes, you can post and subscribe to **any** object, so it can also be `Integer` or `String`. However, typically it is better to have specific event classes to differentiate between events.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
