### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/greenrobot/eventbus/EventBus

### ISSUE THREAD

**Issue by yhongm** [greenrobot/EventBus#460]
Why didn't anyone answer?

**Comment by yhongm** [comment]
why

**Comment by yhongm** [comment]
IDE is Eclipse

**Comment by yhongm** [comment]
os is android 5.1

**Comment by yhongm** [comment]
Eventbus version is 3.00

**Comment by GangemiLorenzo** [comment]
Same error

**Comment by greenrobot-team** [comment]
Please [check the FAQ](http://greenrobot.org/eventbus/documentation/faq/).

If you want us to help you have to share some more details:
- what are you trying to do (code example, demo project, ...)?
- what is going wrong (error message, stacktrace, ...)?
- when does it go wrong (specific device, API level, ...)?
-ut

**Comment by greenrobot-team** [comment]
Additonal note: if you are using multidex, make sure to [set it up properly](https://developer.android.com/studio/build/multidex.html#mdex-gradle) so it works correctly on older devices.

No response. Closing. -ut
