### ISSUE TITLE
error in call ReentrantLock signal(老哥报错了)

### ISSUE THREAD

**Issue by Imcodingcc** [greenrobot/EventBus#461]
When I use the ReentrantLock instance method newCondition() to get the condition object, I call the corresponding object's signal () method, which is called in the @Subscribe declaration method, and the following error (I'm still waiting on the other side , The signal () method is the wake-up waiting thread).

I think the event is waiting in the queue to dispatch, once the opportunity(Thread is idle) to perform the dispatch, it immediately perform, but now it seems not like this

The calling and declare process is like this

```
   @Subscribe
    fun onUUID(msg: BtspReceiver.UUIDMessage) {
        val device = msg.value
        state.uuidTask.device = device
        state.uuidTask.cond.signal()
        Log.d("BTSP", "signal")
    }

   //in MainActivity


            BluetoothDevice.ACTION_UUID -> {
                val device = p1.getParcelableExtra<Parcelable>(BluetoothDevice.EXTRA_DEVICE) as BluetoothDevice
                eventBus.post(UUIDMessage(device))
            } 
    //in BroadCastReceiver



  val lock = ReentrantLock()
    val cond = lock.newCondition()
    var device: BluetoothDevice? = null

    override fun onPreExecute() {
        super.onPreExecute()
        state.withServiceDevices = BtspReceiver.Devices()
    }

    override fun doInBackground(vararg devices: Unit): BluetoothDevice? {
         val deviceSet = state.devices.toMutableSet()
         deviceSet.forEach({d -> if ( d.fetchUuidsWithSdp() ) {
                 Log.d("BTSP", String.format("asking UUIDS for (%s %s)", d.address, d.name))
             }
         })
         while(deviceSet.isNotEmpty()){
             lock.lock()
             try {
                 // wait for MainActivity::onUUID
                 cond.await(10, TimeUnit.SECONDS)
   
    //Mainly the last line， in android Asynctask
```

error msg:
"Could not dispatch event: class cn.leither.btsp.BtspReceiver$UUIDMessage to subscribing class class cn.leither.btsp.MainActivity"

**Comment by greenrobot-team** [comment]
The error message means that somewhere in your `onUUID` method an exception was thrown. The log output should display what exception it was right after the `Could not dispatch event` message. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
