### ISSUE TITLE
Change SnackBar BackgroundColor

### ISSUE THREAD

**Issue by ricardofressa** [greenrobot/EventBus#462]
The activity receives the event from a Fragment, the activity needs to create a snackbar and change the background of the snackbar.
But in doing so the error in the log happens like this:

> 08-28 16:15:58.233 13491-13491 E/EventBus: Could not dispatch event: class SearchPickingListEvent to subscribing class class HomeActivity
> android.content.res.Resources$NotFoundException: Resource ID #0xffffce00
> 

The method that receives the Fragment event is like this:

```
@Subscribe(threadMode = ThreadMode.MAIN)
    public void onSearchListEvent( SearchListEvent searchListEvent) {
        if (searchListEvent.isSuccess()) {

            loadingEventsUI(getString(R.string.findingPickingList), Snackbar.LENGTH_INDEFINITE,
                    ContextCompat.getColor(this, R.color.snackbar_background_warning));

                    controller.fetchInvoice(searchListEvent.getCdCode(),
                    searchListEvent.getPickingListNumber());
        } else {
            showMessage(R.string.orderinvalid);
        }
    }
```

```
private void loadingEventsUI(String message, int duration, int color){
        mSmoothProgressBar.progressiveStart();
        mSmoothProgressBar.setVisibility(View.VISIBLE);
        mSnackbar = Snackbar.make(btnMainMenu, message, duration);
        mSnackbar.getView().setBackgroundColor(ContextCompat.getColor(this, color));
        mSnackbar.show();
    }
```

Erro line
`mSnackbar.getView().setBackgroundColor(ContextCompat.getColor(this, color));`

**Comment by CysionLiu** [comment]
color:R.color.snackbar_background_warning  can not be found, so ContextCompat.getColor(this, color) will throw an exception.then exception "Could not dispatch event: class SearchPickingListEvent to subscribing class class HomeActivity" will occur

**Comment by greenrobot-team** [comment]
This is EventBus logging that your `onSearchListEvent` method has thrown an exception when it was called due to an event being posted. You should fix the cause of the exception, which is "android.content.res.Resources$NotFoundException: Resource ID #0xffffce00". Look at the rest of the stack trace to find the issue. Likely `R.color.snackbar_background_warning` does not exist. -ut
