### ISSUE TITLE
Not working properly with ArrayList

### ISSUE THREAD

**Issue by ravirupareliya** [greenrobot/EventBus#465]
I have 2 fragment class with EventBus receiver and from activity i am sending data using EventBus.

    ArrayList<ModelA> modelAlist = new ArrayList<>();
    EventBus.getDefault().post(modelAlist);

And in FragmentA and FragmentB i have onEvent method, both for different ArrayList types

FragmentA

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onEvent(ArrayList<ModelA> list) {
        Log.d("onEvent", "() called with: list = [" + list + "]");
    }

FragmentB

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onEvent(ArrayList<ModelB> list) {
        Log.d("onEvent", "() called with: list = [" + list + "]");
    }

but it is calling onEvent of both the fragment.

**Comment by CysionLiu** [comment]
ArrayList<ModelB> or ArrayList<ModelA> is a generic type. Essentially they are both the ArrayList.class in JVM. Here i suggest to wrap the list by a obj whose type can be differred.

**Comment by greenrobot-team** [comment]
What @CysionLiu said. So something like:
```java
class ModelAEvent {
    List<ModelA> models;
    ...
}

class ModelBEvent {
    List<ModelB> models;
    ...
}

EventBus.getDefault().post(new ModelAEvent(list));
```
