### ISSUE TITLE
Define Subscribe method in Parent class doesn't receive event when error.

### ISSUE THREAD

**Issue by fanturbo** [greenrobot/EventBus#470]
I define Subscribe method in BaseActivity as follow.
```java
@Subscribe
    public void loginAndRefresh(LoginEvent loginEvent) {
        ToastUtil.show(this, "kkkk");
        if (loginEvent.getI() == 1) {
            loginEvent = null;
            Logger.i(loginEvent.getI());
        }
    }
```
Sometimes this method will produce error,here I intentionally produce a nullPointException when  i is 1. But when i post event again(i is not 1),I can't receive event in this method.I want to know why.
If I define Subscribe method in MainActivity(not in BaseActivity),code run correct.

**Comment by greenrobot-team** [comment]
I can't really tell where the exact issue is without a complete example. Is maybe another subscriber method [cancelling the event](http://greenrobot.org/eventbus/documentation/priorities-and-event-cancellation/) which prevents this method from receiving it? Uwe

**Comment by fanturbo** [comment]
https://github.com/fanturbo/EventBusDemo
I write done a demo to test where eventbus is incorrect but finally i found that it's my mistake.BaseActivity is not exist when i post event :(.Very sorry to waste your time.
