### ISSUE TITLE
DaoMaster.DevOpenHelper class def not found build for android tablet only

### ISSUE THREAD

**Issue by andrewindayang** [greenrobot/EventBus#473]
Hi, I got an issue where DaoMaster.DevOpenHelper not found : classnotfounddef. i have search entire git test with the pro guard and i test with update the gradle and etc. i still got crashing issue on that part when i build into my tablet but it is ok for my phone. any idea how to solve it? Please response to me and  i had tried all of possible solution that i found on online and on this git. thank you

**Comment by greenrobot-team** [comment]
This is the EventBus project. You maybe are looking for [the greenDAO project](https://github.com/greenrobot/greenDAO)?
-ut
