### ISSUE TITLE
subscribing method never gets called

### ISSUE THREAD

**Issue by Yuliya-Kaleda** [greenrobot/EventBus#477]
I am testing greenrobot in Android Instant Apps and have noticed that some subscribing methods are not being called, while others work fine. In installable app all the events get called as expected. I am on version 2.4.1

Here is a subscribing method example:

```
public void onEventMainThread(AuthEvents.EventAuthSuccess event) {
    if (currentFragment == FragmentEnum.FRAGMENT_MY_ACCOUNT) {
      accountManager.loadDataForAccountPage();
      myAccountFragment.syncProgress();
    }
    cartManager.getCartDetails();
  }

```

Here is a snippet of the a post event:

```
public void continueAfterSave() {
    EventBus.getDefault()
      .post(new AuthEvents.EventAuthSuccess());
    analyticsManager.trackUserIdentity(this);
    setResult(Activity.RESULT_OK);
    this.finish();
  }

```

**Comment by greenrobot-team** [comment]
onEvent methods are only called if the class that has them is registered to EventBus. When registering [EventBus uses reflection to find your methods](https://github.com/greenrobot/EventBus/blob/V2.4.0/EventBus/src/de/greenrobot/event/SubscriberMethodFinder.java#L54). Are you sure that the classes where onEvent methods are not called are registered? -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
