### ISSUE TITLE
Failed to navigate the main thread

### ISSUE THREAD

**Issue by eugenio1590** [greenrobot/EventBus#478]
Having a subscriber waiting for an event in the main thread, navigation fails. This can be caused because the subscriber actions are asynchronous and the main activity is paused (executing the onPause event).

When attending the event at the subscriber, an attempt is made to redirect to another activity and but the main event is paused. In the log we get something like this:

````
V/InputMethodManager: onWindowFocus: android.support.v7.widget.AppCompatEditText{e2c2f4d VF.D..CL. .F....ID 0,0-408,78 #7f0e0076 app:id/txt_password} softInputMode=32 first=false flags=#81810100
D/ActivityThread: ACT-AM_ON_PAUSE_CALLED ActivityRecord{ba54c66 token=android.os.BinderProxy@f8ccba7 {com.eatfood.app.suggestfood/com.eatfood.app.suggestfood.features.login.view.LoginActivity}}
D/ActivityThread: ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@f8ccba7
....
E/MultiWindowProxy: getServiceInstance failed!
....
D/ActivityThread: ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{b90de06 token=android.os.BinderProxy@ef88cc7 {com.eatfood.app.suggestfood/com.eatfood.app.suggestfood.features.dashboard.view.MainActivity}}
D/ActivityThread: ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@ef88cc7
````

The subscriber is the following:
````
public class Subscriber {
    private LoginActivity view;

    public void asynchronousAction(){
        //Task lasting at least half a minute
        //And publish the respective event
    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onMessageEvent(MessageEvent event) {
         view.navigateToMainScreen();
    }
}
````

The main activity is:
````
public class LoginActivity extends Activity {
    public void navigateToMainScreen(){
        Intent intent = new Intent();
        intent.setClass(this, MainActivity.class);
        startActivity(intent);
    }
}
````

**Comment by greenrobot-team** [comment]
Where exactly do you register and unregister from EventBus? Note that on Android you should not keep a reference to an activity inside a class that might outlive the activity. Read up on [the Android activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle.html).

If you can not guarantee that the activity is registered to EventBus when the task finishes, you might be able to use [use sticky events](http://greenrobot.org/eventbus/documentation/sticky-events).
-ut

**Comment by eugenio1590** [comment]
@greenrobot-team I record the EventBus object in the onCreate event and the unregister in the onDestroy event of the main activity. I have not used the sticky event yet.

**Comment by greenrobot-team** [comment]
@eugenio1590 So do sticky events work for your case? -ut

**Comment by eugenio1590** [comment]
@greenrobot-team Using sticky events the application goes crazy. An endless cycle is generated due to failed retry to the main screen. The error generated is the same but an endless number of times.

**Comment by eugenio1590** [comment]
- [ x] With PendingIntent not working.

**Comment by greenrobot-team** [comment]
I really think you should take a look at how Android activities work. If you already know the basics, you should have a look at the [Tasks and Back Stack](https://developer.android.com/guide/components/activities/tasks-and-back-stack.html) documentation. This issue tracker is to resolve EventBus issues, I do not have the time to do in-depth Android development support. -ut
