### ISSUE TITLE
About AsyncExecutor...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [greenrobot/EventBus#480]
About this:
http://greenrobot.org/eventbus/documentation/asyncexecutor/

The `handleFailureEvent `is called for all exceptions that you get, even from other AsyncExecutor calls.

This means, that as opposed to listening to specific events, here all error calls are gathered into a single function.

For example, if I call `AsyncExecutor.create().execute(...)` on multiple classes, and I have `handleFailureEvent `somewhere, it can get the error from all those classes, and I won't know what to do with them, because I lost the context...

Is there a way to differentiate the errors somehow? 
The only solution I can think of, is not to use the `handleFailureEvent` at all, and just use a try-catch in the `RunnableEx`, that will send a unique event instead of throwing an exception.

**Comment by greenrobot-team** [comment]
You can call `.getThrowable` on the `ThrowableFailureEvent` event that is posted if an exception occurs to get the original exception. Using `instanceof` you may then look for specific exception types.
-ut

**Comment by AndroidDeveloperLB** [comment]
That's still not unique. If in 2 calls to `AsyncExecutor.create().execute(...)` , both of them throw the same exception, it won't be possible to handle both correctly.
Also, even if it was unique enough, it doesn't make sense to handle them all in one place. Each `handleFailureEvent` should be assigned to the `AsyncExecutor.create().execute(...)` it was meant to handle.

I know it's a bit hard to understand this, but I don't think it's safe to use this API part of the library, unless there is only a single `AsyncExecutor.create().execute(...)` and `handleFailureEvent` in the entire project.

**Comment by greenrobot-team** [comment]
This is how `AsyncExecutor` was designed to work. If this does not fit your requirements, there is no need to use it. As you suggested, just use a try block and then possibly post a unique failure event in the catch block. -ut

**Comment by AndroidDeveloperLB** [comment]
Can you please consider making it work differently? So that it will be more like events, instead of collecting the errors from all places you used `AsyncExecutor.create().execute(...)` ?

Maybe something like this:

```
@Subscribe(threadMode = ThreadMode.MAIN)
public void handleFailureEvent(**LoginException** exception) {
    // do something
}
```

Have you understood the issue here?

**Comment by william-ferguson-au** [comment]
I would be against such a change. You would be creating an implicit distribution of the success and failure logic.  You are much better served by having an explicit success and failure paths defined in your event handler, and to use the generic handler for any unhandled RuntimeExceptions.

Doing it the way you suggest would create spaghetti code.

**Comment by AndroidDeveloperLB** [comment]
It's exact equivalant to unique events.
Why should it be " spaghetti code" ? 
Each class that uses `AsyncExecutor.create().execute` , can have all its declared exceptions unique, just just as if you'd declare unique events there.

For example:
ClassA, calls `AsyncExecutor.create().execute` , has ExceptionA.
ClassB, calls `AsyncExecutor.create().execute` , has ExceptionB.

If ClassC has the next code, it will only handle exceptions of ClassB :

```
@Subscribe(threadMode = ThreadMode.MAIN)
public void handleFailureEvent(ExceptionB exception) {
    // do something
}
```

Now, to the alternative solution I've written before, if instead of exceptions, you'd use events, you would get the exact same logic, and exact same level of uniqueness and (almost the same) amount of code (because of a new function, `handleFailureEvent`).
