### ISSUE TITLE
EventBusException in EventBusBuilder.installDefaultEventBus (EventBusBuilder.java:123). Version is 2.4.0.

### ISSUE THREAD

**Issue by ruslanle** [greenrobot/EventBus#481]
I configure EventBus once in onCreate method of my Application class.
``` 
EventBus.builder()
                .logNoSubscriberMessages(false)
                .installDefaultEventBus();
```
 But in Crashlytics I have the next crash : 
```Fatal Exception: java.lang.RuntimeException
Unable to create application: de.greenrobot.event.EventBusException: Default instance already exists. It may be only set once before it's used the first time to ensure consistent behavior.
```
This crash is not frequent, but how can it happen, if I configure EventBus in Application class? Is it the bug of the library or maybe of a device?

**Comment by greenrobot-team** [comment]
I have seen this behavior before in different apps. It should be relatively safe to guard the install call and just ignore the exception. -ut

**Comment by ruslanle** [comment]
Thanks for the reply.
