### ISSUE TITLE
How to return value on subscribe after post (android)

### ISSUE THREAD

**Issue by farzadnone** [greenrobot/EventBus#482]
hi, i need receive value on subscribe after post.
i need to return value. example: `myReturnValueFromSubscribe`

i post this:

```
OnEvent onEvent = new OnEvent(obj);
String myReturnValueFromSubscribe =  GlobalBus.getBus().post(onEvent);
```

and receive:

```
@Subscribe
public void onEvent(OnEvent obj) {
     // .......
     return ....anything.....; //myReturnValueFromSubscribe
}
```

is possible and how?
thanks

**Comment by william-ferguson-au** [comment]
EventBus and event handling in general does not work like that.
You are describe a synchronous method invocation.

**Comment by greenrobot-team** [comment]
So no, this is not possible with EventBus. -ut

**Comment by kgonul** [comment]
use posting thread of eventbus to listen event. It will block calling thread. You may put return value to passed event object. Thats tricky solution

**Comment by william-ferguson-au** [comment]
@kgonul that is a terrible solution. It means that your calling thread is tied to all the receiving threads. Coding in this way will over complicate and cripple your app.

If you need to block execution until you receive a return value, then execute a method, don't try and use an event bus.

If you don't need to block but still need a result when the 2nd operation completes, then have that 2nd operation generates its own event.
