### ISSUE TITLE
Can I @Subscribe events in parent class?

### ISSUE THREAD

**Issue by lazercorn** [greenrobot/EventBus#485]
"Registering will only find methods on the immediate class type. Unlike the Guava event bus, Otto will not traverse the class hierarchy and add methods from base classes or interfaces that are annotated. This is an explicit design decision to improve performance of the library as well as keep your code simple and unambiguous."

Otto doesn't traverse class hierarchy and add methods from base classes or interfaces that are annotated. Does EventBus traverse?

**Comment by greenrobot-team** [comment]
No, as annotations can not be inherited. EventBus will only pick up methods for the class that has the `@Subscribe` annotation.

You can also see this in my [unofficial example](https://github.com/greenrobot-team/greenrobot-examples/blob/master/eventbus/app/src/main/java/com/example/eventbus/BlankFragment.java).
-ut
