### ISSUE TITLE
Android: Is call method @Subscribe after 20 sec?

### ISSUE THREAD

**Issue by lmdic** [greenrobot/EventBus#488]
Suppose I have Activity with button.
After click button I open fragment.
Before open fragment I sent eventBus message.

Something like this (on Activity)

```
    public class DetailsActivity extends AppCompatActivity {
    
    @OnClick(R.id.imageViewr)
    public void onClick() {
      EventBus.getDefault().post(new CategoryFilterEvent(categoryId));
      // open fragment
      FragmentManager fragmentManager = getSupportFragmentManager();
      fragmentManager.beginTransaction().replace(R.id.mainActivity, currentFragment).commit();
    }
    
    }




```

Here snippet on fragment:

    public class MapFragmentTab extends Fragment {
    
        @Subscribe
        public void onChangeFilter(CategoryFilterEvent categoryFilterEvent) {
    
        }    
    }

OK. It's work.
When fragment is create the method `onChangeFilter() `is call. Nice.

But suppose that fragment will be create **not immediately** after click button on Activity, but after 20 seconds.
In this case is method `onChangeFilter()` is call in fragment (after 20 sec)?

**Comment by greenrobot-team** [comment]
The event will only be posted to subscribers that are currently registered. So in your case the answer is: no.

You might want to try using [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/) to solve this problem.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
