### ISSUE TITLE
use in kotlin bug

### ISSUE THREAD

**Issue by dongxi346** [greenrobot/EventBus#490]
this version doesn`t regist onStart(), it should be onCreate() regist

**Comment by greenrobot-team** [comment]
Sorry, I do not follow. Do you have a code example of what does not work?

Keep in mind that you can `register(Object)` wherever you want. Using `onStart()` is just a reasonable suggestion. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
