### ISSUE TITLE
Fragment not receive onEvent data update

### ISSUE THREAD

**Issue by ant-ia** [greenrobot/EventBus#491]
Hi,
I have an Activity which contains 3 Fragment.
The three fragments implement the same logic for subscribers:

`    @Subscribe(threadMode = ThreadMode.MAIN) `
   `  public void onEvent(Event event){
        \\todo stuff
    }`

`    @Override`
    `  public void onStart() {
        super.onStart();
        GlobalBus.getBus().register(this);
    }
  ` 

   `  @Override  ` 
     `  public void onStop() {
        super.onStop();
        GlobalBus.getBus().unregister(this);
    }
`

The EventBus post done in AsyncTask:
`GlobalBus.getBus().post(new Event(data));`

Currently it appears that only two fragments of 3 receive the data event.
On the third fragment the data arrives null.
Any suggestions for solving this problem?
Or how can I expect to run the onEvent first before proceeding with other operations onCreateView?

**Comment by greenrobot-team** [comment]
Events are only received while a class is registered. So if the event is posted just before the third fragment is past `onStart()`, it won't receive the event.

You can either [persist your shared data](https://developer.android.com/training/data-storage/index.html) using something like SharedPreferences or a database, or you can try using [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).
-ut

**Comment by ant-ia** [comment]
@greenrobot-team, Ok, thanks for reply.
Maybe the question I'm about to do is silly, can I register the bus in the onCreate instead of the onStart to receive the event first? since the onCreate is called earlier than the onStart.
Or do I get out of the logic of implementing the bus?

**Comment by greenrobot-team** [comment]
You can register wherever you want. You just have to make sure to unregister before registering again and before the subscriber is destroyed. So typically using a combination of onCreate/onDestroy or onStart/onStop works best. -ut
