### ISSUE TITLE
typesBySubscriber should be thread-safe

### ISSUE THREAD

**Issue by balizhuang2012** [greenrobot/EventBus#492]
Does EventBus.regiester() method supports multi-thread calling?
If yes, typesBySubscriber should be thread-safe, otherwise it will cause bug.
Unfortunately, it is just a HashMap object in source code.

**Comment by balizhuang2012** [comment]
EventBus.typesBySubscriber

**Comment by greenrobot-team** [comment]
EventBus should be thread-safe. If you can give us a small example project where it is not, that would help us fix any issues. -ut
