### ISSUE TITLE
How to generate index in multi module

### ISSUE THREAD

**Issue by zouzhenglu** [greenrobot/EventBus#493]
As the subject. I know how to add index when I init the eventBus, but How Can I generate the index when I want to use the eventbus in multi module

**Comment by greenrobot-team** [comment]
You can try the instructions in the [Subscriber Index documentation](http://greenrobot.org/eventbus/documentation/subscriber-index/#Indexing_your_Libraries). -ut

**Comment by X-FAN** [comment]
@greenrobot-team I  add 
`        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [eventBusIndex: 'com.example.myapp.MyEventBusLibIndex']
            }
        }`
in my library module build.gradle, but not generate MyEventBusLibIndex class. Can you tell me why?

**Comment by greenrobot-team** [comment]
@X-FAN Did you also add the library and annotation processor to your dependencies?
```
dependencies {
    implementation 'org.greenrobot:eventbus:3.1.1'
    annotationProcessor 'org.greenrobot:eventbus-annotation-processor:3.1.1'
}
```

**Comment by hanhmh1203** [comment]
can you give me an example to add eventbus into Kotlin ? i don't know what is MyEventBusIndex

**Comment by satyarths** [comment]
The approach requires configuring the package name for each module  to have all of those installed at app level. Would it  be possible to have a default location (in each module's package hierarchy) for the index file to be  generated?
