### ISSUE TITLE
Subscribing on Main thread and not receiving event posted from background thread

### ISSUE THREAD

**Issue by omidsjg** [greenrobot/EventBus#496]
I've come across something odd and didn't see an open issue. 

I am using the latest EventBus version (3.1.1) and testing on an android device running 8.0. 

1.) I've registered an activity to the event bus in OnCreate:
        `EventBus.getDefault().register(this);`
2.) In a background thread, I'm posting an event from the doInBackground() method:
       `EventBus.getDefault().post(MyEvent(params));` 
3.) Subscribing in my activity:
        ```@Subscribe(threadMode = ThreadMode.MAIN)
         public void onEvent(MyEvent event) {
           // log something
        }```

and from my logging this method is never reached. 

Anyone else come across this?

**Comment by greenrobot-team** [comment]
Make sure that your activity is subscribed before the event is posted. If you can not guarantee that you may try [sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/). -ut
