### ISSUE TITLE
Sticky events are received multiple times

### ISSUE THREAD

**Issue by bdeneuter** [greenrobot/EventBus#50]
When working with sticky events I noticed that I received events multiple times. This was the case where registering and posting of events happen at the same time. I had a quick look in the code. In the postSticky method I noticed that the lock on the stickyEvents object is released immediatly after putting a sticky event. Then the event is posted to the current listeners. 
For registering, the listener is first registered to receive events and afterwards tries to get the sticky event. When it gets the sticky event, it will receive it. This means a listener can get an event twice: 
1. The first one because the listener is already registered and the postSticky post the event to the listeners. 
2. A second one because during registering the sticky event is already found that was placed by the postSticky

**Comment by jshqhxm** [comment]
removeStickyEvent can fix this	problem
EventBus.getDefault().removeStickyEvent(NotifyToJoinEvent.class);
