### ISSUE TITLE
could not dispatch event

### ISSUE THREAD

**Issue by blennerSilva** [greenrobot/EventBus#500]
Hey guys im sending an event from a fragment to a fragment and im getting this error 

Could not dispatch event: class com.folioreader.model.event.GoToChapterEvent to subscribing class class com.folioreader.ui.folio.fragment.EpubReaderFragment
java.lang.IllegalStateException: FragmentManager is already executing transactions

can you help me out?

**Comment by william-ferguson-au** [comment]
This has nothing to do with EventBus.
It has to do with what you are invoking on the FragmentManager.

The stacktrace should tell you.
