### ISSUE TITLE
Greenrobot crashes if "minifyEnabled true"

### ISSUE THREAD

**Issue by swagatamadeus** [greenrobot/EventBus#503]
Hello Guys,

I am using greenrobot lib with camera events and works fine if I install directly on device. But if I install from play store, app crashes. Basically if I enable **"minifyEnabled true"**, it breaks. 

But this works when I add proguard rules for greenrobot package as below
**“-keep class org.greenrobot.** {*;}”**

Could you please let me know how to deal with this? 

Is there any limitation with greenroot library, if minification is applied?

Regards
Swagat

**Comment by greenrobot-team** [comment]
Have a look at http://greenrobot.org/eventbus/documentation/proguard -ut
