### ISSUE TITLE
Can't get Eventbus to work across fragments

### ISSUE THREAD

**Issue by Pheromone89** [greenrobot/EventBus#509]
>         EventBus.getDefault().post(new DataCommunication(empName));
>         Fragment fragment = new FirstFragment();
>         FragmentManager fragmentManager = getFragmentManager();
>         FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
>         fragmentTransaction.replace(R.id.content_fragment_area, fragment);
>         fragmentTransaction.commit();
This happens inside an onItemClick method in the first fragment. I tried Eventbus with and without registering this class. I declared empName before and the value should be there beforehand.

>     @Override
>     public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
>         rootView = view;
>         EventBus.getDefault().register(this);
>     }
> 
>     @Subscribe
>     public void onEvent(DataCommunication event){
>         nameView = (TextView) rootView.findViewById(R.id.name_view);
>         nameView.setText(event.getAllData());
>     }
I put this in the second fragment. I tried moving registering to onStart but nothing seems to work. The library works fine within the same class/fragment but I can't get it to work on different class/fragments.
This is the `DataCommunication `class that I set as the event class.
public class DataCommunication {

>     private final String allData;
> 
>     public DataCommunication(String string) {
>         allData = string;
>     }
>     public String getAllData(){
>         return allData;
>     }
> }

**Comment by MichelFortes** [comment]
It seems that you are posting an event before the fragment register itself, so it is not able to catch the event. One possible solution is post it as a sticky event (postSticky), so EventBus will deliver it everytime an activity (or a fragment) register itself. Dont forget to remove the event at the time its no more usefull.

**Comment by Pheromone89** [comment]
Thanks for the reply, I tried it as sticky before but I can't register the class as sticky ( `registerSticky(this)` ). It was red and not compile-able. I can postSticky with normal register but subscribe method still didn't work.

Also, what did you mean "remove the event"? Sorry, I'm quite new to programming in general. Is there any method that I use to remove said event?

**Comment by MichelFortes** [comment]
Ok. Try this:

Posting event:
```
EventBus.getDefault().postSticky(new DataCommunication(empName));
    Fragment fragment = new FirstFragment();
    FragmentManager fragmentManager = getFragmentManager();
    FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
    fragmentTransaction.replace(R.id.content_fragment_area, fragment);
    fragmentTransaction.commit();
```

Receiving event (onStart Method):
```
@Override
public void onStart() {
    EventBus.getDefault().register(this);
}

@Subscribe(sticky=true)
public void onEvent(DataCommunication event){
    nameView.setText(event.getAllData());
}
```

To remove the sticky event, use
`EventBus.getDefault().removeStickyEvent(DataCommunication.class);`

**Comment by greenrobot-team** [comment]
Just noting again that this is all covered in the documentation at http://greenrobot.org/eventbus/documentation/ -ut
