### ISSUE TITLE
please fix for AndroidStudio3.0 Error:: Gradle DSL method not found: 'implementation()' 

### ISSUE THREAD

**Issue by yaya2212** [greenrobot/EventBus#512]
Gradle DSL method not found: 'implementation()' Possible causes:
The project 'AndroidPractices' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0). Upgrade plugin to version 3.0.1 and sync project
The project 'AndroidPractices' may be using a version of Gradle that does not contain the method. Open Gradle wrapper file
The build file may be missing a Gradle plugin. Apply Gradle plugin

**Comment by greenrobot-team** [comment]
This should not be an issue with EventBus. The message clearly indicates that you [should update your project to using Android Gradle Plugin 3.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html). -ut

**Comment by uluk1507** [comment]
> This should not be an issue with EventBus. The message clearly indicates that you [should update your project to using Android Gradle Plugin 3.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html). -ut

for some reason its not even letting update it properly, saying cannot be updated
