### ISSUE TITLE
org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass when using @TargetAPI

### ISSUE THREAD

**Issue by frmz** [greenrobot/EventBus#514]
Looks similar to #508 although i dont think its the same issue. So, in my code i have the following statement

`        @TargetApi(Build.VERSION_CODES.O_MR1)
        private WallpaperColors mWallpaperColors = null;`

This causes the following issue when registering on EventBus in Android 4.4

`java.lang.NoClassDefFoundError: android/app/WallpaperColors
	at java.lang.Class.getDeclaredMethods(Class.java)
	at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
	at java.lang.Class.getMethods(Class.java:877)
	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass`

Caused by:

`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.WallpaperColors"
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)`

Is there any way to make EventBus ignore that class?

**Comment by greenrobot-team** [comment]
The only solution I can think off is to make sure that the class instance that you call `EventBus.register(instance)` in does not use classes that may be unavailable on older SDKs.

Also [see the FAQ](http://greenrobot.org/eventbus/documentation/faq/) about this. -ut

**Comment by frmz** [comment]
I ended up using an Object and then checking correct type in a Oreo only code, not nice but works

**Comment by frmz** [comment]
Just for future reference i was able to cleanly fix this by using EventBus indexing
