### ISSUE TITLE
Failed to resolve : eventbus

### ISSUE THREAD

**Issue by ningjiaqi** [greenrobot/EventBus#517]
when I use the version:3.1.1，Error Occurred while building，but when I use the version 3.0.0，it's no problem，what's wrong?

**Comment by oNguyenDucManh** [comment]
I just got this error, please help

**Comment by MaxToyberman** [comment]
@oNguyenDucManh  @ningjiaqi  adding `mavenCentral()` to allprojects -> repositories in build.gradle solved the problem

**Comment by buthela** [comment]
I got this error with:
 - com.android.tools.build:gradle:3.1.0
 - distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip

Work OK with
 - com.android.tools.build:gradle:3.0.1
 - distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by buthela** [comment]
Resolved with:
-  com.android.tools.build:gradle:3.1.0
-  distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip

Don't need add mavenCentral() to allprojects

**Comment by ningjiaqi** [comment]
@buthela 3.0.1 or 3.1.0 need to update AndroidStudio?

**Comment by buthela** [comment]
@ningjiaqi Yes, Android Studio 3.1

**Comment by greenrobot-team** [comment]
Closing this then as a tooling issue.

For completeness: EventBus is published to Maven Central, however this is synced to jCenter which is added by default in new Android projects.
-ut
