### ISSUE TITLE
Subscriber method must be 'public', why?

### ISSUE THREAD

**Issue by ruanshanshan** [greenrobot/EventBus#519]
the source code: 
if (subscriberMethods.isEmpty()) {
            throw new EventBusException("Subscriber " + subscriberClass
                    + " and its super classes have no public methods with the @Subscribe annotation");
        }

why the subscriber method must be 'public'?

**Comment by greenrobot-team** [comment]
Otherwise it can not be seen and called by EventBus. -ut

**Comment by ShrutiLK** [comment]
Is it because it uses BroadcastReceivers internally?

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut
