### ISSUE TITLE
Subscribe method not receiving any event 

### ISSUE THREAD

**Issue by omardhanish** [greenrobot/EventBus#527]
Subscribe method is quiet and not receiving any event , confused for long time , new to eventbus library and i just followed the tutorial 
```
public class MultiPlayerScreenActivity extends AppCompatActivity {

    private MultiPlayerPresenter multiPlayerPresenter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        multiPlayerPresenter = new MultiPlayerPresenter();
        multiPlayerPresenter.showMessage("EventBus activated");
    }

    @Override
    public void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
        Log.e(this.getClass().getName() , "registered");
    }

    @Override
    public void onStop() {
        super.onStop();
        EventBus.getDefault().unregister(this);
        Log.e(this.getClass().getName() , "unregistered");
    }

     // not receiving any event here
    @Subscribe
    public void toastMessage(ViewEvents events){
        Toast.makeText(this, events.getToastMessage(), Toast.LENGTH_SHORT).show();
    }

}
```

From this class i am trying to post event but subscribe method is just quiet 

```
public class MultiPlayerPresenter {


    public void showMessage(String message){
        EventBus.getDefault().post(new ViewEvents(message));
        Log.e(this.getClass().getName() , "posted");
    }

}
```

**Comment by Liberations** [comment]
public class MultiPlayerPresenter {
        public void showMessage(String message){
        EventBus.getDefault().postSticky(new ViewEvents(message));
        Log.e(this.getClass().getName() , "posted");
    }
}

**Comment by ShrutiLK** [comment]
Probably you missed to post the event itself. The gist of EventBus is such that the class where you post the event as well as the class which is receiving the event should be registered by EventBus.gerDefault().regsiter(this); 

In your case your MultiPlayerPresenter class should include the lines

EventBus.gerDefault().regsiter(this); 
EventBus.getDefault().post(new ViewEvents(message));

**Comment by greenrobot-team** [comment]
Your event is posted in `onCreate()`. However, EventBus is not registerd for that class until later in `onStart()`. Either post the event later or maybe [look into sticky events](http://greenrobot.org/eventbus/documentation/configuration/sticky-events/).

Closing. Please re-open if your question was not answered.
-ut
