### ISSUE TITLE
Instructions for recent versions of gradle

### ISSUE THREAD

**Issue by evbarnett** [greenrobot/EventBus#537]
If you are using gradle plugin version > 3.0 (which requires gradle v. > 4.0 (?)), then the following line from the readme will not work:

``compile 'org.greenrobot:eventbus:3.1.1'``

Instead, you must use ``api``

``api 'org.greenrobot:eventbus:3.1.1'``

If you use ``compile`` or ``implementation``, your project will compile but gradle will not be able to load event bus from the classpath during runtime. ``api`` tells gradle to keep the lib on the classpath.

**Comment by moaxcp** [comment]
Is this an issue with documentation? Would you like to see the docs to include info for each version of gradle?

**Comment by greenrobot-team** [comment]
Using `implementation` should work just fine. Doing that in various projects.

Updated the README file.
-ut
