### ISSUE TITLE
could i switch to close all the logs

### ISSUE THREAD

**Issue by yindangchao** [greenrobot/EventBus#542]
could i switch to close all the logs

**Comment by greenrobot-team** [comment]
Closing due to missing details. Please re-open if you can share more details on what it is that you want to do or change. Preferably with a code example. Thanks. -ut

**Comment by DamonChen117** [comment]
What I'm doing in kotlin

`package org.greenrobot.eventbus

import java.util.logging.Level

class MuteLogger: Logger {
    override fun log(level: Level?, msg: String?, th: Throwable?) {
    }

    override fun log(level: Level?, msg: String?) {
    }
}



class MyEventBus()
{
    companion object {
        val my = myEventBus()

        private fun myEventBus() : EventBus
        {
            val builder = EventBusBuilder()
            builder.logger(MuteLogger())
            return EventBus(builder)
        }
    }
}
`

**Comment by greenrobot-team** [comment]
Oh, you want to turn off log messages of `EventBus`? You can try:

`EventBusBuilder().logSubscriberExceptions(false).logNoSubscriberMessages(false)`

See the [JavaDoc](http://greenrobot.org/files/eventbus/javadoc/3.0/org/greenrobot/eventbus/EventBusBuilder.html).
-ut

**Comment by DamonChen117** [comment]
Note that EventBusBuilder is not public, it's package.
I think it's better public.
