### ISSUE TITLE
The update and support plan of that library.

### ISSUE THREAD

**Issue by Nobler** [greenrobot/EventBus#544]
Latest version of the library was released about 9 months ago. 

Will that library release new version? And how long the library will be supported?
I'm afraid one day that library will be tagged as deprecated.

**Comment by greenrobot-team** [comment]
It currently works as is. We may do a new release from time to time. If in doubt, this library is completely open source. So if at all necessary you could make modifications by forking it.

Closing. Please re-open if your question was not answered.
-ut

**Comment by Nobler** [comment]
Many thanks.

greenrobot Team <notifications@github.com> 于 2018年8月27日周一 21:05写道：
