### ISSUE TITLE
WHY AndroidHandlerMainThreadSupport.isMainThread() use Looper.myLooper() but not Looper.getMainLooper() ?

### ISSUE THREAD

**Issue by jiangxiao2008** [greenrobot/EventBus#547]
If invoke this method in a sub-thread, say a HandlerThread, it will return a wrong result.
Use Looper.getMainLooper() is correct, right?

**Comment by greenrobot-team** [comment]
Look at how it is constructed:
https://github.com/greenrobot/EventBus/blob/3670d97835f15d0966e29fb8f52785ca3e87c2af/EventBus/src/org/greenrobot/eventbus/EventBusBuilder.java#L168-L187

`looper` will be the main looper.

Closing. Please re-open if your question was not answered.
-ut
