### ISSUE TITLE
Support for latest API level

### ISSUE THREAD

**Issue by ebghrimtech** [greenrobot/EventBus#551]
Hello,

We are currently using EventBus in one of our applications. Actually we need a favour from your side. According to the updated [Google Play Policy](https://developer.android.com/distribute/best-practices/develop/target-sdk#check_and_update_your_sdks_and_libraries), all apps have to provide support for at least API level 26 which is satisfied in your case. We are targeting API level 28 and haven't found any issues as of now. Do we have to make any changes for API level 28?

**Comment by greenrobot-team** [comment]
I don't see why. If you find any, feel free to report them. -ut
