### ISSUE TITLE
How to Post sticky, keep event in stack, and consume with many fragments when they resume?

### ISSUE THREAD

**Issue by erfannf** [greenrobot/EventBus#558]
I am using EventBus in my app for delivering events from a service to many fragments which some of them are in paused state and one of them is active. When an object is removed from DB, a DeleteEvent would be broadcast sticky. The active fragment takes the event and does the operation. Of course, other fragments would not receive the event. Is there any way to get the event in paused fragments when they come to running state?

**Comment by greenrobot-team** [comment]
You can get the sticky event manually.
http://greenrobot.org/eventbus/documentation/configuration/sticky-events/

-ut
