### ISSUE TITLE
How to configure logging

### ISSUE THREAD

**Issue by moaxcp** [greenrobot/EventBus#563]
I'm using EventBus in a pure java application that uses slf4j. I am having trouble figuring out why EventBus logs to stdout rather than the application log. What system is it using? Is it possible to provide some information in the site for logging and examples for using different logging systems?

**Comment by greenrobot-team** [comment]
See #134 and #280.

And have a look at the Logger and related classes.
https://github.com/greenrobot/EventBus/blob/master/EventBus/src/org/greenrobot/eventbus/Logger.java

-ut
