### ISSUE TITLE
can't generate EventBusIndex

### ISSUE THREAD

**Issue by MichaelJokAr** [greenrobot/EventBus#580]
![image](https://user-images.githubusercontent.com/8246218/56859309-9d473080-69bb-11e9-97f8-12a5c50cd052.png)
![image](https://user-images.githubusercontent.com/8246218/56859320-b6e87800-69bb-11e9-8407-61baf59a0771.png)
![image](https://user-images.githubusercontent.com/8246218/56859321-bd76ef80-69bb-11e9-91e0-b0542d0dc5ac.png)

after import and rebuild ,the build folder not generate any EventBusIndex
![image](https://user-images.githubusercontent.com/8246218/56859342-d8496400-69bb-11e9-8340-d95061675d66.png)

**Comment by MichaelJokAr** [comment]
I'm using ```'com.android.tools.build:gradle:3.3.2'```

**Comment by greenrobot-team** [comment]
Are you using Kotlin by any chance? Check the instructions for kapt then.
http://greenrobot.org/eventbus/documentation/subscriber-index/

But if this is for a Java Android app the setup looks good. Can't really help then without an example project.
-Uwe

**Comment by MichaelJokAr** [comment]
no。I'm using java

**Comment by MichaelJokAr** [comment]
you can  Reproduce this for create new application above gradle plugin v3.2.1

**Comment by MichaelJokAr** [comment]
ok, it's generated now
