### ISSUE TITLE
butterknife evenbuts can't work atthe same time

### ISSUE THREAD

**Issue by molele2** [greenrobot/EventBus#582]
```
apply plugin: 'com.jakewharton.butterknife' 
  classpath 'com.android.tools.build:gradle:3.4.0'
 
implementation 'com.jakewharton:butterknife:9.0.0-rc3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-rc3'

    implementation 'org.greenrobot:eventbus:3.1.1'
```

**Comment by xianfeng92** [comment]
butterknife and evenbuts can work together~

**Comment by greenrobot-team** [comment]
We also use Butterknife and EventBus in a project together, what exactly is not working?
-Uwe

**Comment by sunreview** [comment]
![88862F2D-4070-4F9F-889F-BFF773B5812F](https://user-images.githubusercontent.com/13205117/225567712-ab873920-922b-4601-ade4-95955c43bd3e.png)

write ur build gradle like this 
it works fine for me

**Comment by greenrobot-team** [comment]
@tomridder Thanks. Closing as the original poster did not reply for a long time.
