### ISSUE TITLE
Java and kotlin mixed can not accept events

### ISSUE THREAD

**Issue by bailibaili** [greenrobot/EventBus#596]
```
 //only dependencies
 implementation 'org.greenrobot:eventbus:3.1.1'
```
``` 
//Activity
 EventBus.getDefault().postSticky(new H5AlertEvent());
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                Intent intent = new Intent(mActivity, H5AlertWebViewActivity.class);
                startActivity(intent);

                    }
                }, 5000);
```

```
//onCreate
 EventBus.getDefault().register(this)

//KT
@Subscribe(threadMode = ThreadMode.MAIN, sticky = true)
    public fun onEvent(event: H5AlertEvent) {
        println("实际并没有执行")
}
```
But can't accept the event. Is it not mixed?

**Comment by greenrobot-team** [comment]
This should work.

Note: if you are using a subscriber index (`eventbus-annotation-processor`), make sure to switch `annotationProcessor` to `kapt`.
http://greenrobot.org/eventbus/documentation/subscriber-index/

**Comment by bailibaili** [comment]
> This should work.
> 
> Note: if you are using a subscriber index (`eventbus-annotation-processor`), make sure to switch `annotationProcessor` to `kapt`.
> http://greenrobot.org/eventbus/documentation/subscriber-index/

I only dependency on implementation 'org.greenrobot:eventbus:3.1.1'

**Comment by greenrobot-team** [comment]
Can you provide a small example project that reproduces this? As said, we are not aware of any issues with Kotlin.

**Comment by bailibaili** [comment]
I'm really sorry, it is my own logical question, thanks for your reply.

**Comment by greenrobot-team** [comment]
Closing this then until someone can share a code example to reproduce an issue.
