### ISSUE TITLE
Event is not received when the activity is killed

### ISSUE THREAD

**Issue by mirsaidoff** [greenrobot/EventBus#597]
I am using service <-> activity connection.
I have network interceptor which will logout the user when 401 response comes. 
I am calling most of APIs from the synchronization and location tracking services. 
I am sending event inside the interceptor (when response code == 401)

When, in some cases, activity is being killed in the background, service is running and not aware of activity being killed. Service receives 401 response code and interceptor sends event to the BaseActivity (which is the parent class for all my activity classes). I am listening for the event in the BaseActivity. If Activity (any) is killed, my app does not logout and service is running still. 

The question is: how can I handle that moment? Is there any way to guarantee the event to be received? or should I listen to the event in MyApp.class?

Thanks!

**Comment by greenrobot-team** [comment]
Well, you need to store that info somewhere until the activity is started again. I can think of two solutions:
- Sticky events http://greenrobot.org/eventbus/documentation/configuration/sticky-events/
- A modified LiveData (search for single event LiveData).

**Comment by bigcal6977** [comment]
[{
  "header": "Takeout",
  "title": "Initiated a Takeout",
  "subtitles": [{
    "name": "Requested the following services: My Activity (all resources)"
  }, {
    "name": "You specified that you wanted the archive in zip format, split into 2.00G files, and requested that the output be sent to your email"
  }],
  "time": "2020-05-23T10:10:09.504Z",
  "products": ["Takeout"],
  "details": [{
    "name": "From IP 2600:1010:b100:1e0f:9f9d:cace:f0f6:1a28"
  }]
},{
  "header": "Takeout",
  "title": "Initiated a Takeout",
  "subtitles": [{
    "name": "Requested the following services: Hangouts (all resources) and Mail (1 resource)"
  }, {
    "name": "You specified that you wanted the archive in zip format, split into 2.00G files, and requested that the output be sent to your email"
  }],
  "time": "2020-03-23T15:24:55.285Z",
  "products": ["Takeout"],
  "details": [{
    "name": "From IP 73.90.209.74"
  }]
}]
