### ISSUE TITLE
Can Evnetbus like Nats/Nats-streaming?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [greenrobot/EventBus#599]
Nats/Nats-streaming supports three modes,like the pictures below:

> Publish Subscribe:

![nats-pub-sub1](https://user-images.githubusercontent.com/27602662/61646995-f551b280-acde-11e9-96b2-12cc62605133.png)

> Request Reply:

![nats-req-reply2](https://user-images.githubusercontent.com/27602662/61647018-013d7480-acdf-11e9-861c-664b4ddf5e39.png)

> Queue:

![nats-queue3](https://user-images.githubusercontent.com/27602662/61647002-f97dd000-acde-11e9-8563-50b519f34cc0.png)

----

I wish Eventbus can do all the three things.

**Comment by greenrobot-team** [comment]
I'm not sure what you want here. EventBus does what it was designed for: a publish-subscribe event bus. See the documentation.
https://github.com/greenrobot/EventBus
http://greenrobot.org/eventbus/documentation/delivery-threads-threadmode/

**Comment by AweiLoveAndroid** [comment]
Eventbus looks like Nats/Nats-streaming,so I wish the good idea in Nats/Nats-streaming can be used in Eventbus.

**Comment by SaeedJinat** [comment]
picture 1 : the default . 
picture 2 : the subscriber can post a ReplyEvent which would in return be posted as well . 
picture 3 : supported in 3.1.+ (ThreadMode.MAIN_ORDERED)

**Comment by AweiLoveAndroid** [comment]
@SaeedJinat Thanks you very much.

**Comment by andob** [comment]
picture 2 can be done by using a callback in the event object:
class ReloadStuff(val onReloaded : () -> (Unit))

publish(ReloadStuff(onReloaded = { ... }))

@Subscribe
fun reload(event: ReloadStuff) {
    doReloadThen {
         event.onReloaded()
    }
}

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to comment with more information or create a new issue.
