### ISSUE TITLE
ProGuard configuration

### ISSUE THREAD

**Issue by intrications** [greenrobot/EventBus#6]
I'd like to know if there's a better way but I had to add this to my proguard-project.txt file to stop the onEvent methods being stripped out:

```
-keepclassmembers class ** {
    public void onEvent(**);
}
```

Whatever the best method is should be added to the documentation.

**Comment by smistry-toushay** [comment]
@AndreasZeiser's rule from https://github.com/greenrobot/EventBus/issues/6#issuecomment-17593941 worked for me. Same rule can be found in [HOWTO.md](https://github.com/greenrobot/EventBus/blob/master/HOWTO.md#proguard-configuration)
