### ISSUE TITLE
multiple fragments in an Activity

### ISSUE THREAD

**Issue by zs1973** [greenrobot/EventBus#604]
There are multiple fragments in an Activity, and how to pass information between fragments using EventBus. I cannot receive a published Event using post() or postSticky() 
Activity
`package com.example.fragmentdemo;

import android.support.annotation.NonNull;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;

public class MainActivity extends AppCompatActivity {

    FrameLayout container;

    Fb1 fragment1;
    Fb2 fragment2;

    Button fg1;
    Button fg2;

    private Fragment mCurrentFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        
        fragment1 = new Fb1();
        fragment2 = new Fb2();

        fg1 = findViewById(R.id.fg1);
        fg2 = findViewById(R.id.fg2);

        changeFragment(R.id.fragment_layout, fragment1);
        fg1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                changeFragment(R.id.fragment_layout, fragment1);
            }
        });

        fg2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                changeFragment(R.id.fragment_layout, fragment2);

            }
        });

    }

    public void changeFragment(int resView, @NonNull Fragment targetFragment) {
        //如果Fragment是当前Fragment 不进行操作
        if (targetFragment.equals(mCurrentFragment)) {
            return;
        }
        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        if (!targetFragment.isAdded()) {
            transaction.add(resView, targetFragment, targetFragment.getClass().getName());
        }
        if (targetFragment.isHidden()) {
            transaction.show(targetFragment);
            //targetFragment.onFragmentShow();
        }
        if (mCurrentFragment != null && mCurrentFragment.isVisible()) {
            transaction.hide(mCurrentFragment);
            //mCurrentFragment.onFragmentHide();
        }
        mCurrentFragment = targetFragment;
        transaction.commitAllowingStateLoss();
    }
}
`
Fragment1
`package com.example.fragmentdemo;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.Toast;

import org.greenrobot.eventbus.EventBus;

public class Fb1 extends Fragment {

    Button btn;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        Log.i("-----", "onAttach: "+"fb1");

    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = LayoutInflater.from(getActivity()).inflate(R.layout.fb1,container,false);
        btn = view.findViewById(R.id.btn);
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(getActivity(), "send", Toast.LENGTH_SHORT).show();
                EventBus.getDefault().postSticky(new TEvent("this is text"));
            }
        });

        return view;
    }
}
`
Fragment2
`package com.example.fragmentdemo;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;

public class Fb2 extends Fragment {

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        Log.i("-----", "onAttach: "+"fb2");
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        EventBus.getDefault().register(this);
        View view = LayoutInflater.from(getActivity()).inflate(R.layout.fb2, container,false);
        return view;
    }

    @Subscribe(sticky = true)
    public void onReceiveEvent(TEvent event){
        Log.i("------", "onReceiveEvent: "+event.getT());
    }

    @Override
    public void onPause() {
        super.onPause();
        EventBus.getDefault().unregister(this);
    }
}
`

**Comment by SaeedJinat** [comment]
i think you have 2 issues here : 

1- you have to register & unregister in a proper manner , although its ok to register at onCreateView() and unregister at onPause() i strongly suggest that you put register onStart() and unregister at onStop(). 

2- specify the thread mode in "@Subscribe" to be  ThreadMode.MAIN .

**Comment by zs1973** [comment]
> i think you have 2 issues here :
> 
> 1- you have to register & unregister in a proper manner , although its ok to register at onCreateView() and unregister at onPause() i strongly suggest that you put register onStart() and unregister at onStop().
> 
> 2- specify the thread mode in "@subscribe" to be ThreadMode.MAIN .

thank you , i have solved this problem .  hhhhh
