### ISSUE TITLE
org.greenrobot.eventbus.EventBusException at EventBus.getDefault().register - Motorola Devices with Android 9

### ISSUE THREAD

**Issue by GrazianoCapelli** [greenrobot/EventBus#605]
Recently we started to have some Google Crash Reports from our small GPSLogger App, reporting an EventBusException in our main Activity onResume.

The App is open sourced and GPL-3 licensed, the source code is published on GitHub: [https://github.com/BasicAirData/GPSLogger](https://github.com/BasicAirData/GPSLogger).

Our related issue, with the complete crash report, is opened here: [https://github.com/BasicAirData/GPSLogger/issues/77](https://github.com/BasicAirData/GPSLogger/issues/77).
[Here](https://github.com/BasicAirData/GPSLogger/blob/af81170fe30c0c8dd773deb52cf97095d79497e7/app/src/main/java/eu/basicairdata/graziano/gpslogger/GPSActivity.java#L134) into the code you can find the line that causes the crash on our Release 26.

I first cheched our code, but it seems that our usage of EventBus is correct along the app.

I chosen to open this issue because it seems that the problem occurs only on Motorola devices with Android 9, and the number of reports are small but relevant and increasing.

**Comment by greenrobot-team** [comment]
EventBus is open-source, too! So looking at the lines where the exception originates:
https://github.com/greenrobot/EventBus/blob/2e7c0461106a3c261859579ec6fdcb5353ed31a4/EventBus/src/org/greenrobot/eventbus/EventBus.java#L159-L162

So that means for whatever reason `register` is called even though the activity is still registered. As it only occurs on that device, it might be a bug in that device's version of Android.

**Comment by GrazianoCapelli** [comment]
In effect I looked into your code before opening the issue to verify that EventBus does nothing asynchronously during the unregistering process.
The reason of my check is that we call eventBus _unregister/register_ methods in our Activity's _onPause/onResume_ that, in case of screen rotation, could be temporally very close.

We'll find a way to wrap the register call as suggested without risking to start the activity without registration in case of screen rotation (Because I prefer a crash report rather than a silent bad App's behaviour). Thanks for your tip!

In any case, we'll place `EventBus.getDefault().unregister(this);` before `super.onPause();` in the next App update.

**Comment by GrazianoCapelli** [comment]
The issue has been resolved by using the `!EventBus.getDefault().isRegistered(this)` method, as the @greenrobot-team suggested.

No more crashes occured, thanks for the tip.
And thanks for this great opensource library!
