### ISSUE TITLE
在Fragment里面注册时，传入getActivity()，接收不到回调

### ISSUE THREAD

**Issue by Luffys6** [greenrobot/EventBus#609]
改成this可以正常接收

**Comment by yuhaocan** [comment]
在Fragment中注册传Activity对象，注解又写在Fragment当然不能收到回调。

**Comment by Luffys6** [comment]
大佬说的我不是很明白啊

**Comment by Luffys6** [comment]
> 在Fragment中注册传Activity对象，注解又写在Fragment当然不能收到回调。

大佬说的我不是很明白啊，我debug跟踪看的getActivity()和this是一样的啊

**Comment by yuhaocan** [comment]
一个是获取activity，一个是Fragment本身，怎么会一样的

**Comment by Luffys6** [comment]
> 一个是获取activity，一个是Fragment本身，怎么会一样的

Fragment中this表示的是啥

**Comment by greenrobot-team** [comment]
Sorry, this issue tracker is English-speaking only. I tried to translate, but am unsure what the issue is.

Regardless: have a look at the documentation. http://greenrobot.org/eventbus/documentation/how-to-get-started/

**Comment by Luffys6** [comment]
When registered in Fragment, getActivity () is passed in and no callback is received.

**Comment by Luffys6** [comment]
> Sorry, this issue tracker is English-speaking only. I tried to translate, but am unsure what the issue is.
> 
> Regardless: have a look at the documentation. http://greenrobot.org/eventbus/documentation/how-to-get-started/

When registered in Fragment, getActivity () is passed in and no callback is received.

**Comment by konstant2016** [comment]
你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context

**Comment by Luffys6** [comment]
> 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context

那getActivity ()和this不都是对象本身啊

**Comment by konstant2016** [comment]
getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
EventBus.getDefault().register(this)中的tihs，要求是对象自己

**Comment by konstant2016** [comment]
> > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> 
> 那getActivity ()和this不都是对象本身啊

getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
EventBus.getDefault().register(this)中的tihs，要求是对象自己

**Comment by Luffys6** [comment]
> > > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> > 
> > 
> > 那getActivity ()和this不都是对象本身啊
> 
> getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
> EventBus.getDefault().register(this)中的tihs，要求是对象自己

EventBus.getDefault().register(this)中的tihs也就是fragment自己，getActiviy获取的是Activiy对象，是不是这样的？

**Comment by konstant2016** [comment]
> > > > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> > > 
> > > 
> > > 那getActivity ()和this不都是对象本身啊
> > 
> > 
> > getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
> > EventBus.getDefault().register(this)中的tihs，要求是对象自己
> 
> EventBus.getDefault().register(this)中的tihs也就是fragment自己，getActiviy获取的是Activiy对象，是不是这样的？

对滴，你可算理解啦

**Comment by Luffys6** [comment]
> > > > > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> > > > 
> > > > 
> > > > 那getActivity ()和this不都是对象本身啊
> > > 
> > > 
> > > getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
> > > EventBus.getDefault().register(this)中的tihs，要求是对象自己
> > 
> > 
> > EventBus.getDefault().register(this)中的tihs也就是fragment自己，getActiviy获取的是Activiy对象，是不是这样的？
> 
> 对滴，你可算理解啦

哈哈，我这一开始思路就跑偏了。谢大佬了

**Comment by konstant2016** [comment]
> > > > > > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> > > > > 
> > > > > 
> > > > > 那getActivity ()和this不都是对象本身啊
> > > > 
> > > > 
> > > > getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
> > > > EventBus.getDefault().register(this)中的tihs，要求是对象自己
> > > 
> > > 
> > > EventBus.getDefault().register(this)中的tihs也就是fragment自己，getActiviy获取的是Activiy对象，是不是这样的？
> > 
> > 
> > 对滴，你可算理解啦
> 
> 哈哈，我这一开始思路就跑偏了。谢大佬了

有空翻一下源码，不需要多仔细，但是了解大致实现思路还是很有帮助的

**Comment by Luffys6** [comment]
> > > > > > > 你可以大致翻一下eventbus的源码，传入的 this 指的是对象本身，不是context
> > > > > > 
> > > > > > 
> > > > > > 那getActivity ()和this不都是对象本身啊
> > > > > 
> > > > > 
> > > > > getActiviy得到的是context，this指的是对象啊，fragment的对象是fragment自身，并不是context，
> > > > > EventBus.getDefault().register(this)中的tihs，要求是对象自己
> > > > 
> > > > 
> > > > EventBus.getDefault().register(this)中的tihs也就是fragment自己，getActiviy获取的是Activiy对象，是不是这样的？
> > > 
> > > 
> > > 对滴，你可算理解啦
> > 
> > 
> > 哈哈，我这一开始思路就跑偏了。谢大佬了
> 
> 有空翻一下源码，不需要多仔细，但是了解大致实现思路还是很有帮助的

嗯，刚看了一下，需要传入的参数是Object对象
