### ISSUE TITLE
Does not work when exchanging between activity and service in another process

### ISSUE THREAD

**Issue by DrMort-kam** [greenrobot/EventBus#621]
Good afternoon, my service is running in a different process than activity and when I try to make a post from service, the error "No subscribers registered" is displayed.
The debugger shows that the instances of EventBus.getDefault () are completely different. Is this normal or am I doing something wrong?
Everything starts to work fine if you remove android: process = ": ServiceProcess" from the manifest

**Comment by greenrobot-team** [comment]
This is normal. See #140 and https://stackoverflow.com/a/25568255/9187282.
