### ISSUE TITLE
Cannot update recycler view from GreenRobotEventBus

### ISSUE THREAD

**Issue by kauramanp** [greenrobot/EventBus#626]
I am trying to update recyclerview data from the event bus but nothing is happening. I am getting data in the event but data is not shown in the recycler view

@Subscribe(sticky=true)
    fun vehicleListEvent (data : VehicleListEvent){
        Log.e(TAG, "vehicle List Event ")
        try {
                vehicleListResponse = data.vehicleListResponse!!
                vehicleListResult = vehicleListResponse!!.vehicleListResult

                vehicleList.addAll(vehicleListResult!!.vehicleCategory!!)
                vehicleAdapter.notifyDataSetChanged()

                vehicleAdapter.append(vehicleListResponse!!.vehicleListResult!!.vehicleCategory!!);
                //vehicleAdapter.updateData(vehicleListResult.vehicleCategory!!);
                // vehicleAdapter.notifyDataSetChanged();
        }
        catch (exception : Exception )
        {
            Log.d("vehicle info" ,"vehicle List Event"+exception.toString())
        }
    }
Can anyone help me with this. Because there are many who are saying they cannot update recycler view with event bus there must be some solution.

**Comment by ice45571** [comment]
Had code jump to catch block and what's exception?

**Comment by kauramanp** [comment]
Problem was constraint layout as the height was set to 0dp. It was mot giving height to the view
