### ISSUE TITLE
cant receive multiple instances of the same sticky event class 

### ISSUE THREAD

**Issue by SaeedJinat** [greenrobot/EventBus#636]
ive stumbled upon a case where i need to deliver events from one screen to another ( android ) . 
for this i used sticky events , i have multiple instances of the same class  being posted as sticky events , yet my subscriber seems to receive only the latest sticky instance posted . 

ive done some investigation , and it starts with this member in Eventbus.java:
`private final Map<Class<?>, Object> stickyEvents;`

when a sticky event is posted , the put method to this map will overwrite any previous events put here . 

my question is that sth by design and has a reason for ? maybe related to not store multiple instances in memory . OR is it sth that i can work on to improve ?  and maybe  instead of mapping a class to a single object , we can do so to a collection of objects. 

ive also gone through test package for sticky events , although this test passes , its for two different types : 

```
@Test
    public void testPostStickyTwoEvents() throws InterruptedException {
        eventBus.postSticky("Sticky");  // String.class
        eventBus.postSticky(new IntTestEvent(7));  //IntTestEvent.class 
        eventBus.register(this);
        assertEquals(2, eventCount.intValue());
    } 
```

ive created this test for two sticky events with same class  , it fails : 
```
@Test
    public void testPostStickyTwoEventsSameClass() throws InterruptedException {
        eventBus.postSticky("Sticky1");
        eventBus.postSticky("Sticky2");
        eventBus.register(this);
        assertEquals(2, eventCount.intValue());
    }
```

please let me know if this is sth i can contribute and work on ? 

thank you

**Comment by greenrobot-team** [comment]
It is by design that only the latest sticky event is kept.
https://greenrobot.org/eventbus/documentation/configuration/sticky-events/
