### ISSUE TITLE
Unable to start activity ComponentInfo m.d.a.g: Subscriber class  and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by suryapratap1** [greenrobot/EventBus#649]
I am getting this error when "minifyEnabled true".

    java.lang.RuntimeException: Unable to start activity ComponentInfo m.d.a.g: Subscriber class  and its super classes have no public methods with the @Subscribe annotation

**Comment by greenrobot-team** [comment]
Check your R8 / ProGuard rules.
https://github.com/greenrobot/EventBus#r8-proguard

**Comment by arpit-korechi** [comment]
minifyEnabled false still I am getting this Error.
Please check SO for the description.
https://stackoverflow.com/questions/63341627/eventbusexception-its-super-classes-have-no-public-methods-with-the-subscribe

**Comment by ahyangnb** [comment]
Same problem

**Comment by sunreview** [comment]
t

> minifyEnabled false still I am getting this Error. Please check SO for the description. https://stackoverflow.com/questions/63341627/eventbusexception-its-super-classes-have-no-public-methods-with-the-subscribe

it is because u should register in MainFragment,not in MainActivity :)

**Comment by sunreview** [comment]
u should register in the class which contains the @subscribe method.
 probably u register in the wrong class :)

**Comment by greenrobot-team** [comment]
The original poster has not replied in a long time. Closing this.
