### ISSUE TITLE
i can't generate "MyEventBusIndex"

### ISSUE THREAD

**Issue by yanghuaangel** [greenrobot/EventBus#655]
i can't generate "MyEventBusIndex"

i read the guide https://greenrobot.org/eventbus/documentation/subscriber-index/

```
android {
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ eventBusIndex : 'com.example.myapp.MyEventBusIndex' ]
            }
        }
    }
}

dependencies {
    def eventbus_version = '3.2.0'
    implementation "org.greenrobot:eventbus:$eventbus_version"
    annotationProcessor "org.greenrobot:eventbus-annotation-processor:$eventbus_version"
}
```

but also can't generate "MyEventBusIndex"   
Is it possible reason  beacause the gradle verion or gladle plugin version?

**Comment by greenrobot-team** [comment]
I don't see anything wrong. Can you share a small example project? Or do you get an error message in your Build log?

**Comment by yanghuaangel** [comment]
it's my problem,now is solved

**Comment by MichaelJokAr** [comment]
how do you  solved?
