### ISSUE TITLE
Something different between my practice and README

### ISSUE THREAD

**Issue by Git-a-Live** [greenrobot/EventBus#664]
I tried to register and unregister EventBus in a subscriber Activity's `onStart` and `onStop` as README shows, then posted my event from a publisher Activity (codes are as follows). However, the subscriber didn't receive any event from the publisher, until I set `sticky = true` in the annotation @Subscribe and called `EventBus.getDefault().postSticky()` in publisher.

Moreover, I tried registering and unregistering EventBus in subsciber's `onCreate` and `onDestroy`, and ran the code without setting `sticky = true` or calling `EventBus.getDefault().postSticky()`, then it worked! The subscriber received an event from the publisher. So I wonder if there is something wrong with my practice, or README made a mistake?

```
//Subsciber Activity
class MainActivity : AppCompatActivity() {
    private val text: TextView by lazy {
        findViewById(R.id.text)
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        text.setOnClickListener {
            startActivity(Intent(this,MyActivity::class.java))
        }
    }

    override fun onStart() {
        super.onStart()
        EventBus.getDefault().register(this)
    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    fun onMessageEvent(message: Message) {
        text.text = message.myMessage
    }

    override fun onStop() {
        super.onStop()
        EventBus.getDefault().unregister(this)
    }
}

//Publisher Activity
class MyActivity : AppCompatActivity() {
    private val button: Button by lazy {
        findViewById(R.id.button)
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_my)
        button.setOnClickListener {
            EventBus.getDefault().post(Message("Hello World!"))
            finish()
        }
    }
}

//My event class
data class Message(
        val myMessage: String
)
```

**Comment by greenrobot-team** [comment]
The activity lifecycle does not work as you expect it does, have a look at https://developer.android.com/guide/components/activities/activity-lifecycle#coordinating-activities
