### ISSUE TITLE
No subscribers registered for event class when using kotlin value classes

### ISSUE THREAD

**Issue by Berki2021** [greenrobot/EventBus#671]
Today, I tried to use eventbus in combination with kotlins value classes (java inline classes) to reduce the overhead of created objects. What I found out was that this does not work and it gives the following error:

```
D/EventBus: No subscribers registered for event class com.example.app.presentation.documents.DocumentClickBusEvent
    No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
```

Here is the minimum code to reproduce the error:

### Event-Class

```
// object inside the value class doesn't matter, can also be Boolean or a custom Object
@JvmInline
value class MyEventClass(val string: String) 
```

### Adapter (Can be any other publisher as well, for example fragment or activity)

```
class DocumentListAdapter : ListAdapter<Document, DocumentListAdapter.DocumentViewHolder (Companion) {
    companion object : DiffUtil.ItemCallback<Document>() {
        // deleted for simplicity purpose
    }

    inner class DocumentViewHolder(val binding: DocumentListItemBinding) : RecyclerView.ViewHolder(binding.root)

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): DocumentViewHolder {
        // deleted for simplicity purpose
        return DocumentViewHolder(binding).also {
            binding.materialCardView.setOnClickListener {
                EventBus.getDefault().post(DocumentClickBusEvent(binding.document!!))
            }
        }
    }

    override fun onBindViewHolder(holder: DocumentViewHolder, position: Int) {
        // deleted for simplicity purpose
    }
}
```

### Fragment (Can be any other subscriber, for example activity)

```
class DocumentsFragment : Fragment() {

    override fun onCreate(savedInstanceState: Bundle?) {
        EventBus.getDefault().register(this)
        super.onCreate(savedInstanceState)
    }

    /**
      * !!! ERROR !!!!
      * No subscribers registered for event class com.example.app.presentation.documents.DocumentClickBusEvent
      *   No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
     */
    @Subscribe(sticky = false, threadMode = ThreadMode.POSTING)
    fun onDocumentClick(document: DocumentClickBusEvent) {
        // deleted for simplicity purpose
    }

    override fun onDestroy() {
        EventBus.getDefault().unregister(this)
        super.onDestroy()
    }
}
```

### Solution
Changing the event-class to a normal data-class solves the issue, but introduces the object-overhead.

```
data class MyEventClass(val string: String) 
```

**Comment by andob** [comment]
Seems logic to me. Value classes are transformed into their primitive counterparts. So, at runtime, you won't subscribe to an event of type MyEventClass, but to one of type String. I don't think value class support should be considered for this library, considering..

"the overhead of created objects". There is no such thing. Even more, specifically in your case. We're talking about 4 bytes that represent the pointer that holds the address in the heap. We're in 2021, devices with 8GB!! of RAM are common. There is an antipattern, it's called premature optimisation. Look it up on the internet. Basically, doing optimizations too early, such as not using enums and avoiding object instantiation leads to bad, unreadable, unnecesary complex code. Usually won't help with optimisation either. Saving few bytes of RAM / max few kb of RAM.. when the real overhead is in network overhead (API calls, backend queries, json serialization) and the bloated View system (have you seen the size of View.java file in the android source code?). Most of the times, even sqlite overhead is not worth considering. So please, stop doing premature optimisation, focus on clean code with elegant solutions (simple yet extensible) and then optimise.

Value classes are great in other context: If you want to instantiate thousands of them and do mathematic operations with them, can save lots of time. It's not your case.

Of course, this is a highly opinionated answer and I'm not even the author of this library. Hope it helps.

**Comment by Berki2021** [comment]
@andob it did, thank you very much. Closing this issue :)
