### ISSUE TITLE
eventbus-java not available on Maven Central

### ISSUE THREAD

**Issue by koczadly** [greenrobot/EventBus#683]
Apologies if I'm missing or misunderstanding something here.

The readme document mentions an `eventbus-java` artifact, presumably for use with non-Android apps. I've tried pasting the Maven dependency example into my project and it can't be resolved. Unlike the android variant, this one doesn't appear to be available on Maven Central — is it perhaps hosted elsewhere? Or is the proper use to only use the standard `eventbus` dependency, regardless of Android status.

**Comment by greenrobot-team** [comment]
`eventbus-java` is currently only available as a snapshot release. You need to add the Maven Central snapshot repository to use this preview. https://github.com/greenrobot/EventBus/issues/552#issuecomment-982645670

To use the current stable version use the 2.2.0 README: https://github.com/greenrobot/EventBus/tree/V3.2.0#add-eventbus-to-your-project

**Comment by greenrobot-team** [comment]
Latest release, with `eventbus-java`, available on Maven Central now. https://github.com/greenrobot/EventBus#add-eventbus-to-your-project

**Comment by koczadly** [comment]
> Latest release, with `eventbus-java`, available on Maven Central now. https://github.com/greenrobot/EventBus#add-eventbus-to-your-project

Awesome, thank you! 😊
