### ISSUE TITLE
Non Android ThreadMode behaviour

### ISSUE THREAD

**Issue by guoci** [greenrobot/EventBus#692]
On non-Android JVMs ThreadModes `MAIN` and `MAIN_ORDERED` follow the same behavior as documented for `POSTING`. Is that a feature or a bug?
The documentation for `MAIN` and `MAIN_ORDERED` seems to be only for Android.

**Comment by greenrobot-team** [comment]
https://github.com/greenrobot/EventBus/blob/1d995077d0b620a6aae9c60a8b96443113752305/EventBus/src/org/greenrobot/eventbus/ThreadMode.java#L38

Docs also say that this is the behavior if not Android, no?

**Comment by guoci** [comment]
Looks like `MAIN` is documented correctly in the code for non-Android JVMs. But `MAIN_ORDERED` doesn't document the non-Android behavior.
Also, I was referring to the documentation on https://greenrobot.org/eventbus/documentation/delivery-threads-threadmode/ for my original post.

**Comment by greenrobot-team** [comment]
@guoci Thanks for the hint, updated that page.
