### ISSUE TITLE
Does it work with Any ?

### ISSUE THREAD

**Issue by jimlyas** [greenrobot/EventBus#694]
So I would like to make a general function to subscribe to any event, because my component might subscribe to more than one event.

Does this work with EventBus? 

```kotlin
@Subscribe(threadMode = ThreadMode.BACKGROUND)
fun subscribeToAnything(event : Any) {
     when(event) {
           is EventA -> // do something for event A
           is EventB -> // do something for event B
     }
}
```

Thanks in advance.

**Comment by greenrobot-team** [comment]
To subscribe to more than one event, add a `@Subscribe` function for each event instead.
