### ISSUE TITLE
Experience of using EventBus

### ISSUE THREAD

**Issue by ANewAnonymous** [greenrobot/EventBus#698]
They all said that EventBus is not easy to use. Here I will give the name of EventBus. He is a very good framework. Since I used eventbus, my workload has increased every day, and I can work overtime consciously. I am the last person to leave the company. The boss used to look at me, but now he uses me as a positive teaching material for every meeting. The project in charge of another colleague of mine also used eventbus a lot and never wrote comments. Later, the technical team leader fired him. After recruiting for half a year, I ran 6 Androids. Later, the boss came to visit in person, only to invite the previous Android master back.

**Comment by greenrobot-team** [comment]
Cool story. Not an issue though so closing.
