### ISSUE TITLE
Could not resolve org.greenrobot:eventbus:3.3.1.

### ISSUE THREAD

**Issue by 582527512** [greenrobot/EventBus#701]
It's ok before then. After update gradle version to 7.4.2 , there got these question
"Could not resolve org.greenrobot:eventbus:3.3.1."
"Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html"

**Comment by greenrobot-team** [comment]
EventBus is available on Maven Central, as noted in the README. If you have Maven Central added to the repository section of your project it should be found:

```
repositories {
    mavenCentral()
}
```

**Comment by HJHL** [comment]
Check `settings.gradle` file in your project,

```gradle
dependencyResolutionManagement {
  repositories {
    // check if it exists, add it if not
    mavenCentral()
  }
}
```

**Comment by greenrobot-team** [comment]
@HJHL Thanks! This is the new way to declare repositories globally in Gradle: https://docs.gradle.org/current/userguide/dependency_management.html#sub:centralized-repository-declaration
