### ISSUE TITLE
tag missing problem 

### ISSUE THREAD

**Issue by CChengjie** [greenrobot/EventBus#705]
I'm doing a research on tags .
We found that versions like **3.1.2-RC** was released in Maven, but there was no corresponding tag in github, Can you help me with this?
1）What is the reason for tag's absence?

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、Don't care or is too trouble
- f、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?

**['9b1aeddcd3bab713b094d00e8043a2399bb97000']**

♥ This question is very important to our research. Thank you for your time!

**Comment by greenrobot-team** [comment]
1) c, but originally I guess this was not tagged because it is a preview release.

2) Yes, https://github.com/greenrobot/EventBus/commit/9b1aeddcd3bab713b094d00e8043a2399bb97000 is the associated commit.

Thanks, pushed the missing commits since V3.0.0.
