### ISSUE TITLE
 EventBus.getDefault().register Can it be put into asynchronous initialization?

### ISSUE THREAD

**Issue by AndroidLMY** [greenrobot/EventBus#722]
EventBus.getDefault().register是否可以放到异步初始化？

Translation:  EventBus.getDefault().register Can it be put into asynchronous initialization?

**Comment by mlzhang920802** [comment]
既然支持线程调度，理论上是支持的

**Comment by greenrobot-team** [comment]
`EventBus.getDefault()` is thread-safe, so that should not be an issue. But be aware that `register` will throw an exception if the subscriber is already registered. Maybe add a `isRegistered` check first.
